"""
Rebuilds GLOSSARY.md from every LESSON-*.md file in this same folder.

Full re-parse every run - no incremental "already processed" tracking.
Parsing plain-text lessons is cheap; a stale incremental index that
misses an edited lesson is a real, silent bug. Always re-derive from
the actual current files.

Usage:
    python build_glossary.py

Reads:  every LESSON-*.md in this folder's own "Terms used in this
        lesson" and "Objects and methods used" Header sections.
Writes: GLOSSARY.md, one line per term/object, alphabetical, each
        showing every lesson it appears in and a short excerpt - so a
        lookup never requires opening a lesson just to check whether
        something was already covered.
"""
import re
from pathlib import Path
from collections import defaultdict

CURRICULUM_DIR = Path(__file__).parent
TERMS_HEADER = "Terms used in this lesson"
OBJECTS_HEADER = "Objects and methods used"


def extract_section(text: str, header: str) -> str:
    """Return the text between a '## <header>' line and the next '## ' line."""
    pattern = re.compile(
        r"^##\s+" + re.escape(header) + r"\s*$(.*?)(?=^##\s|\Z)",
        re.MULTILINE | re.DOTALL,
    )
    match = pattern.search(text)
    return match.group(1) if match else ""


def split_names(raw_name: str):
    """A bolded entry name may be several backtick-wrapped names joined
    by ' / ' (e.g. "`Flask.test_client` / `FlaskClient.get`") - split
    those into separate real names instead of one combined string."""
    if "/" in raw_name and "`" in raw_name:
        parts = [p.strip().strip("`").strip() for p in raw_name.split("/")]
        return [p for p in parts if p]
    return [raw_name.strip().strip("`").strip()]


def parse_entries(section_text: str, is_objects_section: bool):
    """Split a section into top-level '- **Name**' entries. Returns a
    list of (name, snippet) tuples - one per name, after un-combining
    any '/'-joined names on one bullet.

    For the Objects section, the snippet always comes from the nested
    '*What it is:*' sub-bullet, never from trailing text on the name's
    own line (that trailing text is a parenthetical aside, e.g.
    "(the rebuild's own)", not a definition)."""
    lines = section_text.splitlines()
    entries = []  # list of (names_list, trailing_text, what_it_is)
    current_names = None
    current_trailing = ""
    current_what_it_is = ""

    def flush():
        if current_names is None:
            return
        snippet = (
            current_what_it_is
            if is_objects_section
            else (current_trailing or current_what_it_is)
        )
        for name in current_names:
            entries.append((name, snippet))

    for line in lines:
        top_level_bullet = re.match(r"^- \*\*(.+?)\*\*\s*(.*)$", line)
        if top_level_bullet:
            flush()
            current_names = split_names(top_level_bullet.group(1).strip())
            current_trailing = top_level_bullet.group(2).lstrip("— -").strip()
            current_what_it_is = ""
            continue
        if current_names is not None:
            what_it_is = re.match(r"^\s*-\s*\*What it is:\*\s*(.*)$", line)
            if what_it_is and not current_what_it_is:
                current_what_it_is = what_it_is.group(1).strip()
    flush()
    return entries


def main():
    lesson_files = sorted(
        p for p in CURRICULUM_DIR.rglob("LESSON-*.md")
        if not any(part.upper().startswith("ARCHIVE") for part in p.relative_to(CURRICULUM_DIR).parts)
    )
    if not lesson_files:
        print("No LESSON-*.md files found in", CURRICULUM_DIR)
        return

    glossary = defaultdict(list)  # name -> list of (lesson_stem, kind, snippet)

    for path in lesson_files:
        text = path.read_text(encoding="utf-8")
        lesson_stem = path.stem

        terms_section = extract_section(text, TERMS_HEADER)
        for name, snippet in parse_entries(terms_section, is_objects_section=False):
            glossary[name].append((lesson_stem, "Term", snippet))

        objects_section = extract_section(text, OBJECTS_HEADER)
        for name, snippet in parse_entries(objects_section, is_objects_section=True):
            glossary[name].append((lesson_stem, "Object/method", snippet))

    lines = [
        "# Glossary",
        "",
        "Auto-generated by `build_glossary.py` - do not edit by hand;",
        "re-run the script after any lesson changes instead.",
        "",
    ]

    for name in sorted(glossary.keys(), key=str.lower):
        lines.append(f"## {name}")
        for lesson_stem, kind, snippet in glossary[name]:
            snippet_display = snippet if snippet else "(no inline snippet found)"
            lines.append(f"- **{kind}** in `{lesson_stem}` - {snippet_display}")
        lines.append("")

    # Light collision check: flag distinct names that share a whole word,
    # for manual review - not a hard failure, just a prompt to go look.
    # Expected domain words filtered out - otherwise every HTTP/Flask/
    # test-related pair "collides" on a word that's supposed to be
    # everywhere, drowning out anything actually worth a second look.
    STOPWORDS = {
        "test", "tests", "flask", "http", "get", "route", "routing",
        "json", "mock", "url", "request", "response", "code", "status",
        "object", "app",
    }

    def words(name: str):
        return set(re.findall(r"[a-zA-Z]+", name.lower())) - STOPWORDS

    def is_expected_parent_child(name_a: str, name_b: str) -> bool:
        """'Socket' vs 'socket.accept', or 'socket.accept' vs
        'socket.bind', aren't real collisions to review - they're
        methods named after (or siblings of) the real object they
        belong to, on purpose. Skip this pattern generally instead of
        hardcoding every domain word (flask, http, socket, ...) into
        STOPWORDS by hand as each new topic gets taught."""
        a, b = name_a.lower().strip("`"), name_b.lower().strip("`")
        if b.startswith(a + ".") or a.startswith(b + "."):
            return True
        if "." in a and "." in b and a.split(".")[0] == b.split(".")[0]:
            return True
        return False

    names = sorted(glossary.keys(), key=str.lower)
    collisions = []
    for i, name_a in enumerate(names):
        for name_b in names[i + 1 :]:
            if name_a == name_b or is_expected_parent_child(name_a, name_b):
                continue
            shared = words(name_a) & words(name_b)
            if shared:
                collisions.append((name_a, name_b, shared))

    if collisions:
        lines.append("## Possible collisions (shared words, different names)")
        lines.append("")
        lines.append(
            "Not necessarily a problem - review each one. A real violation "
            "looks like two different names that could be confused with "
            "each other (e.g. \"freestanding\" vs \"free function\")."
        )
        lines.append("")
        for name_a, name_b, shared in collisions:
            lines.append(f"- `{name_a}` / `{name_b}` - shares: {', '.join(sorted(shared))}")
        lines.append("")

    output_path = CURRICULUM_DIR / "GLOSSARY.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output_path} - {len(glossary)} unique terms/objects across {len(lesson_files)} lessons.")
    if collisions:
        print(f"{len(collisions)} possible collision(s) flagged - see bottom of GLOSSARY.md.")


if __name__ == "__main__":
    main()
