export interface SeriesMeta {
  id: string
  label: string
  lang: string
  emoji: string
  description: string
  levels: { level: number; title: string; file: string }[]
}

export const SERIES: SeriesMeta[] = [
  {
    id: 'python-fundamentals',
    label: 'Python Fundamentals',
    lang: 'python',
    emoji: '🐍',
    description: 'Learn Python the way professionals think about it — not just the syntax, but how the interpreter works, how to read and debug code, and the CS and SE ideas underneath every line.',
    levels: [
      // Phase 0 — The Programmer's Mental Model
      { level: 0,  title: 'What Programming Is',          file: 'python-fundamentals/level-0.md'  },
      { level: 1,  title: 'How Python Reads Your Code',   file: 'python-fundamentals/level-1.md'  },
      { level: 2,  title: 'The Debugger',                 file: 'python-fundamentals/level-2.md'  },
      { level: 3,  title: 'Reading Error Messages',       file: 'python-fundamentals/level-3.md'  },
      // Phase 1 — Core Language
      { level: 4,  title: 'print()',                      file: 'python-fundamentals/level-4.md'  },
      { level: 5,  title: 'Variables',                    file: 'python-fundamentals/level-5.md'  },
      { level: 6,  title: 'Types',                        file: 'python-fundamentals/level-6.md'  },
      { level: 7,  title: 'Numbers & Arithmetic',         file: 'python-fundamentals/level-7.md'  },
      { level: 8,  title: 'Strings',                      file: 'python-fundamentals/level-8.md'  },
      { level: 9,  title: 'String Methods',               file: 'python-fundamentals/level-9.md'  },
      { level: 10, title: 'f-strings',                    file: 'python-fundamentals/level-10.md' },
      { level: 11, title: 'Comments',                     file: 'python-fundamentals/level-11.md' },
      { level: 12, title: 'Input & Type Conversion',       file: 'python-fundamentals/level-12.md' },
      { level: 13, title: 'Comparisons & Booleans',       file: 'python-fundamentals/level-13.md' },
      { level: 14, title: 'if / elif / else',             file: 'python-fundamentals/level-14.md' },
      { level: 15, title: 'while Loops',                  file: 'python-fundamentals/level-15.md' },
      { level: 16, title: 'for Loops',                    file: 'python-fundamentals/level-16.md' },
      { level: 17, title: 'range()',                      file: 'python-fundamentals/level-17.md' },
      { level: 18, title: 'Functions',                    file: 'python-fundamentals/level-18.md' },
      { level: 19, title: 'Scope',                        file: 'python-fundamentals/level-19.md' },
      { level: 20, title: 'Lists',                        file: 'python-fundamentals/level-20.md' },
      { level: 21, title: 'List Methods',                 file: 'python-fundamentals/level-21.md' },
      { level: 22, title: 'Tuples',                       file: 'python-fundamentals/level-22.md' },
      { level: 23, title: 'Dictionaries',                 file: 'python-fundamentals/level-23.md' },
      { level: 24, title: 'Sets',                         file: 'python-fundamentals/level-24.md' },
      { level: 25, title: 'Modules & Imports',            file: 'python-fundamentals/level-25.md' },
      { level: 26, title: 'Exceptions',                   file: 'python-fundamentals/level-26.md' },
      // Phase 2 — Writing Programs
      { level: 27, title: 'List Comprehensions',          file: 'python-fundamentals/level-27.md' },
      { level: 28, title: 'Files',                         file: 'python-fundamentals/level-28.md' },
      { level: 29, title: 'Testing',                      file: 'python-fundamentals/level-29.md' },
      { level: 30, title: 'Refactoring',                  file: 'python-fundamentals/level-30.md' },
      // Phase 3 — Professional Python
      { level: 31, title: 'Type Hints',                   file: 'python-fundamentals/level-31.md' },
      { level: 32, title: 'Virtual Environments & pip',   file: 'python-fundamentals/level-32.md' },
      { level: 33, title: 'Formatting & Linting',         file: 'python-fundamentals/level-33.md' },
      { level: 34, title: 'JSON',                         file: 'python-fundamentals/level-34.md' },
      { level: 35, title: 'CSV',                          file: 'python-fundamentals/level-35.md' },
      { level: 36, title: 'SQLite',                       file: 'python-fundamentals/level-36.md' },
    ],
  },
  {
    id: 'dsa-python',
    label: 'Data Structures & Algorithms in Python',
    lang: 'python',
    emoji: '🧮',
    description: 'Master the core DSA patterns used in every technical interview and production codebase — lists, two pointers, hash maps, stacks, queues, linked lists, binary search, recursion, sorting, trees, and graphs.',
    levels: [
      { level: 0,  title: 'Lists & Indexing',      file: 'dsa-python/level-0.md'  },
      { level: 1,  title: 'Two Pointers',           file: 'dsa-python/level-1.md'  },
      { level: 2,  title: 'Hash Maps & Sets',       file: 'dsa-python/level-2.md'  },
      { level: 3,  title: 'Stacks',                 file: 'dsa-python/level-3.md'  },
      { level: 4,  title: 'Queues & Deques',        file: 'dsa-python/level-4.md'  },
      { level: 5,  title: 'Linked Lists',           file: 'dsa-python/level-5.md'  },
      { level: 6,  title: 'Binary Search',          file: 'dsa-python/level-6.md'  },
      { level: 7,  title: 'Recursion',              file: 'dsa-python/level-7.md'  },
      { level: 8,  title: 'Sorting',                file: 'dsa-python/level-8.md'  },
      { level: 9,  title: 'Trees',                  file: 'dsa-python/level-9.md'  },
      { level: 10, title: 'Graphs',                 file: 'dsa-python/level-10.md' },
    ],
  },
  {
    id: 'cpp-fundamentals',
    label: 'C++ Fundamentals',
    lang: 'cpp',
    emoji: 'C++',
    description: 'Learn C++ with the lesson engine: syntax-highlighted examples, runnable C/C++ subset demos, and debug-oriented explanations of stack, heap, values, and references.',
    levels: [
      { level: 0, title: 'Types, Variables & main()',      file: 'cpp-fundamentals/level-0.md' },
      { level: 1, title: 'Control Flow',                  file: 'cpp-fundamentals/level-1.md' },
      { level: 2, title: 'Functions',                     file: 'cpp-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays & Pointers',             file: 'cpp-fundamentals/level-3.md' },
      { level: 4, title: 'References & Pass-by-Reference',file: 'cpp-fundamentals/level-4.md' },
      { level: 5, title: 'Structs',                       file: 'cpp-fundamentals/level-5.md' },
      { level: 6, title: 'Classes & Constructors',        file: 'cpp-fundamentals/level-6.md' },
      { level: 7, title: 'Strings & the Standard Library',file: 'cpp-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'csharp-fundamentals',
    label: 'C# Fundamentals',
    lang: 'csharp',
    emoji: 'C#',
    description: 'Learn C# from types and methods through classes, interfaces, generics, and LINQ — with a focus on how the .NET runtime works.',
    levels: [
      { level: 0, title: 'Types, Variables & Methods', file: 'csharp-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Properties',       file: 'csharp-fundamentals/level-1.md' },
      { level: 2, title: 'Interfaces & Generics',      file: 'csharp-fundamentals/level-2.md' },
      { level: 3, title: 'LINQ & Collections',         file: 'csharp-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'java-fundamentals',
    label: 'Java Fundamentals',
    lang: 'java',
    emoji: 'Java',
    description: 'Learn Java from types and main() through classes, inheritance, interfaces, and the Collections/Streams framework.',
    levels: [
      { level: 0, title: 'Types, Variables & main()', file: 'java-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Methods',         file: 'java-fundamentals/level-1.md' },
      { level: 2, title: 'Inheritance & Interfaces',  file: 'java-fundamentals/level-2.md' },
      { level: 3, title: 'Collections & Streams',     file: 'java-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'css-selectors',
    label: 'CSS Selectors',
    lang: 'css',
    emoji: 'CSS',
    description: 'Go beyond type, class, and ID selectors. Learn combinators, attribute selectors, structural and form pseudo-classes, :not() / :is() / :where() / :has(), pseudo-elements, and cascade layers.',
    levels: [
      { level: 0, title: 'Combinators',              file: 'css-selectors/level-0.md' },
      { level: 1, title: 'Attribute Selectors',       file: 'css-selectors/level-1.md' },
      { level: 2, title: 'Structural Pseudo-classes', file: 'css-selectors/level-2.md' },
      { level: 3, title: 'Form Pseudo-classes',       file: 'css-selectors/level-3.md' },
      { level: 4, title: ':not(), :is(), :where()',   file: 'css-selectors/level-4.md' },
      { level: 5, title: ':has() — The Parent Selector', file: 'css-selectors/level-5.md' },
      { level: 6, title: 'Pseudo-elements',           file: 'css-selectors/level-6.md' },
      { level: 7, title: 'Cascade Layers',            file: 'css-selectors/level-7.md' },
    ],
  },
  {
    id: 'css-box-model',
    label: 'CSS Box Model',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the box model from the ground up: content, padding, border, margin, box-sizing, overflow, display types, min/max/clamp sizing, and stacking contexts with z-index.',
    levels: [
      { level: 0, title: 'The Box Model',                   file: 'css-box-model/level-0.md' },
      { level: 1, title: 'box-sizing: border-box',          file: 'css-box-model/level-1.md' },
      { level: 2, title: 'Margin & Margin Collapsing',      file: 'css-box-model/level-2.md' },
      { level: 3, title: 'Border & Outline',                file: 'css-box-model/level-3.md' },
      { level: 4, title: 'Overflow',                        file: 'css-box-model/level-4.md' },
      { level: 5, title: 'Display — Block, Inline, Inline-Block', file: 'css-box-model/level-5.md' },
      { level: 6, title: 'Sizing — min, max, clamp',        file: 'css-box-model/level-6.md' },
      { level: 7, title: 'Stacking Contexts & z-index',     file: 'css-box-model/level-7.md' },
    ],
  },
  {
    id: 'css-layout',
    label: 'CSS Layout',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the full layout cascade: normal flow, block formatting contexts, all five position values, floats, containing blocks, and stacking contexts. The foundation every other layout system builds on.',
    levels: [
      { level: 0, title: 'Normal Flow',                   file: 'css-layout/level-0.md' },
      { level: 1, title: 'Block Formatting Contexts',     file: 'css-layout/level-1.md' },
      { level: 2, title: 'position: relative',            file: 'css-layout/level-2.md' },
      { level: 3, title: 'position: absolute',            file: 'css-layout/level-3.md' },
      { level: 4, title: 'position: fixed and sticky',    file: 'css-layout/level-4.md' },
      { level: 5, title: 'Floats',                        file: 'css-layout/level-5.md' },
      { level: 6, title: 'The Containing Block',          file: 'css-layout/level-6.md' },
      { level: 7, title: 'Stacking Contexts and z-index', file: 'css-layout/level-7.md' },
    ],
  },
  {
    id: 'css-fundamentals',
    label: 'CSS Fundamentals',
    lang: 'css',
    emoji: 'CSS',
    description: 'Learn what CSS is, how rules work, the full colour system, units, typography, inheritance, the cascade, specificity, custom properties, and how to debug styles in the browser. No prerequisites.',
    levels: [
      { level: 0, title: 'What CSS Is',             file: 'css-fundamentals/level-0.md' },
      { level: 1, title: 'Selectors — Type, Class & ID', file: 'css-fundamentals/level-1.md' },
      { level: 2, title: 'Colors',                  file: 'css-fundamentals/level-2.md' },
      { level: 3, title: 'Units',                   file: 'css-fundamentals/level-3.md' },
      { level: 4, title: 'Text & Fonts',            file: 'css-fundamentals/level-4.md' },
      { level: 5, title: 'Inheritance',             file: 'css-fundamentals/level-5.md' },
      { level: 6, title: 'The Cascade',             file: 'css-fundamentals/level-6.md' },
      { level: 7, title: 'Specificity Deep Dive',   file: 'css-fundamentals/level-7.md' },
      { level: 8, title: 'Custom Properties',       file: 'css-fundamentals/level-8.md' },
      { level: 9, title: 'Reading & Debugging CSS', file: 'css-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'css-flexbox',
    label: 'CSS Flexbox',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master one-dimensional layout: flex containers, main and cross axis alignment, flex-grow/shrink/basis, wrapping, gaps, and real-world patterns like navbars, sidebars, and card grids.',
    levels: [
      { level: 0, title: 'The Flex Container',                    file: 'css-flexbox/level-0.md' },
      { level: 1, title: 'justify-content',                       file: 'css-flexbox/level-1.md' },
      { level: 2, title: 'align-items and align-self',            file: 'css-flexbox/level-2.md' },
      { level: 3, title: 'flex-wrap',                             file: 'css-flexbox/level-3.md' },
      { level: 4, title: 'flex-grow, flex-shrink, flex-basis',    file: 'css-flexbox/level-4.md' },
      { level: 5, title: 'gap and order',                         file: 'css-flexbox/level-5.md' },
      { level: 6, title: 'Nested Flex Containers',                file: 'css-flexbox/level-6.md' },
      { level: 7, title: 'Real-World Flex Patterns',              file: 'css-flexbox/level-7.md' },
      { level: 8, title: 'Flexbox vs Grid',                       file: 'css-flexbox/level-8.md' },
    ],
  },
  {
    id: 'css-grid',
    label: 'CSS Grid',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master two-dimensional layout: grid containers and items, repeat/fr/minmax, explicit placement, named areas, alignment, auto-flow, and real-world patterns like dashboards and magazine layouts.',
    levels: [
      { level: 0, title: 'The Grid Container',              file: 'css-grid/level-0.md' },
      { level: 1, title: 'repeat(), fr, and minmax()',       file: 'css-grid/level-1.md' },
      { level: 2, title: 'Grid Placement',                  file: 'css-grid/level-2.md' },
      { level: 3, title: 'grid-template-areas',             file: 'css-grid/level-3.md' },
      { level: 4, title: 'Grid Alignment',                  file: 'css-grid/level-4.md' },
      { level: 5, title: 'Auto-flow and Implicit Grids',    file: 'css-grid/level-5.md' },
      { level: 6, title: 'Real-World Grid Patterns',        file: 'css-grid/level-6.md' },
      { level: 7, title: 'Grid and Flexbox Together',       file: 'css-grid/level-7.md' },
    ],
  },
  {
    id: 'javascript-fundamentals',
    label: 'JavaScript Fundamentals',
    lang: 'javascript',
    emoji: 'JS',
    description: 'Learn JavaScript the way the runtime works — values, functions, scope, closures, objects, classes, async/await, and modules. No browser required; pure JS from first principles.',
    levels: [
      { level: 0, title: 'Values & Variables',      file: 'javascript-fundamentals/level-0.md' },
      { level: 1, title: 'Functions',               file: 'javascript-fundamentals/level-1.md' },
      { level: 2, title: 'Scope & the Call Stack',  file: 'javascript-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays',                  file: 'javascript-fundamentals/level-3.md' },
      { level: 4, title: 'Objects',                 file: 'javascript-fundamentals/level-4.md' },
      { level: 5, title: 'Loops & Iteration',       file: 'javascript-fundamentals/level-5.md' },
      { level: 6, title: 'Closures',                file: 'javascript-fundamentals/level-6.md' },
      { level: 7, title: 'Classes',                 file: 'javascript-fundamentals/level-7.md' },
      { level: 8, title: 'Promises & async/await',  file: 'javascript-fundamentals/level-8.md' },
      { level: 9, title: 'Modules',                 file: 'javascript-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'html-dom',
    label: 'HTML, DOM, and JavaScript',
    lang: 'html',
    emoji: 'DOM',
    description: 'Build browser-side skills from the ground up: query the DOM, respond to events, manage forms, and apply the state-driven render pattern that powers every modern framework.',
    levels: [
      { level: 0,  title: 'The Browser Environment',         file: 'html-dom/level-0.md'  },
      { level: 1,  title: 'querySelector & the DOM Tree',    file: 'html-dom/level-1.md'  },
      { level: 2,  title: 'Reading & Writing DOM Properties',file: 'html-dom/level-2.md'  },
      { level: 3,  title: 'classList',                       file: 'html-dom/level-3.md'  },
      { level: 4,  title: 'Creating & Inserting Elements',   file: 'html-dom/level-4.md'  },
      { level: 5,  title: 'Removing & Replacing Elements',   file: 'html-dom/level-5.md'  },
      { level: 6,  title: 'Events & addEventListener',       file: 'html-dom/level-6.md'  },
      { level: 7,  title: 'The Event Object & Bubbling',     file: 'html-dom/level-7.md'  },
      { level: 8,  title: 'Forms & Input Elements',          file: 'html-dom/level-8.md'  },
      { level: 9,  title: 'Data Attributes',                 file: 'html-dom/level-9.md'  },
      { level: 10, title: 'Rendering Lists from Data',       file: 'html-dom/level-10.md' },
      { level: 11, title: 'State & Re-rendering',            file: 'html-dom/level-11.md' },
    ],
  },
  {
    id: 'contributor-series',
    label: 'How to Contribute',
    lang: 'javascript',
    emoji: '🤝',
    description: 'Build the skills you need to contribute to this project: Markdown, Git, branches and PRs, reading unfamiliar code, writing great educational content, React components, the theming system, and making your first pull request.',
    levels: [
      { level: 0, title: 'What Markdown Is',                file: 'contributor-series/level-0.md' },
      { level: 1, title: 'Git Basics — Saving Your Work',   file: 'contributor-series/level-1.md' },
      { level: 2, title: 'Branches and Pull Requests',      file: 'contributor-series/level-2.md' },
      { level: 3, title: 'Reading Code You Didn\'t Write',  file: 'contributor-series/level-3.md' },
      { level: 4, title: 'How to Teach Through Code',       file: 'contributor-series/level-4.md' },
      { level: 5, title: 'Understanding Components',        file: 'contributor-series/level-5.md' },
      { level: 6, title: 'The Theming System',              file: 'contributor-series/level-6.md' },
      { level: 7, title: 'Your First Contribution',         file: 'contributor-series/level-7.md' },
    ],
  },
  {
    id: 'css-visual-design',
    label: 'CSS Visual Design',
    lang: 'css',
    emoji: 'CSS',
    description: 'Design with intention: color theory and HSL palettes, typography hierarchy, spacing systems, shadows and depth, WCAG accessibility, dark mode, and design tokens that tie it all together.',
    levels: [
      { level: 0, title: 'Color Theory for the Web',       file: 'css-visual-design/level-0.md' },
      { level: 1, title: 'Typography Hierarchy',           file: 'css-visual-design/level-1.md' },
      { level: 2, title: 'Spacing Systems',                file: 'css-visual-design/level-2.md' },
      { level: 3, title: 'Shadows and Depth',              file: 'css-visual-design/level-3.md' },
      { level: 4, title: 'Contrast and Accessibility',     file: 'css-visual-design/level-4.md' },
      { level: 5, title: 'Dark Mode with Custom Properties', file: 'css-visual-design/level-5.md' },
      { level: 6, title: 'Design Tokens and Theming Systems', file: 'css-visual-design/level-6.md' },
      { level: 7, title: 'A Complete Design System in CSS', file: 'css-visual-design/level-7.md' },
    ],
  },
  {
    id: 'css-professional',
    label: 'CSS Professional',
    lang: 'css',
    emoji: 'CSS',
    description: 'Write CSS at production scale: cascade layers, native HTML elements (dialog, details, popover), state ownership, CSS/JS integration, scroll-driven animations, @property, and professional methodology.',
    levels: [
      { level: 0, title: 'Cascade Layers',                  file: 'css-professional/level-0.md' },
      { level: 1, title: 'Native HTML Elements',            file: 'css-professional/level-1.md' },
      { level: 2, title: 'CSS Owns the State',              file: 'css-professional/level-2.md' },
      { level: 3, title: 'CSS and JavaScript',              file: 'css-professional/level-3.md' },
      { level: 4, title: 'Scroll-Driven Animations',        file: 'css-professional/level-4.md' },
      { level: 5, title: '@property — Typed Custom Properties', file: 'css-professional/level-5.md' },
      { level: 6, title: 'Maintainable CSS at Scale',       file: 'css-professional/level-6.md' },
      { level: 7, title: 'Professional CSS Reference',      file: 'css-professional/level-7.md' },
    ],
  },
  {
    id: 'css-responsive',
    label: 'CSS Responsive Design',
    lang: 'css',
    emoji: 'CSS',
    description: 'Build layouts that work on any screen: viewport units, media queries, mobile-first strategy, fluid typography with clamp(), responsive images, auto-fit/minmax grids, and container queries.',
    levels: [
      { level: 0, title: 'The Viewport and CSS Pixels',            file: 'css-responsive/level-0.md' },
      { level: 1, title: 'Media Queries',                          file: 'css-responsive/level-1.md' },
      { level: 2, title: 'Mobile-First Design',                    file: 'css-responsive/level-2.md' },
      { level: 3, title: 'Responsive Typography',                  file: 'css-responsive/level-3.md' },
      { level: 4, title: 'Responsive Images and Media',            file: 'css-responsive/level-4.md' },
      { level: 5, title: 'Responsive Layouts Without Media Queries', file: 'css-responsive/level-5.md' },
      { level: 6, title: 'Container Queries',                      file: 'css-responsive/level-6.md' },
      { level: 7, title: 'A Complete Responsive Page',             file: 'css-responsive/level-7.md' },
    ],
  },
  {
    id: 'css-animation',
    label: 'CSS Animations',
    lang: 'css',
    emoji: 'CSS',
    description: 'Bring UIs to life: CSS transitions, transform, @keyframes animations, easing functions, UI micro-animations, staggered effects, and performance-safe animation with prefers-reduced-motion.',
    levels: [
      { level: 0, title: 'CSS Transitions',                file: 'css-animation/level-0.md' },
      { level: 1, title: 'CSS Transform',                  file: 'css-animation/level-1.md' },
      { level: 2, title: '@keyframes',                     file: 'css-animation/level-2.md' },
      { level: 3, title: 'Easing Functions',               file: 'css-animation/level-3.md' },
      { level: 4, title: 'UI Micro-animations',            file: 'css-animation/level-4.md' },
      { level: 5, title: 'Animation Patterns',             file: 'css-animation/level-5.md' },
      { level: 6, title: 'Performance and Accessibility',  file: 'css-animation/level-6.md' },
    ],
  },
  {
    id: 'typescript-fundamentals',
    label: 'TypeScript Fundamentals',
    lang: 'typescript',
    emoji: 'TS',
    description: 'Add types to JavaScript: type annotations and inference, interfaces and type aliases, union/intersection types, generics, utility types, narrowing, classes, and modules.',
    levels: [
      { level: 0, title: 'Types and Type Annotations',    file: 'typescript-fundamentals/level-0.md' },
      { level: 1, title: 'Interfaces and Type Aliases',   file: 'typescript-fundamentals/level-1.md' },
      { level: 2, title: 'Union and Intersection Types',  file: 'typescript-fundamentals/level-2.md' },
      { level: 3, title: 'Generics',                      file: 'typescript-fundamentals/level-3.md' },
      { level: 4, title: 'Utility Types',                 file: 'typescript-fundamentals/level-4.md' },
      { level: 5, title: 'Narrowing and Type Guards',     file: 'typescript-fundamentals/level-5.md' },
      { level: 6, title: 'Classes and Access Modifiers',  file: 'typescript-fundamentals/level-6.md' },
      { level: 7, title: 'Modules and Declaration Files', file: 'typescript-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'sql-fundamentals',
    label: 'SQL Fundamentals',
    lang: 'sql',
    emoji: 'SQL',
    description: 'Query and design relational databases: SELECT, WHERE, ORDER BY, aggregates, GROUP BY, JOINs, subqueries, CTEs, INSERT/UPDATE/DELETE, schema design, and indexes.',
    levels: [
      { level: 0, title: 'What SQL Is',                file: 'sql-fundamentals/level-0.md' },
      { level: 1, title: 'SELECT and FROM',            file: 'sql-fundamentals/level-1.md' },
      { level: 2, title: 'Sorting, Limiting, Distinct',file: 'sql-fundamentals/level-2.md' },
      { level: 3, title: 'Aggregates and GROUP BY',    file: 'sql-fundamentals/level-3.md' },
      { level: 4, title: 'JOINs',                     file: 'sql-fundamentals/level-4.md' },
      { level: 5, title: 'Subqueries and CTEs',        file: 'sql-fundamentals/level-5.md' },
      { level: 6, title: 'INSERT, UPDATE, DELETE',     file: 'sql-fundamentals/level-6.md' },
      { level: 7, title: 'Schema Design and Indexes',  file: 'sql-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'backend-fundamentals',
    label: 'Backend Fundamentals',
    lang: 'javascript',
    emoji: 'BE',
    description: 'Build production-quality APIs with Node.js and Express: HTTP, routing, middleware, async handlers, SQL injection prevention, JWTs, bcrypt, database integration, testing, and deployment.',
    levels: [
      { level: 0, title: 'What Backend Is',                    file: 'backend-fundamentals/level-0.md' },
      { level: 1, title: 'Express.js and Routing',             file: 'backend-fundamentals/level-1.md' },
      { level: 2, title: 'Async Handlers and Error Handling',  file: 'backend-fundamentals/level-2.md' },
      { level: 3, title: 'Authentication (JWT and bcrypt)',     file: 'backend-fundamentals/level-3.md' },
      { level: 4, title: 'Database Integration',               file: 'backend-fundamentals/level-4.md' },
      { level: 5, title: 'Environment Variables and Config',   file: 'backend-fundamentals/level-5.md' },
      { level: 6, title: 'Testing APIs',                       file: 'backend-fundamentals/level-6.md' },
      { level: 7, title: 'Deployment',                         file: 'backend-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'git-version-control',
    label: 'Git & Version Control',
    lang: 'bash',
    emoji: 'Git',
    description: 'Master version control from the ground up: the three states, core workflow, branches, merging, remotes, pull requests, rebase, stash, fixing mistakes, and professional Git workflows.',
    levels: [
      { level: 0, title: 'What Git Is',                    file: 'git-version-control/level-0.md' },
      { level: 1, title: 'The Core Workflow',              file: 'git-version-control/level-1.md' },
      { level: 2, title: 'Branches and Merging',           file: 'git-version-control/level-2.md' },
      { level: 3, title: 'Remote Repositories and GitHub', file: 'git-version-control/level-3.md' },
      { level: 4, title: 'Pull Requests and Code Review',  file: 'git-version-control/level-4.md' },
      { level: 5, title: 'Rebase, Stash, and Fixing Mistakes', file: 'git-version-control/level-5.md' },
      { level: 6, title: 'Git Workflows',                  file: 'git-version-control/level-6.md' },
      { level: 7, title: 'Git Mastery Reference',          file: 'git-version-control/level-7.md' },
    ],
  },
  {
    id: 'git-advanced',
    label: 'Git Advanced',
    lang: 'bash',
    emoji: 'Git',
    description: 'Go beyond the daily workflow: Git internals (the object model), reflog recovery, bisect debugging, cherry-pick, interactive rebase, forensics (blame, pickaxe), hooks, submodules, worktrees, rerere, and .gitattributes.',
    levels: [
      { level: 0, title: 'Git Internals — The Object Model',              file: 'git-advanced/level-0.md' },
      { level: 1, title: 'Reflog — Git\'s Safety Net',                    file: 'git-advanced/level-1.md' },
      { level: 2, title: 'git bisect — Binary Search Debugging',          file: 'git-advanced/level-2.md' },
      { level: 3, title: 'git cherry-pick — Surgical Commit Application', file: 'git-advanced/level-3.md' },
      { level: 4, title: 'Interactive Rebase — Rewriting History',        file: 'git-advanced/level-4.md' },
      { level: 5, title: 'Git Forensics — blame, log, and Archaeology',   file: 'git-advanced/level-5.md' },
      { level: 6, title: 'Git Hooks — Automation at Every Step',          file: 'git-advanced/level-6.md' },
      { level: 7, title: 'Advanced Git — Submodules, Worktrees, rerere',  file: 'git-advanced/level-7.md' },
    ],
  },
  {
    id: 'software-construction',
    label: 'Software Construction',
    lang: 'javascript',
    emoji: '🏗️',
    description: 'The bridge between knowing a language and building real software: decomposition, function design, modules, error handling, configuration, data modeling, state, coupling, dependency injection, project structure, refactoring, testing, extension, and designing for change.',
    levels: [
      { level: 0,  title: 'From Script to Program',              file: 'software-construction/level-0.md' },
      { level: 1,  title: 'Decomposing Problems',                file: 'software-construction/level-1.md' },
      { level: 2,  title: 'Designing Functions',                 file: 'software-construction/level-2.md' },
      { level: 3,  title: 'Modules and Public APIs',             file: 'software-construction/level-3.md' },
      { level: 4,  title: 'Error Handling',                      file: 'software-construction/level-4.md' },
      { level: 5,  title: 'Configuration',                       file: 'software-construction/level-5.md' },
      { level: 6,  title: 'Data Modeling',                       file: 'software-construction/level-6.md' },
      { level: 7,  title: 'State Management',                    file: 'software-construction/level-7.md' },
      { level: 8,  title: 'Coupling and Cohesion',               file: 'software-construction/level-8.md' },
      { level: 9,  title: 'Dependency Injection and Interfaces', file: 'software-construction/level-9.md' },
      { level: 10, title: 'Organising Larger Projects',          file: 'software-construction/level-10.md' },
      { level: 11, title: 'Refactoring',                         file: 'software-construction/level-11.md' },
      { level: 12, title: 'Testing as You Build',                file: 'software-construction/level-12.md' },
      { level: 13, title: 'Extending Existing Systems',          file: 'software-construction/level-13.md' },
      { level: 14, title: 'Designing for Change',                file: 'software-construction/level-14.md' },
    ],
  },
  {
    id: 'cs-foundations',
    label: 'CS Foundations',
    lang: 'javascript',
    emoji: '🖥️',
    description: 'The machine model behind every program: how computers execute instructions, bits and bytes, the stack and heap, how functions work at the machine level, data structures in memory, complexity analysis, recursion and memoisation, and how the OS runs your process.',
    levels: [
      { level: 0, title: 'What Computers Actually Do',              file: 'cs-foundations/level-0.md' },
      { level: 1, title: 'Bits, Bytes, and Number Systems',        file: 'cs-foundations/level-1.md' },
      { level: 2, title: 'Memory — The Stack and the Heap',        file: 'cs-foundations/level-2.md' },
      { level: 3, title: 'How Functions Really Work',              file: 'cs-foundations/level-3.md' },
      { level: 4, title: 'How Data Structures Work in Memory',     file: 'cs-foundations/level-4.md' },
      { level: 5, title: 'Complexity — How Fast Is Your Code?',   file: 'cs-foundations/level-5.md' },
      { level: 6, title: 'Recursion and Its Cost',                 file: 'cs-foundations/level-6.md' },
      { level: 7, title: 'How the OS Runs Your Program',          file: 'cs-foundations/level-7.md' },
      { level: 8, title: 'CS Foundations — Putting It All Together', file: 'cs-foundations/level-8.md' },
    ],
  },
  {
    id: 'debugging-fundamentals',
    label: 'Debugging Fundamentals',
    lang: 'javascript',
    emoji: '🔍',
    description: 'The scientific method applied to code: the five-step debugging process, reading error messages and stack traces, using the interactive debugger, structured logging, binary search for localisation, bug categories, async debugging, and building permanent debugging habits.',
    levels: [
      { level: 0, title: 'What Debugging Actually Is',        file: 'debugging-fundamentals/level-0.md' },
      { level: 1, title: 'Reading Error Messages',            file: 'debugging-fundamentals/level-1.md' },
      { level: 2, title: 'Using the Debugger',                file: 'debugging-fundamentals/level-2.md' },
      { level: 3, title: 'Logging and Observability',         file: 'debugging-fundamentals/level-3.md' },
      { level: 4, title: 'Isolating Bugs — Divide and Conquer', file: 'debugging-fundamentals/level-4.md' },
      { level: 5, title: 'Categories of Bugs',                file: 'debugging-fundamentals/level-5.md' },
      { level: 6, title: 'Debugging Async Code',              file: 'debugging-fundamentals/level-6.md' },
      { level: 7, title: 'Debugging Fundamentals — Putting It Together', file: 'debugging-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'functional-programming',
    label: 'Functional Programming',
    lang: 'javascript',
    emoji: '🔗',
    description: 'Pure functions, immutability, higher-order functions, function composition, currying and partial application, handling absence and failure with Maybe and Result, and applying functional patterns to real data pipelines and state management.',
    levels: [
      { level: 0, title: 'What Functional Programming Is',          file: 'functional-programming/level-0.md' },
      { level: 1, title: 'Higher-Order Functions',                  file: 'functional-programming/level-1.md' },
      { level: 2, title: 'Function Composition',                    file: 'functional-programming/level-2.md' },
      { level: 3, title: 'Currying and Partial Application',        file: 'functional-programming/level-3.md' },
      { level: 4, title: 'Handling Absence and Failure Functionally', file: 'functional-programming/level-4.md' },
      { level: 5, title: 'Functional Patterns in Practice',         file: 'functional-programming/level-5.md' },
    ],
  },
  {
    id: 'database-design',
    label: 'Database Design',
    lang: 'sql',
    emoji: '🗄️',
    description: 'Relational database fundamentals: ACID guarantees, entities and relationships, primary and foreign keys, the three normal forms, indexes and query planning, multi-table joins and aggregation, and safe schema migrations with the expand-contract pattern.',
    levels: [
      { level: 0, title: 'What Databases Are For',                  file: 'database-design/level-0.md' },
      { level: 1, title: 'Entities, Relationships, and Keys',       file: 'database-design/level-1.md' },
      { level: 2, title: 'Normalisation — Eliminating Redundancy',  file: 'database-design/level-2.md' },
      { level: 3, title: 'Indexes — Making Queries Fast',           file: 'database-design/level-3.md' },
      { level: 4, title: 'Querying Across Tables — Joins',          file: 'database-design/level-4.md' },
      { level: 5, title: 'Migrations and Schema Evolution',         file: 'database-design/level-5.md' },
    ],
  },
  {
    id: 'browser-apis',
    label: 'Browser APIs',
    lang: 'javascript',
    emoji: '🌐',
    description: 'The browser as a platform: the environment model and sandbox, DOM events and event delegation, the Fetch API and its error model, client-side storage (localStorage/sessionStorage), and how to combine them all into resilient browser applications.',
    levels: [
      { level: 0, title: 'The Browser Environment',               file: 'browser-apis/level-0.md' },
      { level: 1, title: 'Events and the Event Loop',             file: 'browser-apis/level-1.md' },
      { level: 2, title: 'Fetch — Network Requests in the Browser', file: 'browser-apis/level-2.md' },
      { level: 3, title: 'Storage APIs',                          file: 'browser-apis/level-3.md' },
      { level: 4, title: 'Browser APIs — Putting It Together',    file: 'browser-apis/level-4.md' },
    ],
  },
  {
    id: 'devops-concepts',
    label: 'DevOps Concepts',
    lang: 'javascript',
    emoji: '🚀',
    description: 'The full path from code to production: the DevOps mindset, environment variables and secrets management, CI/CD pipelines with GitHub Actions, Docker containers and images, deployment strategies (rolling, blue-green, canary), and production-ready server startup with health checks and graceful shutdown.',
    levels: [
      { level: 0, title: 'What DevOps Is',                         file: 'devops-concepts/level-0.md' },
      { level: 1, title: 'Environment Variables and Configuration', file: 'devops-concepts/level-1.md' },
      { level: 2, title: 'CI/CD — Automating the Pipeline',        file: 'devops-concepts/level-2.md' },
      { level: 3, title: 'Containers and Docker',                  file: 'devops-concepts/level-3.md' },
      { level: 4, title: 'Deployment — Getting Code to Production',file: 'devops-concepts/level-4.md' },
      { level: 5, title: 'DevOps — Putting It Together',           file: 'devops-concepts/level-5.md' },
    ],
  },
  {
    id: 'clean-code',
    label: 'Clean Code',
    lang: 'javascript',
    emoji: '✨',
    description: 'Write code that communicates: what clean code is and why it matters, naming variables and functions well, writing functions that do one thing, the right use of comments (WHY not WHAT), code structure and guard clauses, and a full refactoring case study pulling all four skills together.',
    levels: [
      { level: 0, title: 'What Clean Code Is',        file: 'clean-code/level-0.md' },
      { level: 1, title: 'Naming Things Well',         file: 'clean-code/level-1.md' },
      { level: 2, title: 'Functions — One Thing, Done Well', file: 'clean-code/level-2.md' },
      { level: 3, title: 'Comments — When and What to Write', file: 'clean-code/level-3.md' },
      { level: 4, title: 'Code Structure and Layout', file: 'clean-code/level-4.md' },
      { level: 5, title: 'Clean Code — Putting It Together', file: 'clean-code/level-5.md' },
    ],
  },
  {
    id: 'oop-design',
    label: 'OOP Design',
    lang: 'javascript',
    emoji: '🏛️',
    description: 'Object-oriented design from first principles: encapsulation and polymorphism, inheritance vs. composition, the SOLID principles (SRP, OCP, LSP, ISP, DIP), and the most important design patterns (Observer, Strategy, Decorator, Factory) — culminating in a full system design case study.',
    levels: [
      { level: 0, title: 'What Object-Oriented Design Is',          file: 'oop-design/level-0.md' },
      { level: 1, title: 'Inheritance and Composition',             file: 'oop-design/level-1.md' },
      { level: 2, title: 'SOLID Principles',                        file: 'oop-design/level-2.md' },
      { level: 3, title: 'Design Patterns — Structural and Behavioural', file: 'oop-design/level-3.md' },
      { level: 4, title: 'OOP Design — Putting It Together',        file: 'oop-design/level-4.md' },
    ],
  },
  {
    id: 'testing-fundamentals',
    label: 'Testing Fundamentals',
    lang: 'javascript',
    emoji: '🧪',
    description: 'Build a complete testing practice: why tests matter (and what they don\'t guarantee), unit test structure with Arrange-Act-Assert, edge cases and error paths, test doubles (fakes, stubs, spies, mocks), testing async code and controlling time, integration test setup, and a full payment service test suite.',
    levels: [
      { level: 0, title: 'Why We Test',                              file: 'testing-fundamentals/level-0.md' },
      { level: 1, title: 'Unit Tests — Structure and Patterns',     file: 'testing-fundamentals/level-1.md' },
      { level: 2, title: 'Test Doubles — Mocks, Stubs, and Fakes', file: 'testing-fundamentals/level-2.md' },
      { level: 3, title: 'Integration Tests and Testing Async Code',file: 'testing-fundamentals/level-3.md' },
      { level: 4, title: 'Testing Fundamentals — Putting It Together', file: 'testing-fundamentals/level-4.md' },
    ],
  },
  {
    id: 'async-programming',
    label: 'Async Programming',
    lang: 'javascript',
    emoji: '⚡',
    description: 'Master JavaScript\'s concurrency model: the event loop (call stack, microtask queue, task queue), Promises and their state machine, all four combinators (all/allSettled/race/any), async/await patterns and pitfalls (sequential vs parallel, loops, generators), and production patterns (retry with backoff, semaphore, cancellation, work queue).',
    levels: [
      { level: 0, title: 'Concurrency Without Threads — The Event Loop Model', file: 'async-programming/level-0.md' },
      { level: 1, title: 'Promises Deep Dive',                                 file: 'async-programming/level-1.md' },
      { level: 2, title: 'Async/Await Patterns and Pitfalls',                  file: 'async-programming/level-2.md' },
      { level: 3, title: 'Async Patterns — Queues, Retries, and Cancellation', file: 'async-programming/level-3.md' },
      { level: 4, title: 'Async Programming — Putting It Together',            file: 'async-programming/level-4.md' },
    ],
  },
  {
    id: 'performance-engineering',
    label: 'Performance Engineering',
    lang: 'javascript',
    emoji: '📈',
    description: 'Make the right code fast: the performance engineering mindset (measure → bottleneck → fix), in-memory caching with TTL and LRU eviction, the N+1 query problem and batching, EXPLAIN-based index design, the DataLoader pattern, and a complete case-study optimisation workflow.',
    levels: [
      { level: 0, title: 'What Performance Engineering Is',   file: 'performance-engineering/level-0.md' },
      { level: 1, title: 'Caching — The Fastest Operation Is No Operation', file: 'performance-engineering/level-1.md' },
      { level: 2, title: 'Database Query Performance',        file: 'performance-engineering/level-2.md' },
      { level: 3, title: 'Performance Engineering — Putting It Together', file: 'performance-engineering/level-3.md' },
    ],
  },
  {
    id: 'frontend-engineering',
    label: 'Frontend Engineering',
    lang: 'javascript',
    emoji: '🖥',
    description: 'Professional browser application patterns: the state→render→event model, component thinking, shared stores and the reducer pattern with selectors, accessible HTML and ARIA, keyboard navigation and focus management, and a complete accessible filterable product list case study.',
    levels: [
      { level: 0, title: 'The Frontend Engineering Model', file: 'frontend-engineering/level-0.md' },
      { level: 1, title: 'State Management Patterns',      file: 'frontend-engineering/level-1.md' },
      { level: 2, title: 'Accessibility and Inclusive Design', file: 'frontend-engineering/level-2.md' },
      { level: 3, title: 'Frontend Engineering — Putting It Together', file: 'frontend-engineering/level-3.md' },
    ],
  },
  {
    id: 'web-security',
    label: 'Web Security',
    lang: 'javascript',
    emoji: '🔐',
    description: 'Understand web security the way attackers do — trust boundaries, injection attacks (SQL, XSS, command), authentication, sessions, and defence-in-depth patterns for production applications.',
    levels: [
      { level: 0, title: 'The Web Security Mindset',                      file: 'web-security/level-0.md' },
      { level: 1, title: 'Injection — SQL, XSS, and Command Injection',   file: 'web-security/level-1.md' },
      { level: 2, title: 'Authentication and Session Security',            file: 'web-security/level-2.md' },
      { level: 3, title: 'Web Security — Putting It Together',            file: 'web-security/level-3.md' },
    ],
  },
  {
    id: 'design-patterns',
    label: 'Design Patterns',
    lang: 'javascript',
    emoji: '🧩',
    description: 'Learn the Gang of Four patterns as a vocabulary for common design problems — Factory, Builder, Decorator, Proxy, Facade, Observer, Strategy, Command, and State — with modern JavaScript idioms.',
    levels: [
      { level: 0, title: 'What Design Patterns Are',                             file: 'design-patterns/level-0.md' },
      { level: 1, title: 'Creational Patterns — Factory, Builder, Singleton',    file: 'design-patterns/level-1.md' },
      { level: 2, title: 'Structural Patterns — Adapter, Decorator, Proxy, Facade', file: 'design-patterns/level-2.md' },
      { level: 3, title: 'Behavioural Patterns — Observer, Strategy, Command, State', file: 'design-patterns/level-3.md' },
      { level: 4, title: 'Design Patterns — Putting It Together',                file: 'design-patterns/level-4.md' },
    ],
  },
  {
    id: 'rest-apis',
    label: 'REST APIs',
    lang: 'javascript',
    emoji: '🌐',
    description: 'Design and build production REST APIs: HTTP methods and status codes, request/response conventions, pagination, authentication, rate limiting, versioning, and consistent error handling.',
    levels: [
      { level: 0, title: 'What REST Is',                                        file: 'rest-apis/level-0.md' },
      { level: 1, title: 'HTTP Status Codes and Error Handling',                file: 'rest-apis/level-1.md' },
      { level: 2, title: 'Request and Response Design',                         file: 'rest-apis/level-2.md' },
      { level: 3, title: 'Authentication, Rate Limiting, and API Design Patterns', file: 'rest-apis/level-3.md' },
      { level: 4, title: 'REST APIs — Putting It Together',                     file: 'rest-apis/level-4.md' },
    ],
  },
  {
    id: 'react-fundamentals',
    label: 'React Fundamentals',
    lang: 'javascript',
    emoji: '⚛️',
    description: 'Build real React applications: the UI-as-function-of-state model, useState and event handling, useEffect and data fetching, component composition, custom hooks, and putting it together in a complete feature.',
    levels: [
      { level: 0, title: 'What React Is and Why It Exists',     file: 'react-fundamentals/level-0.md' },
      { level: 1, title: 'useState and Event Handling',          file: 'react-fundamentals/level-1.md' },
      { level: 2, title: 'useEffect and Data Fetching',          file: 'react-fundamentals/level-2.md' },
      { level: 3, title: 'Component Composition and Custom Hooks', file: 'react-fundamentals/level-3.md' },
      { level: 4, title: 'React — Putting It Together',          file: 'react-fundamentals/level-4.md' },
    ],
  },
]

export function getSeries(id: string): SeriesMeta | undefined {
  return SERIES.find(s => s.id === id)
}
