export interface SeriesMeta {
  id: string
  label: string
  lang: string
  emoji: string
  description: string
  levels: { level: number; title: string; file: string }[]
}

export const SERIES: SeriesMeta[] = [
  {
    id: 'python-fundamentals',
    label: 'Python Fundamentals',
    lang: 'python',
    emoji: '🐍',
    description: 'Learn Python the way professionals think about it — not just the syntax, but how the interpreter works, how to read and debug code, and the CS and SE ideas underneath every line.',
    levels: [
      // Phase 0 — The Programmer's Mental Model
      { level: 0,  title: 'What Programming Is',          file: 'python-fundamentals/level-0.md'  },
      { level: 1,  title: 'How Python Reads Your Code',   file: 'python-fundamentals/level-1.md'  },
      { level: 2,  title: 'The Debugger',                 file: 'python-fundamentals/level-2.md'  },
      { level: 3,  title: 'Reading Error Messages',       file: 'python-fundamentals/level-3.md'  },
      // Phase 1 — Core Language
      { level: 4,  title: 'print()',                      file: 'python-fundamentals/level-4.md'  },
      { level: 5,  title: 'Variables',                    file: 'python-fundamentals/level-5.md'  },
      { level: 6,  title: 'Types',                        file: 'python-fundamentals/level-6.md'  },
      { level: 7,  title: 'Numbers & Arithmetic',         file: 'python-fundamentals/level-7.md'  },
      { level: 8,  title: 'Strings',                      file: 'python-fundamentals/level-8.md'  },
      { level: 9,  title: 'String Methods',               file: 'python-fundamentals/level-9.md'  },
      { level: 10, title: 'f-strings',                    file: 'python-fundamentals/level-10.md' },
      { level: 11, title: 'Comments',                     file: 'python-fundamentals/level-11.md' },
      { level: 12, title: 'Input & Type Conversion',       file: 'python-fundamentals/level-12.md' },
      { level: 13, title: 'Comparisons & Booleans',       file: 'python-fundamentals/level-13.md' },
      { level: 14, title: 'if / elif / else',             file: 'python-fundamentals/level-14.md' },
      { level: 15, title: 'while Loops',                  file: 'python-fundamentals/level-15.md' },
      { level: 16, title: 'for Loops',                    file: 'python-fundamentals/level-16.md' },
      { level: 17, title: 'range()',                      file: 'python-fundamentals/level-17.md' },
      { level: 18, title: 'Functions',                    file: 'python-fundamentals/level-18.md' },
      { level: 19, title: 'Scope',                        file: 'python-fundamentals/level-19.md' },
      { level: 20, title: 'Lists',                        file: 'python-fundamentals/level-20.md' },
      { level: 21, title: 'List Methods',                 file: 'python-fundamentals/level-21.md' },
      { level: 22, title: 'Tuples',                       file: 'python-fundamentals/level-22.md' },
      { level: 23, title: 'Dictionaries',                 file: 'python-fundamentals/level-23.md' },
      { level: 24, title: 'Sets',                         file: 'python-fundamentals/level-24.md' },
      { level: 25, title: 'Modules & Imports',            file: 'python-fundamentals/level-25.md' },
      { level: 26, title: 'Exceptions',                   file: 'python-fundamentals/level-26.md' },
      // Phase 2 — Writing Programs
      { level: 27, title: 'List Comprehensions',          file: 'python-fundamentals/level-27.md' },
      { level: 28, title: 'Files',                         file: 'python-fundamentals/level-28.md' },
      { level: 29, title: 'Testing',                      file: 'python-fundamentals/level-29.md' },
      { level: 30, title: 'Refactoring',                  file: 'python-fundamentals/level-30.md' },
      // Phase 3 — Professional Python
      { level: 31, title: 'Type Hints',                   file: 'python-fundamentals/level-31.md' },
      { level: 32, title: 'Virtual Environments & pip',   file: 'python-fundamentals/level-32.md' },
      { level: 33, title: 'Formatting & Linting',         file: 'python-fundamentals/level-33.md' },
      { level: 34, title: 'JSON',                         file: 'python-fundamentals/level-34.md' },
      { level: 35, title: 'CSV',                          file: 'python-fundamentals/level-35.md' },
      { level: 36, title: 'SQLite',                       file: 'python-fundamentals/level-36.md' },
    ],
  },
  {
    id: 'dsa-python',
    label: 'Data Structures & Algorithms in Python',
    lang: 'python',
    emoji: '🧮',
    description: 'Master the core DSA patterns used in every technical interview and production codebase — lists, two pointers, hash maps, stacks, queues, linked lists, binary search, recursion, sorting, trees, and graphs.',
    levels: [
      { level: 0,  title: 'Lists & Indexing',      file: 'dsa-python/level-0.md'  },
      { level: 1,  title: 'Two Pointers',           file: 'dsa-python/level-1.md'  },
      { level: 2,  title: 'Hash Maps & Sets',       file: 'dsa-python/level-2.md'  },
      { level: 3,  title: 'Stacks',                 file: 'dsa-python/level-3.md'  },
      { level: 4,  title: 'Queues & Deques',        file: 'dsa-python/level-4.md'  },
      { level: 5,  title: 'Linked Lists',           file: 'dsa-python/level-5.md'  },
      { level: 6,  title: 'Binary Search',          file: 'dsa-python/level-6.md'  },
      { level: 7,  title: 'Recursion',              file: 'dsa-python/level-7.md'  },
      { level: 8,  title: 'Sorting',                file: 'dsa-python/level-8.md'  },
      { level: 9,  title: 'Trees',                  file: 'dsa-python/level-9.md'  },
      { level: 10, title: 'Graphs',                 file: 'dsa-python/level-10.md' },
    ],
  },
  {
    id: 'cpp-fundamentals',
    label: 'C++ Fundamentals',
    lang: 'cpp',
    emoji: 'C++',
    description: 'Learn C++ with the lesson engine: syntax-highlighted examples, runnable C/C++ subset demos, and debug-oriented explanations of stack, heap, values, and references.',
    levels: [
      { level: 0, title: 'Types, Variables & main()',      file: 'cpp-fundamentals/level-0.md' },
      { level: 1, title: 'Control Flow',                  file: 'cpp-fundamentals/level-1.md' },
      { level: 2, title: 'Functions',                     file: 'cpp-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays & Pointers',             file: 'cpp-fundamentals/level-3.md' },
      { level: 4, title: 'References & Pass-by-Reference',file: 'cpp-fundamentals/level-4.md' },
      { level: 5, title: 'Structs',                       file: 'cpp-fundamentals/level-5.md' },
      { level: 6, title: 'Classes & Constructors',        file: 'cpp-fundamentals/level-6.md' },
      { level: 7, title: 'Strings & the Standard Library',file: 'cpp-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'csharp-fundamentals',
    label: 'C# Fundamentals',
    lang: 'csharp',
    emoji: 'C#',
    description: 'Learn C# from types and methods through classes, interfaces, generics, and LINQ — with a focus on how the .NET runtime works.',
    levels: [
      { level: 0, title: 'Types, Variables & Methods', file: 'csharp-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Properties',       file: 'csharp-fundamentals/level-1.md' },
      { level: 2, title: 'Interfaces & Generics',      file: 'csharp-fundamentals/level-2.md' },
      { level: 3, title: 'LINQ & Collections',         file: 'csharp-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'java-fundamentals',
    label: 'Java Fundamentals',
    lang: 'java',
    emoji: 'Java',
    description: 'Learn Java from types and main() through classes, inheritance, interfaces, and the Collections/Streams framework.',
    levels: [
      { level: 0, title: 'Types, Variables & main()', file: 'java-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Methods',         file: 'java-fundamentals/level-1.md' },
      { level: 2, title: 'Inheritance & Interfaces',  file: 'java-fundamentals/level-2.md' },
      { level: 3, title: 'Collections & Streams',     file: 'java-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'css-selectors',
    label: 'CSS Selectors',
    lang: 'css',
    emoji: 'CSS',
    description: 'Go beyond type, class, and ID selectors. Learn combinators, attribute selectors, structural and form pseudo-classes, :not() / :is() / :where() / :has(), pseudo-elements, and cascade layers.',
    levels: [
      { level: 0, title: 'Combinators',              file: 'css-selectors/level-0.md' },
      { level: 1, title: 'Attribute Selectors',       file: 'css-selectors/level-1.md' },
      { level: 2, title: 'Structural Pseudo-classes', file: 'css-selectors/level-2.md' },
      { level: 3, title: 'Form Pseudo-classes',       file: 'css-selectors/level-3.md' },
      { level: 4, title: ':not(), :is(), :where()',   file: 'css-selectors/level-4.md' },
      { level: 5, title: ':has() — The Parent Selector', file: 'css-selectors/level-5.md' },
      { level: 6, title: 'Pseudo-elements',           file: 'css-selectors/level-6.md' },
      { level: 7, title: 'Cascade Layers',            file: 'css-selectors/level-7.md' },
    ],
  },
  {
    id: 'css-box-model',
    label: 'CSS Box Model',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the box model from the ground up: content, padding, border, margin, box-sizing, overflow, display types, min/max/clamp sizing, and stacking contexts with z-index.',
    levels: [
      { level: 0, title: 'The Box Model',                   file: 'css-box-model/level-0.md' },
      { level: 1, title: 'box-sizing: border-box',          file: 'css-box-model/level-1.md' },
      { level: 2, title: 'Margin & Margin Collapsing',      file: 'css-box-model/level-2.md' },
      { level: 3, title: 'Border & Outline',                file: 'css-box-model/level-3.md' },
      { level: 4, title: 'Overflow',                        file: 'css-box-model/level-4.md' },
      { level: 5, title: 'Display — Block, Inline, Inline-Block', file: 'css-box-model/level-5.md' },
      { level: 6, title: 'Sizing — min, max, clamp',        file: 'css-box-model/level-6.md' },
      { level: 7, title: 'Stacking Contexts & z-index',     file: 'css-box-model/level-7.md' },
    ],
  },
  {
    id: 'css-layout',
    label: 'CSS Layout',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the full layout cascade: normal flow, block formatting contexts, all five position values, floats, containing blocks, and stacking contexts. The foundation every other layout system builds on.',
    levels: [
      { level: 0, title: 'Normal Flow',                   file: 'css-layout/level-0.md' },
      { level: 1, title: 'Block Formatting Contexts',     file: 'css-layout/level-1.md' },
      { level: 2, title: 'position: relative',            file: 'css-layout/level-2.md' },
      { level: 3, title: 'position: absolute',            file: 'css-layout/level-3.md' },
      { level: 4, title: 'position: fixed and sticky',    file: 'css-layout/level-4.md' },
      { level: 5, title: 'Floats',                        file: 'css-layout/level-5.md' },
      { level: 6, title: 'The Containing Block',          file: 'css-layout/level-6.md' },
      { level: 7, title: 'Stacking Contexts and z-index', file: 'css-layout/level-7.md' },
    ],
  },
  {
    id: 'css-fundamentals',
    label: 'CSS Fundamentals',
    lang: 'css',
    emoji: 'CSS',
    description: 'Learn what CSS is, how rules work, the full colour system, units, typography, inheritance, the cascade, specificity, custom properties, and how to debug styles in the browser. No prerequisites.',
    levels: [
      { level: 0, title: 'What CSS Is',             file: 'css-fundamentals/level-0.md' },
      { level: 1, title: 'Selectors — Type, Class & ID', file: 'css-fundamentals/level-1.md' },
      { level: 2, title: 'Colors',                  file: 'css-fundamentals/level-2.md' },
      { level: 3, title: 'Units',                   file: 'css-fundamentals/level-3.md' },
      { level: 4, title: 'Text & Fonts',            file: 'css-fundamentals/level-4.md' },
      { level: 5, title: 'Inheritance',             file: 'css-fundamentals/level-5.md' },
      { level: 6, title: 'The Cascade',             file: 'css-fundamentals/level-6.md' },
      { level: 7, title: 'Specificity Deep Dive',   file: 'css-fundamentals/level-7.md' },
      { level: 8, title: 'Custom Properties',       file: 'css-fundamentals/level-8.md' },
      { level: 9, title: 'Reading & Debugging CSS', file: 'css-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'css-flexbox',
    label: 'CSS Flexbox',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master one-dimensional layout: flex containers, main and cross axis alignment, flex-grow/shrink/basis, wrapping, gaps, and real-world patterns like navbars, sidebars, and card grids.',
    levels: [
      { level: 0, title: 'The Flex Container',                    file: 'css-flexbox/level-0.md' },
      { level: 1, title: 'justify-content',                       file: 'css-flexbox/level-1.md' },
      { level: 2, title: 'align-items and align-self',            file: 'css-flexbox/level-2.md' },
      { level: 3, title: 'flex-wrap',                             file: 'css-flexbox/level-3.md' },
      { level: 4, title: 'flex-grow, flex-shrink, flex-basis',    file: 'css-flexbox/level-4.md' },
      { level: 5, title: 'gap and order',                         file: 'css-flexbox/level-5.md' },
      { level: 6, title: 'Nested Flex Containers',                file: 'css-flexbox/level-6.md' },
      { level: 7, title: 'Real-World Flex Patterns',              file: 'css-flexbox/level-7.md' },
      { level: 8, title: 'Flexbox vs Grid',                       file: 'css-flexbox/level-8.md' },
    ],
  },
  {
    id: 'css-grid',
    label: 'CSS Grid',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master two-dimensional layout: grid containers and items, repeat/fr/minmax, explicit placement, named areas, alignment, auto-flow, and real-world patterns like dashboards and magazine layouts.',
    levels: [
      { level: 0, title: 'The Grid Container',              file: 'css-grid/level-0.md' },
      { level: 1, title: 'repeat(), fr, and minmax()',       file: 'css-grid/level-1.md' },
      { level: 2, title: 'Grid Placement',                  file: 'css-grid/level-2.md' },
      { level: 3, title: 'grid-template-areas',             file: 'css-grid/level-3.md' },
      { level: 4, title: 'Grid Alignment',                  file: 'css-grid/level-4.md' },
      { level: 5, title: 'Auto-flow and Implicit Grids',    file: 'css-grid/level-5.md' },
      { level: 6, title: 'Real-World Grid Patterns',        file: 'css-grid/level-6.md' },
      { level: 7, title: 'Grid and Flexbox Together',       file: 'css-grid/level-7.md' },
    ],
  },
  {
    id: 'javascript-fundamentals',
    label: 'JavaScript Fundamentals',
    lang: 'javascript',
    emoji: 'JS',
    description: 'Learn JavaScript the way the runtime works — values, functions, scope, closures, objects, classes, async/await, and modules. No browser required; pure JS from first principles.',
    levels: [
      { level: 0, title: 'Values & Variables',      file: 'javascript-fundamentals/level-0.md' },
      { level: 1, title: 'Functions',               file: 'javascript-fundamentals/level-1.md' },
      { level: 2, title: 'Scope & the Call Stack',  file: 'javascript-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays',                  file: 'javascript-fundamentals/level-3.md' },
      { level: 4, title: 'Objects',                 file: 'javascript-fundamentals/level-4.md' },
      { level: 5, title: 'Loops & Iteration',       file: 'javascript-fundamentals/level-5.md' },
      { level: 6, title: 'Closures',                file: 'javascript-fundamentals/level-6.md' },
      { level: 7, title: 'Classes',                 file: 'javascript-fundamentals/level-7.md' },
      { level: 8, title: 'Promises & async/await',  file: 'javascript-fundamentals/level-8.md' },
      { level: 9, title: 'Modules',                 file: 'javascript-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'html-dom',
    label: 'HTML, DOM, and JavaScript',
    lang: 'html',
    emoji: 'DOM',
    description: 'Build browser-side skills from the ground up: query the DOM, respond to events, manage forms, and apply the state-driven render pattern that powers every modern framework.',
    levels: [
      { level: 0,  title: 'The Browser Environment',         file: 'html-dom/level-0.md'  },
      { level: 1,  title: 'querySelector & the DOM Tree',    file: 'html-dom/level-1.md'  },
      { level: 2,  title: 'Reading & Writing DOM Properties',file: 'html-dom/level-2.md'  },
      { level: 3,  title: 'classList',                       file: 'html-dom/level-3.md'  },
      { level: 4,  title: 'Creating & Inserting Elements',   file: 'html-dom/level-4.md'  },
      { level: 5,  title: 'Removing & Replacing Elements',   file: 'html-dom/level-5.md'  },
      { level: 6,  title: 'Events & addEventListener',       file: 'html-dom/level-6.md'  },
      { level: 7,  title: 'The Event Object & Bubbling',     file: 'html-dom/level-7.md'  },
      { level: 8,  title: 'Forms & Input Elements',          file: 'html-dom/level-8.md'  },
      { level: 9,  title: 'Data Attributes',                 file: 'html-dom/level-9.md'  },
      { level: 10, title: 'Rendering Lists from Data',       file: 'html-dom/level-10.md' },
      { level: 11, title: 'State & Re-rendering',            file: 'html-dom/level-11.md' },
    ],
  },
  {
    id: 'contributor-series',
    label: 'How to Contribute',
    lang: 'javascript',
    emoji: '🤝',
    description: 'Build the skills you need to contribute to this project: Markdown, Git, branches and PRs, reading unfamiliar code, writing great educational content, React components, the theming system, and making your first pull request.',
    levels: [
      { level: 0, title: 'What Markdown Is',                file: 'contributor-series/level-0.md' },
      { level: 1, title: 'Git Basics — Saving Your Work',   file: 'contributor-series/level-1.md' },
      { level: 2, title: 'Branches and Pull Requests',      file: 'contributor-series/level-2.md' },
      { level: 3, title: 'Reading Code You Didn\'t Write',  file: 'contributor-series/level-3.md' },
      { level: 4, title: 'How to Teach Through Code',       file: 'contributor-series/level-4.md' },
      { level: 5, title: 'Understanding Components',        file: 'contributor-series/level-5.md' },
      { level: 6, title: 'The Theming System',              file: 'contributor-series/level-6.md' },
      { level: 7, title: 'Your First Contribution',         file: 'contributor-series/level-7.md' },
    ],
  },
  {
    id: 'css-visual-design',
    label: 'CSS Visual Design',
    lang: 'css',
    emoji: 'CSS',
    description: 'Design with intention: color theory and HSL palettes, typography hierarchy, spacing systems, shadows and depth, WCAG accessibility, dark mode, and design tokens that tie it all together.',
    levels: [
      { level: 0, title: 'Color Theory for the Web',       file: 'css-visual-design/level-0.md' },
      { level: 1, title: 'Typography Hierarchy',           file: 'css-visual-design/level-1.md' },
      { level: 2, title: 'Spacing Systems',                file: 'css-visual-design/level-2.md' },
      { level: 3, title: 'Shadows and Depth',              file: 'css-visual-design/level-3.md' },
      { level: 4, title: 'Contrast and Accessibility',     file: 'css-visual-design/level-4.md' },
      { level: 5, title: 'Dark Mode with Custom Properties', file: 'css-visual-design/level-5.md' },
      { level: 6, title: 'Design Tokens and Theming Systems', file: 'css-visual-design/level-6.md' },
      { level: 7, title: 'A Complete Design System in CSS', file: 'css-visual-design/level-7.md' },
    ],
  },
  {
    id: 'css-professional',
    label: 'CSS Professional',
    lang: 'css',
    emoji: 'CSS',
    description: 'Write CSS at production scale: cascade layers, native HTML elements (dialog, details, popover), state ownership, CSS/JS integration, scroll-driven animations, @property, and professional methodology.',
    levels: [
      { level: 0, title: 'Cascade Layers',                  file: 'css-professional/level-0.md' },
      { level: 1, title: 'Native HTML Elements',            file: 'css-professional/level-1.md' },
      { level: 2, title: 'CSS Owns the State',              file: 'css-professional/level-2.md' },
      { level: 3, title: 'CSS and JavaScript',              file: 'css-professional/level-3.md' },
      { level: 4, title: 'Scroll-Driven Animations',        file: 'css-professional/level-4.md' },
      { level: 5, title: '@property — Typed Custom Properties', file: 'css-professional/level-5.md' },
      { level: 6, title: 'Maintainable CSS at Scale',       file: 'css-professional/level-6.md' },
      { level: 7, title: 'Professional CSS Reference',      file: 'css-professional/level-7.md' },
    ],
  },
  {
    id: 'css-responsive',
    label: 'CSS Responsive Design',
    lang: 'css',
    emoji: 'CSS',
    description: 'Build layouts that work on any screen: viewport units, media queries, mobile-first strategy, fluid typography with clamp(), responsive images, auto-fit/minmax grids, and container queries.',
    levels: [
      { level: 0, title: 'The Viewport and CSS Pixels',            file: 'css-responsive/level-0.md' },
      { level: 1, title: 'Media Queries',                          file: 'css-responsive/level-1.md' },
      { level: 2, title: 'Mobile-First Design',                    file: 'css-responsive/level-2.md' },
      { level: 3, title: 'Responsive Typography',                  file: 'css-responsive/level-3.md' },
      { level: 4, title: 'Responsive Images and Media',            file: 'css-responsive/level-4.md' },
      { level: 5, title: 'Responsive Layouts Without Media Queries', file: 'css-responsive/level-5.md' },
      { level: 6, title: 'Container Queries',                      file: 'css-responsive/level-6.md' },
      { level: 7, title: 'A Complete Responsive Page',             file: 'css-responsive/level-7.md' },
    ],
  },
  {
    id: 'css-animation',
    label: 'CSS Animations',
    lang: 'css',
    emoji: 'CSS',
    description: 'Bring UIs to life: CSS transitions, transform, @keyframes animations, easing functions, UI micro-animations, staggered effects, and performance-safe animation with prefers-reduced-motion.',
    levels: [
      { level: 0, title: 'CSS Transitions',                file: 'css-animation/level-0.md' },
      { level: 1, title: 'CSS Transform',                  file: 'css-animation/level-1.md' },
      { level: 2, title: '@keyframes',                     file: 'css-animation/level-2.md' },
      { level: 3, title: 'Easing Functions',               file: 'css-animation/level-3.md' },
      { level: 4, title: 'UI Micro-animations',            file: 'css-animation/level-4.md' },
      { level: 5, title: 'Animation Patterns',             file: 'css-animation/level-5.md' },
      { level: 6, title: 'Performance and Accessibility',  file: 'css-animation/level-6.md' },
    ],
  },
  {
    id: 'typescript-fundamentals',
    label: 'TypeScript Fundamentals',
    lang: 'typescript',
    emoji: 'TS',
    description: 'Add types to JavaScript: type annotations and inference, interfaces and type aliases, union/intersection types, generics, utility types, narrowing, classes, and modules.',
    levels: [
      { level: 0, title: 'Types and Type Annotations',    file: 'typescript-fundamentals/level-0.md' },
      { level: 1, title: 'Interfaces and Type Aliases',   file: 'typescript-fundamentals/level-1.md' },
      { level: 2, title: 'Union and Intersection Types',  file: 'typescript-fundamentals/level-2.md' },
      { level: 3, title: 'Generics',                      file: 'typescript-fundamentals/level-3.md' },
      { level: 4, title: 'Utility Types',                 file: 'typescript-fundamentals/level-4.md' },
      { level: 5, title: 'Narrowing and Type Guards',     file: 'typescript-fundamentals/level-5.md' },
      { level: 6, title: 'Classes and Access Modifiers',  file: 'typescript-fundamentals/level-6.md' },
      { level: 7, title: 'Modules and Declaration Files', file: 'typescript-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'sql-fundamentals',
    label: 'SQL Fundamentals',
    lang: 'sql',
    emoji: 'SQL',
    description: 'Query and design relational databases: SELECT, WHERE, ORDER BY, aggregates, GROUP BY, JOINs, subqueries, CTEs, INSERT/UPDATE/DELETE, schema design, and indexes.',
    levels: [
      { level: 0, title: 'What SQL Is',                file: 'sql-fundamentals/level-0.md' },
      { level: 1, title: 'SELECT and FROM',            file: 'sql-fundamentals/level-1.md' },
      { level: 2, title: 'Sorting, Limiting, Distinct',file: 'sql-fundamentals/level-2.md' },
      { level: 3, title: 'Aggregates and GROUP BY',    file: 'sql-fundamentals/level-3.md' },
      { level: 4, title: 'JOINs',                     file: 'sql-fundamentals/level-4.md' },
      { level: 5, title: 'Subqueries and CTEs',        file: 'sql-fundamentals/level-5.md' },
      { level: 6, title: 'INSERT, UPDATE, DELETE',     file: 'sql-fundamentals/level-6.md' },
      { level: 7, title: 'Schema Design and Indexes',  file: 'sql-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'backend-fundamentals',
    label: 'Backend Fundamentals',
    lang: 'javascript',
    emoji: 'BE',
    description: 'Build production-quality APIs with Node.js and Express: HTTP, routing, middleware, async handlers, SQL injection prevention, JWTs, bcrypt, database integration, testing, and deployment.',
    levels: [
      { level: 0, title: 'What Backend Is',                    file: 'backend-fundamentals/level-0.md' },
      { level: 1, title: 'Express.js and Routing',             file: 'backend-fundamentals/level-1.md' },
      { level: 2, title: 'Async Handlers and Error Handling',  file: 'backend-fundamentals/level-2.md' },
      { level: 3, title: 'Authentication (JWT and bcrypt)',     file: 'backend-fundamentals/level-3.md' },
      { level: 4, title: 'Database Integration',               file: 'backend-fundamentals/level-4.md' },
      { level: 5, title: 'Environment Variables and Config',   file: 'backend-fundamentals/level-5.md' },
      { level: 6, title: 'Testing APIs',                       file: 'backend-fundamentals/level-6.md' },
      { level: 7, title: 'Deployment',                         file: 'backend-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'git-version-control',
    label: 'Git & Version Control',
    lang: 'bash',
    emoji: 'Git',
    description: 'Master version control from the ground up: the three states, core workflow, branches, merging, remotes, pull requests, rebase, stash, fixing mistakes, and professional Git workflows.',
    levels: [
      { level: 0, title: 'What Git Is',                    file: 'git-version-control/level-0.md' },
      { level: 1, title: 'The Core Workflow',              file: 'git-version-control/level-1.md' },
      { level: 2, title: 'Branches and Merging',           file: 'git-version-control/level-2.md' },
      { level: 3, title: 'Remote Repositories and GitHub', file: 'git-version-control/level-3.md' },
      { level: 4, title: 'Pull Requests and Code Review',  file: 'git-version-control/level-4.md' },
      { level: 5, title: 'Rebase, Stash, and Fixing Mistakes', file: 'git-version-control/level-5.md' },
      { level: 6, title: 'Git Workflows',                  file: 'git-version-control/level-6.md' },
    ],
  },
]

export function getSeries(id: string): SeriesMeta | undefined {
  return SERIES.find(s => s.id === id)
}
