export interface SeriesMeta {
  id: string
  label: string
  lang: string
  emoji: string
  description: string
  levels: { level: number; title: string; file: string }[]
}

export const SERIES: SeriesMeta[] = [
  {
    id: 'python-fundamentals',
    label: 'Python Fundamentals',
    lang: 'python',
    emoji: '🐍',
    description: 'Learn Python the way professionals think about it — not just the syntax, but how the interpreter works, how to read and debug code, and the CS and SE ideas underneath every line.',
    levels: [
      // Phase 0 — The Programmer's Mental Model
      { level: 0,  title: 'What Programming Is',          file: 'python-fundamentals/level-0.md'  },
      { level: 1,  title: 'How Python Reads Your Code',   file: 'python-fundamentals/level-1.md'  },
      { level: 2,  title: 'The Debugger',                 file: 'python-fundamentals/level-2.md'  },
      { level: 3,  title: 'Reading Error Messages',       file: 'python-fundamentals/level-3.md'  },
      // Phase 1 — Core Language
      { level: 4,  title: 'print()',                      file: 'python-fundamentals/level-4.md'  },
      { level: 5,  title: 'Variables',                    file: 'python-fundamentals/level-5.md'  },
      { level: 6,  title: 'Types',                        file: 'python-fundamentals/level-6.md'  },
      { level: 7,  title: 'Numbers & Arithmetic',         file: 'python-fundamentals/level-7.md'  },
      { level: 8,  title: 'Strings',                      file: 'python-fundamentals/level-8.md'  },
      { level: 9,  title: 'String Methods',               file: 'python-fundamentals/level-9.md'  },
      { level: 10, title: 'f-strings',                    file: 'python-fundamentals/level-10.md' },
      { level: 11, title: 'Comments',                     file: 'python-fundamentals/level-11.md' },
      { level: 12, title: 'Input & Type Conversion',       file: 'python-fundamentals/level-12.md' },
      { level: 13, title: 'Comparisons & Booleans',       file: 'python-fundamentals/level-13.md' },
      { level: 14, title: 'if / elif / else',             file: 'python-fundamentals/level-14.md' },
      { level: 15, title: 'while Loops',                  file: 'python-fundamentals/level-15.md' },
      { level: 16, title: 'for Loops',                    file: 'python-fundamentals/level-16.md' },
      { level: 17, title: 'range()',                      file: 'python-fundamentals/level-17.md' },
      { level: 18, title: 'Functions',                    file: 'python-fundamentals/level-18.md' },
      { level: 19, title: 'Scope',                        file: 'python-fundamentals/level-19.md' },
      { level: 20, title: 'Lists',                        file: 'python-fundamentals/level-20.md' },
      { level: 21, title: 'List Methods',                 file: 'python-fundamentals/level-21.md' },
      { level: 22, title: 'Tuples',                       file: 'python-fundamentals/level-22.md' },
      { level: 23, title: 'Dictionaries',                 file: 'python-fundamentals/level-23.md' },
      { level: 24, title: 'Sets',                         file: 'python-fundamentals/level-24.md' },
      { level: 25, title: 'Modules & Imports',            file: 'python-fundamentals/level-25.md' },
      { level: 26, title: 'Exceptions',                   file: 'python-fundamentals/level-26.md' },
      // Phase 2 — Writing Programs
      { level: 27, title: 'List Comprehensions',          file: 'python-fundamentals/level-27.md' },
      { level: 28, title: 'Files',                         file: 'python-fundamentals/level-28.md' },
      { level: 29, title: 'Testing',                      file: 'python-fundamentals/level-29.md' },
      { level: 30, title: 'Refactoring',                  file: 'python-fundamentals/level-30.md' },
      // Phase 3 — Professional Python
      { level: 31, title: 'Type Hints',                   file: 'python-fundamentals/level-31.md' },
      { level: 32, title: 'Virtual Environments & pip',   file: 'python-fundamentals/level-32.md' },
      { level: 33, title: 'Formatting & Linting',         file: 'python-fundamentals/level-33.md' },
      { level: 34, title: 'JSON',                         file: 'python-fundamentals/level-34.md' },
      { level: 35, title: 'CSV',                          file: 'python-fundamentals/level-35.md' },
      { level: 36, title: 'SQLite',                       file: 'python-fundamentals/level-36.md' },
    ],
  },
  {
    id: 'dsa-python',
    label: 'Data Structures & Algorithms in Python',
    lang: 'python',
    emoji: '🧮',
    description: 'Master the core DSA patterns used in every technical interview and production codebase — lists, two pointers, hash maps, stacks, queues, linked lists, binary search, recursion, sorting, trees, and graphs.',
    levels: [
      { level: 0,  title: 'Lists & Indexing',      file: 'dsa-python/level-0.md'  },
      { level: 1,  title: 'Two Pointers',           file: 'dsa-python/level-1.md'  },
      { level: 2,  title: 'Hash Maps & Sets',       file: 'dsa-python/level-2.md'  },
      { level: 3,  title: 'Stacks',                 file: 'dsa-python/level-3.md'  },
      { level: 4,  title: 'Queues & Deques',        file: 'dsa-python/level-4.md'  },
      { level: 5,  title: 'Linked Lists',           file: 'dsa-python/level-5.md'  },
      { level: 6,  title: 'Binary Search',          file: 'dsa-python/level-6.md'  },
      { level: 7,  title: 'Recursion',              file: 'dsa-python/level-7.md'  },
      { level: 8,  title: 'Sorting',                file: 'dsa-python/level-8.md'  },
      { level: 9,  title: 'Trees',                  file: 'dsa-python/level-9.md'  },
      { level: 10, title: 'Graphs',                 file: 'dsa-python/level-10.md' },
    ],
  },
  {
    id: 'cpp-fundamentals',
    label: 'C++ Fundamentals',
    lang: 'cpp',
    emoji: 'C++',
    description: 'Learn C++ with the lesson engine: syntax-highlighted examples, runnable C/C++ subset demos, and debug-oriented explanations of stack, heap, values, and references.',
    levels: [
      { level: 0, title: 'Types, Variables & main()',      file: 'cpp-fundamentals/level-0.md' },
      { level: 1, title: 'Control Flow',                  file: 'cpp-fundamentals/level-1.md' },
      { level: 2, title: 'Functions',                     file: 'cpp-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays & Pointers',             file: 'cpp-fundamentals/level-3.md' },
      { level: 4, title: 'References & Pass-by-Reference',file: 'cpp-fundamentals/level-4.md' },
      { level: 5, title: 'Structs',                       file: 'cpp-fundamentals/level-5.md' },
      { level: 6, title: 'Classes & Constructors',        file: 'cpp-fundamentals/level-6.md' },
      { level: 7, title: 'Strings & the Standard Library',file: 'cpp-fundamentals/level-7.md' },
    ],
  },
  {
    id: 'csharp-fundamentals',
    label: 'C# Fundamentals',
    lang: 'csharp',
    emoji: 'C#',
    description: 'Learn C# from types and methods through classes, interfaces, generics, and LINQ — with a focus on how the .NET runtime works.',
    levels: [
      { level: 0, title: 'Types, Variables & Methods', file: 'csharp-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Properties',       file: 'csharp-fundamentals/level-1.md' },
      { level: 2, title: 'Interfaces & Generics',      file: 'csharp-fundamentals/level-2.md' },
      { level: 3, title: 'LINQ & Collections',         file: 'csharp-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'java-fundamentals',
    label: 'Java Fundamentals',
    lang: 'java',
    emoji: 'Java',
    description: 'Learn Java from types and main() through classes, inheritance, interfaces, and the Collections/Streams framework.',
    levels: [
      { level: 0, title: 'Types, Variables & main()', file: 'java-fundamentals/level-0.md' },
      { level: 1, title: 'Classes & Methods',         file: 'java-fundamentals/level-1.md' },
      { level: 2, title: 'Inheritance & Interfaces',  file: 'java-fundamentals/level-2.md' },
      { level: 3, title: 'Collections & Streams',     file: 'java-fundamentals/level-3.md' },
    ],
  },
  {
    id: 'css-selectors',
    label: 'CSS Selectors',
    lang: 'css',
    emoji: 'CSS',
    description: 'Go beyond type, class, and ID selectors. Learn combinators, attribute selectors, structural and form pseudo-classes, :not() / :is() / :where() / :has(), pseudo-elements, and cascade layers.',
    levels: [
      { level: 0, title: 'Combinators',              file: 'css-selectors/level-0.md' },
      { level: 1, title: 'Attribute Selectors',       file: 'css-selectors/level-1.md' },
      { level: 2, title: 'Structural Pseudo-classes', file: 'css-selectors/level-2.md' },
      { level: 3, title: 'Form Pseudo-classes',       file: 'css-selectors/level-3.md' },
      { level: 4, title: ':not(), :is(), :where()',   file: 'css-selectors/level-4.md' },
      { level: 5, title: ':has() — The Parent Selector', file: 'css-selectors/level-5.md' },
      { level: 6, title: 'Pseudo-elements',           file: 'css-selectors/level-6.md' },
      { level: 7, title: 'Cascade Layers',            file: 'css-selectors/level-7.md' },
    ],
  },
  {
    id: 'css-box-model',
    label: 'CSS Box Model',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the box model from the ground up: content, padding, border, margin, box-sizing, overflow, display types, min/max/clamp sizing, and stacking contexts with z-index.',
    levels: [
      { level: 0, title: 'The Box Model',                   file: 'css-box-model/level-0.md' },
      { level: 1, title: 'box-sizing: border-box',          file: 'css-box-model/level-1.md' },
      { level: 2, title: 'Margin & Margin Collapsing',      file: 'css-box-model/level-2.md' },
      { level: 3, title: 'Border & Outline',                file: 'css-box-model/level-3.md' },
      { level: 4, title: 'Overflow',                        file: 'css-box-model/level-4.md' },
      { level: 5, title: 'Display — Block, Inline, Inline-Block', file: 'css-box-model/level-5.md' },
      { level: 6, title: 'Sizing — min, max, clamp',        file: 'css-box-model/level-6.md' },
      { level: 7, title: 'Stacking Contexts & z-index',     file: 'css-box-model/level-7.md' },
    ],
  },
  {
    id: 'css-layout',
    label: 'CSS Layout',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master the full layout cascade: normal flow, block formatting contexts, all five position values, floats, containing blocks, and stacking contexts. The foundation every other layout system builds on.',
    levels: [
      { level: 0, title: 'Normal Flow',                   file: 'css-layout/level-0.md' },
      { level: 1, title: 'Block Formatting Contexts',     file: 'css-layout/level-1.md' },
      { level: 2, title: 'position: relative',            file: 'css-layout/level-2.md' },
      { level: 3, title: 'position: absolute',            file: 'css-layout/level-3.md' },
      { level: 4, title: 'position: fixed and sticky',    file: 'css-layout/level-4.md' },
      { level: 5, title: 'Floats',                        file: 'css-layout/level-5.md' },
      { level: 6, title: 'The Containing Block',          file: 'css-layout/level-6.md' },
      { level: 7, title: 'Stacking Contexts and z-index', file: 'css-layout/level-7.md' },
    ],
  },
  {
    id: 'css-fundamentals',
    label: 'CSS Fundamentals',
    lang: 'css',
    emoji: 'CSS',
    description: 'Learn what CSS is, how rules work, the full colour system, units, typography, inheritance, the cascade, specificity, custom properties, and how to debug styles in the browser. No prerequisites.',
    levels: [
      { level: 0, title: 'What CSS Is',             file: 'css-fundamentals/level-0.md' },
      { level: 1, title: 'Selectors — Type, Class & ID', file: 'css-fundamentals/level-1.md' },
      { level: 2, title: 'Colors',                  file: 'css-fundamentals/level-2.md' },
      { level: 3, title: 'Units',                   file: 'css-fundamentals/level-3.md' },
      { level: 4, title: 'Text & Fonts',            file: 'css-fundamentals/level-4.md' },
      { level: 5, title: 'Inheritance',             file: 'css-fundamentals/level-5.md' },
      { level: 6, title: 'The Cascade',             file: 'css-fundamentals/level-6.md' },
      { level: 7, title: 'Specificity Deep Dive',   file: 'css-fundamentals/level-7.md' },
      { level: 8, title: 'Custom Properties',       file: 'css-fundamentals/level-8.md' },
      { level: 9, title: 'Reading & Debugging CSS', file: 'css-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'css-flexbox',
    label: 'CSS Flexbox',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master one-dimensional layout: flex containers, main and cross axis alignment, flex-grow/shrink/basis, wrapping, gaps, and real-world patterns like navbars, sidebars, and card grids.',
    levels: [
      { level: 0, title: 'The Flex Container',                    file: 'css-flexbox/level-0.md' },
      { level: 1, title: 'justify-content',                       file: 'css-flexbox/level-1.md' },
      { level: 2, title: 'align-items and align-self',            file: 'css-flexbox/level-2.md' },
      { level: 3, title: 'flex-wrap',                             file: 'css-flexbox/level-3.md' },
      { level: 4, title: 'flex-grow, flex-shrink, flex-basis',    file: 'css-flexbox/level-4.md' },
      { level: 5, title: 'gap and order',                         file: 'css-flexbox/level-5.md' },
      { level: 6, title: 'Nested Flex Containers',                file: 'css-flexbox/level-6.md' },
      { level: 7, title: 'Real-World Flex Patterns',              file: 'css-flexbox/level-7.md' },
      { level: 8, title: 'Flexbox vs Grid',                       file: 'css-flexbox/level-8.md' },
    ],
  },
  {
    id: 'css-grid',
    label: 'CSS Grid',
    lang: 'css',
    emoji: 'CSS',
    description: 'Master two-dimensional layout: grid containers and items, repeat/fr/minmax, explicit placement, named areas, alignment, auto-flow, and real-world patterns like dashboards and magazine layouts.',
    levels: [
      { level: 0, title: 'The Grid Container',              file: 'css-grid/level-0.md' },
      { level: 1, title: 'repeat(), fr, and minmax()',       file: 'css-grid/level-1.md' },
      { level: 2, title: 'Grid Placement',                  file: 'css-grid/level-2.md' },
      { level: 3, title: 'grid-template-areas',             file: 'css-grid/level-3.md' },
      { level: 4, title: 'Grid Alignment',                  file: 'css-grid/level-4.md' },
      { level: 5, title: 'Auto-flow and Implicit Grids',    file: 'css-grid/level-5.md' },
      { level: 6, title: 'Real-World Grid Patterns',        file: 'css-grid/level-6.md' },
      { level: 7, title: 'Grid and Flexbox Together',       file: 'css-grid/level-7.md' },
    ],
  },
  {
    id: 'javascript-fundamentals',
    label: 'JavaScript Fundamentals',
    lang: 'javascript',
    emoji: 'JS',
    description: 'Learn JavaScript the way the runtime works — values, functions, scope, closures, objects, classes, async/await, and modules. No browser required; pure JS from first principles.',
    levels: [
      { level: 0, title: 'Values & Variables',      file: 'javascript-fundamentals/level-0.md' },
      { level: 1, title: 'Functions',               file: 'javascript-fundamentals/level-1.md' },
      { level: 2, title: 'Scope & the Call Stack',  file: 'javascript-fundamentals/level-2.md' },
      { level: 3, title: 'Arrays',                  file: 'javascript-fundamentals/level-3.md' },
      { level: 4, title: 'Objects',                 file: 'javascript-fundamentals/level-4.md' },
      { level: 5, title: 'Loops & Iteration',       file: 'javascript-fundamentals/level-5.md' },
      { level: 6, title: 'Closures',                file: 'javascript-fundamentals/level-6.md' },
      { level: 7, title: 'Classes',                 file: 'javascript-fundamentals/level-7.md' },
      { level: 8, title: 'Promises & async/await',  file: 'javascript-fundamentals/level-8.md' },
      { level: 9, title: 'Modules',                 file: 'javascript-fundamentals/level-9.md' },
    ],
  },
  {
    id: 'html-dom',
    label: 'HTML, DOM, and JavaScript',
    lang: 'html',
    emoji: 'DOM',
    description: 'Build browser-side skills from the ground up: query the DOM, respond to events, manage forms, and apply the state-driven render pattern that powers every modern framework.',
    levels: [
      { level: 0,  title: 'The Browser Environment',         file: 'html-dom/level-0.md'  },
      { level: 1,  title: 'querySelector & the DOM Tree',    file: 'html-dom/level-1.md'  },
      { level: 2,  title: 'Reading & Writing DOM Properties',file: 'html-dom/level-2.md'  },
      { level: 3,  title: 'classList',                       file: 'html-dom/level-3.md'  },
      { level: 4,  title: 'Creating & Inserting Elements',   file: 'html-dom/level-4.md'  },
      { level: 5,  title: 'Removing & Replacing Elements',   file: 'html-dom/level-5.md'  },
      { level: 6,  title: 'Events & addEventListener',       file: 'html-dom/level-6.md'  },
      { level: 7,  title: 'The Event Object & Bubbling',     file: 'html-dom/level-7.md'  },
      { level: 8,  title: 'Forms & Input Elements',          file: 'html-dom/level-8.md'  },
      { level: 9,  title: 'Data Attributes',                 file: 'html-dom/level-9.md'  },
      { level: 10, title: 'Rendering Lists from Data',       file: 'html-dom/level-10.md' },
      { level: 11, title: 'State & Re-rendering',            file: 'html-dom/level-11.md' },
    ],
  },
]

export function getSeries(id: string): SeriesMeta | undefined {
  return SERIES.find(s => s.id === id)
}
