// KinematicsPatternSpotter.jsx — Ch2 Pillar 3 (shared across SUVAT lessons)
import { useState } from "react";
const ROUNDS = [
  { q: "v₀=0, a=5 m/s², t=4s. Which equation finds v?", opts: ["v²=v₀²+2aΔx","v=v₀+at","Δx=v₀t+½at²","Δx=½(v₀+v)t"], correct: "v=v₀+at", why: "Eq 1: missing Δx, which is not needed. Direct: v = 0 + 5(4) = 20 m/s." },
  { q: "v₀=30, v=0, a=−6 m/s². Find Δx — which equation?", opts: ["Δx=v₀t+½at²","v=v₀+at","v²=v₀²+2aΔx","Δx=½(v₀+v)t"], correct: "v²=v₀²+2aΔx", why: "Eq 5: time is unknown and not needed. 0 = 900 + 2(−6)Δx → Δx = 75 m." },
  { q: "A car accelerates from 10 to 30 m/s over 100 m. Find a.", opts: ["Use Eq 1","Use Eq 3","Use Eq 5","Use Eq 2"], correct: "Use Eq 5", why: "v₀, v, Δx known. t unknown and not needed. v²=v₀²+2aΔx → 900=100+200a → a=4 m/s²." },
  { q: "An object falls from rest. After 3 s, how far has it fallen? (g=9.8)", opts: ["Δx=½(9.8)(9)=44.1m","Δx=9.8×3=29.4m","Δx=½(9.8)(3)=14.7m","Δx=9.8×9=88.2m"], correct: "Δx=½(9.8)(9)=44.1m", why: "Eq 3 with v₀=0: Δx = 0 + ½(9.8)(3²) = 44.1 m." },
  { q: "Ball thrown up at 20 m/s. When does it return to start?", opts: ["t=20/9.8≈2.04s","t=40/9.8≈4.08s","t=10/9.8≈1.02s","t=20×9.8"], correct: "t=40/9.8≈4.08s", why: "Δx=0 (returns to start), v₀=20, a=−9.8. 0=20t−4.9t². t(20−4.9t)=0 → t=0 or t=40/9.8≈4.08s." },
  { q: "v₀=0, Δx=45m, a=10 m/s². Which equation finds t?", opts: ["Eq 5","Eq 1","Eq 3","Eq 2"], correct: "Eq 3", why: "Eq 3: 45 = 0 + ½(10)t² → t² = 9 → t = 3s. Eq 5 would give v; Eq 1 needs v." },
  { q: "Does a negative acceleration always mean slowing down?", opts: ["Yes","No — depends on direction of v","Only in free fall","Only if v₀>0"], correct: "No — depends on direction of v", why: "Negative a with negative v means speeding up (in the −x direction). Slowing down requires a and v to have opposite signs." },
];
export default function KinematicsPatternSpotter({ params = {} }) {
  const [r, setR] = useState(0); const [chosen, setChosen] = useState(null); const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0); const [done, setDone] = useState(false); const [history, setHistory] = useState([]);
  const q = ROUNDS[r]; const C = "#10b981";
  function choose(opt) { if (revealed) return; setChosen(opt); setRevealed(true); const ok = opt === q.correct; if (ok) setScore(s => s + 1); setHistory(h => [...h, { q: q.q, correct: ok, answer: q.correct }]); }
  function next() { if (r + 1 >= ROUNDS.length) setDone(true); else { setR(n => n + 1); setChosen(null); setRevealed(false); } }
  function reset() { setR(0); setChosen(null); setRevealed(false); setScore(0); setDone(false); setHistory([]); }
  if (done) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>PILLAR 3 · EQUATION SELECTION</div><div style={{ fontSize: 32, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{score}/{ROUNDS.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{history.map((h, i) => <div key={i} style={{ background: h.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "8px 14px", borderLeft: `2px solid ${h.correct ? C : "#f43f5e"}` }}><div style={{ fontSize: 12, color: "#64748b" }}>{h.q.substring(0, 55)}</div><div style={{ fontSize: 12, fontWeight: 700, color: h.correct ? "#34d399" : "#f87171" }}>{h.answer}</div></div>)}</div><button onClick={reset} style={{ width: "100%", background: C, color: "#0f172a", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Try Again</button></div>);
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}>
    <div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 3 · SUVAT PATTERNS</span><div style={{ display: "flex", gap: 5 }}>{ROUNDS.map((_, i) => <div key={i} style={{ width: 7, height: 7, borderRadius: "50%", background: i < r ? "#6366f1" : i === r ? C : "#1e293b" }} />)}</div></div>
    <div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(r / ROUNDS.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div>
    <div style={{ padding: "18px 20px 0" }}>
      <div style={{ background: "#1e293b", borderRadius: 12, padding: "18px", marginBottom: 14, border: revealed ? `2px solid ${chosen === q.correct ? C : "#f43f5e"}` : "2px solid #334155" }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>Round {r + 1}/{ROUNDS.length}</div><div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>
        {q.opts.map(opt => { const isC = opt === q.correct, isCh = opt === chosen; let bg = "#1e293b", border = "#334155", tc = "#94a3b8"; if (revealed) { if (isC) { bg = "#0d2a1e"; border = C; tc = "#34d399"; } else if (isCh) { bg = "#2a0d0d"; border = "#f43f5e"; tc = "#f87171"; } } return <button key={opt} onClick={() => choose(opt)} style={{ background: bg, border: `2px solid ${border}`, borderRadius: 10, padding: "11px", fontSize: 12, fontWeight: 700, color: tc, cursor: revealed ? "default" : "pointer" }}>{opt}</button>; })}
      </div>
      {revealed && <><div style={{ background: chosen === q.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 10, padding: "12px 16px", borderLeft: `3px solid ${chosen === q.correct ? C : "#f43f5e"}`, marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 700, color: chosen === q.correct ? "#34d399" : "#f87171", marginBottom: 4 }}>{chosen === q.correct ? "✓ Correct" : "✗ " + q.correct}</div><div style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.6 }}>{q.why}</div></div><button onClick={next} style={{ width: "100%", background: C, color: "#0f172a", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer", marginBottom: 20 }}>{r + 1 >= ROUNDS.length ? "Results →" : "Next →"}</button></>}
    </div>
  </div>);
}
