// KinematicsFormRecogniser.jsx — Ch2 Pillar 5 (shared across most lessons)
import { useState } from "react";
const FORMS = [
  { label: "Displacement", formula: "Δx = x_f − x_i  (signed, vector in 1D)", note: "Positive = moved in +x direction. Negative = moved in −x direction.", color: "#6366f1" },
  { label: "Average velocity", formula: "v̄ = Δx/Δt = (x_f−x_i)/(t_f−t_i)", note: "Slope of the secant on the x–t graph. Signed quantity.", color: "#6366f1" },
  { label: "Average acceleration", formula: "ā = Δv/Δt = (v_f−v_i)/(t_f−t_i)", note: "Slope of the secant on the v–t graph. Negative acceleration ≠ slowing down.", color: "#f59e0b" },
  { label: "Instantaneous velocity", formula: "v(t) = dx/dt = lim(Δt→0) Δx/Δt", note: "Slope of the tangent on the x–t graph at time t.", color: "#6366f1" },
  { label: "Instantaneous acceleration", formula: "a(t) = dv/dt = d²x/dt²", note: "Slope of the tangent on the v–t graph, or curvature of the x–t graph.", color: "#f59e0b" },
  { label: "Kinematic eq 1", formula: "v = v₀ + at", note: "Missing Δx. Use when time is known or needed.", color: "#10b981" },
  { label: "Kinematic eq 2", formula: "Δx = ½(v₀+v)t", note: "Missing a. Use when acceleration is unknown.", color: "#10b981" },
  { label: "Kinematic eq 3", formula: "Δx = v₀t + ½at²", note: "Missing v. The most commonly used equation.", color: "#10b981" },
  { label: "Kinematic eq 4", formula: "Δx = vt − ½at²", note: "Missing v₀. Use when initial velocity is unknown.", color: "#10b981" },
  { label: "Kinematic eq 5", formula: "v² = v₀² + 2aΔx", note: "Missing t. The go-to when time is irrelevant.", color: "#10b981" },
  { label: "Free fall (up positive)", formula: "a = −g = −9.8 m/s²", note: "Apply kinematic equations with a = −g. At max height: v = 0.", color: "#818cf8" },
  { label: "Integration (variable a)", formula: "v(t) = v₀ + ∫a dt,   x(t) = x₀ + ∫v dt", note: "Use when acceleration is not constant. SUVAT does not apply.", color: "#f43f5e" },
];
const RECALL = [
  { q: "What is the difference between displacement and distance?", a: "Displacement = Δx = x_f − x_i (signed, net change). Distance = total path length (always ≥ |displacement|)." },
  { q: "Which kinematic equation is missing time t?", a: "v² = v₀² + 2aΔx  (equation 5)" },
  { q: "What does the slope of the v–t graph give you?", a: "Acceleration — a = dv/dt = slope of v–t graph." },
  { q: "What does the area under the v–t graph give you?", a: "Displacement — Δx = ∫v dt = area under v–t curve." },
  { q: "A ball is at maximum height. What is its velocity?", a: "v = 0  (instantaneous rest — before direction reverses)." },
  { q: "When do the kinematic equations NOT apply?", a: "When acceleration is NOT constant. Use calculus (integration) instead." },
  { q: "What is the acceleration of a freely falling object near Earth?", a: "a = −g ≈ −9.8 m/s² (taking up as positive)." },
];
export default function KinematicsFormRecogniser({ params = {} }) {
  const [mode, setMode] = useState("table"); const [expanded, setExpanded] = useState(null);
  const [ri, setRi] = useState(0); const [shown, setShown] = useState(false); const [rs, setRs] = useState(0); const [rdone, setRdone] = useState(false); const [rh, setRh] = useState([]);
  function nextR(knew) { setRh(h => [...h, { ...RECALL[ri], knew }]); if (knew) setRs(s => s + 1); if (ri + 1 >= RECALL.length) setRdone(true); else { setRi(n => n + 1); setShown(false); } }
  const C = "#10b981";
  if (mode === "recall" && rdone) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>PILLAR 5 RECALL</div><div style={{ fontSize: 28, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{rs}/{RECALL.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{rh.map((h, i) => <div key={i} style={{ background: h.knew ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "10px 14px", borderLeft: `2px solid ${h.knew ? C : "#f43f5e"}` }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 2 }}>{h.q}</div><div style={{ fontSize: 13, fontFamily: "'Fira Code',monospace", color: "#e2e8f0" }}>{h.a}</div></div>)}</div><button onClick={() => { setMode("table"); setRi(0); setShown(false); setRs(0); setRdone(false); setRh([]); }} style={{ width: "100%", background: C, color: "#0f172a", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Back</button></div>);
  if (mode === "recall") { const q = RECALL[ri]; return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}><div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between" }}><span style={{ fontSize: 13, color: C, fontWeight: 700 }}>PILLAR 5 RECALL</span><span style={{ fontSize: 12, color: "#475569" }}>{ri + 1}/{RECALL.length}</span></div><div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(ri / RECALL.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div><div style={{ padding: 24 }}><div style={{ background: "#1e293b", borderRadius: 12, padding: "22px", textAlign: "center", marginBottom: 20 }}><div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>{!shown ? <button onClick={() => setShown(true)} style={{ width: "100%", background: "#1e293b", color: "#94a3b8", border: "2px solid #334155", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 700, cursor: "pointer" }}>Show Answer</button> : <><div style={{ background: "#0c1a2e", borderLeft: `3px solid ${C}`, borderRadius: 10, padding: "14px 18px", marginBottom: 12, fontFamily: "'Fira Code',monospace", fontSize: 13, color: "#6ee7b7" }}>{q.a}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><button onClick={() => nextR(false)} style={{ background: "#2a0d0d", color: "#f87171", border: "2px solid #f43f5e", borderRadius: 10, padding: 12, fontSize: 13, fontWeight: 700, cursor: "pointer" }}>✗ Didn't know</button><button onClick={() => nextR(true)} style={{ background: "#0d2a1e", color: "#34d399", border: `2px solid ${C}`, borderRadius: 10, padding: 12, fontSize: 13, fontWeight: 700, cursor: "pointer" }}>✓ Knew it</button></div></>}</div></div>); }
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}><div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 5 · KINEMATICS REFERENCE</span><button onClick={() => setMode("recall")} style={{ background: "#1e293b", color: "#6ee7b7", border: `1px solid ${C}`, borderRadius: 8, padding: "5px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer" }}>Recall →</button></div>
  <div style={{ padding: "16px 20px 20px", display: "flex", flexDirection: "column", gap: 7 }}>{FORMS.map((f, i) => (<div key={i} onClick={() => setExpanded(expanded === i ? null : i)} style={{ background: expanded === i ? "#0c1a2e" : "#1e293b", borderRadius: 10, padding: "10px 14px", border: `1px solid ${expanded === i ? f.color : "#334155"}`, cursor: "pointer", transition: "all 0.2s" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 12, fontWeight: 700, color: f.color }}>{f.label}</div><div style={{ fontSize: 11, fontFamily: "'Fira Code',monospace", color: "#64748b", marginTop: 1 }}>{f.formula}</div></div><span style={{ color: "#475569", fontSize: 12 }}>{expanded === i ? "▲" : "▼"}</span></div>{expanded === i && <div style={{ marginTop: 8, paddingTop: 8, borderTop: "1px solid #334155", fontSize: 12, color: "#94a3b8", lineHeight: 1.6 }}>{f.note}</div>}</div>))}</div></div>);
}
