// ProjectilePatternSpotter.jsx — Ch3 Pillar 3 (shared across projectile lessons)
import { useState } from "react";
const G = 9.8;
const ROUNDS = [
  { q: "A ball is launched horizontally at 20 m/s from 80 m high. How long does it take to land?", opts: ["4.04 s", "8.16 s", "2.02 s", "1.43 s"], correct: "4.04 s", why: "t = √(2h/g) = √(160/9.8) ≈ 4.04 s. Horizontal speed has no effect on fall time." },
  { q: "At what angle is range R = v₀²sin(2θ)/g maximised?", opts: ["30°", "45°", "60°", "90°"], correct: "45°", why: "sin(2θ) is maximum when 2θ = 90°, i.e. θ = 45°. This is the range-maximising angle on flat ground." },
  { q: "A projectile launched at 60° has the same range as one launched at what other angle?", opts: ["40°", "45°", "30°", "75°"], correct: "30°", why: "sin(2×60°) = sin(120°) = sin(60°) = sin(2×30°). Complementary angles θ and (90°−θ) always give the same range." },
  { q: "At maximum height, what is true about the projectile?", opts: ["v = 0", "vy = 0 only", "vx = 0 only", "acceleration = 0"], correct: "vy = 0 only", why: "At peak: vy = 0 (momentarily no vertical motion). vx is unchanged. Acceleration is still −g. Only vy is zero." },
  { q: "A ball is thrown at 30 m/s at 53°. What is vy₀? (sin53°≈0.8, cos53°≈0.6)", opts: ["18 m/s", "24 m/s", "30 m/s", "15 m/s"], correct: "24 m/s", why: "vy₀ = v₀sinθ = 30 × 0.8 = 24 m/s." },
  { q: "Which factor does NOT affect the time of flight for a projectile launched from flat ground?", opts: ["v₀y (vertical component)", "g (gravity)", "v₀x (horizontal component)", "Launch angle θ"], correct: "v₀x (horizontal component)", why: "Time depends only on vertical motion: t = 2vy₀/g. The horizontal component plays no role in determining time of flight." },
  { q: "A plane drops a bomb horizontally while flying level. Ignoring air resistance, where is the plane when the bomb hits the ground?", opts: ["Behind the bomb", "Directly above the bomb", "Ahead of the bomb", "Depends on altitude"], correct: "Directly above the bomb", why: "The bomb inherits the plane's horizontal velocity and keeps it. Both travel at the same vx. The plane stays directly above." },
];

export default function ProjectilePatternSpotter({ params = {} }) {
  const [r, setR] = useState(0); const [chosen, setChosen] = useState(null); const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0); const [done, setDone] = useState(false); const [history, setHistory] = useState([]);
  const q = ROUNDS[r]; const C = "#6366f1";
  function choose(opt) { if (revealed) return; setChosen(opt); setRevealed(true); const ok = opt === q.correct; if (ok) setScore(s => s + 1); setHistory(h => [...h, { q: q.q, correct: ok, answer: q.correct }]); }
  function next() { if (r + 1 >= ROUNDS.length) setDone(true); else { setR(n => n + 1); setChosen(null); setRevealed(false); } }
  function reset() { setR(0); setChosen(null); setRevealed(false); setScore(0); setDone(false); setHistory([]); }
  if (done) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>PROJECTILE PATTERNS</div><div style={{ fontSize: 32, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{score}/{ROUNDS.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{history.map((h, i) => <div key={i} style={{ background: h.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "8px 14px", borderLeft: `2px solid ${h.correct ? "#10b981" : "#f43f5e"}` }}><div style={{ fontSize: 12, color: "#64748b" }}>{h.q.substring(0, 55)}</div><div style={{ fontSize: 12, fontWeight: 700, color: h.correct ? "#34d399" : "#f87171" }}>{h.answer}</div></div>)}</div><button onClick={reset} style={{ width: "100%", background: C, color: "#fff", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Try Again</button></div>);
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}>
    <div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 3 · PROJECTILE PATTERNS</span><div style={{ display: "flex", gap: 5 }}>{ROUNDS.map((_, i) => <div key={i} style={{ width: 7, height: 7, borderRadius: "50%", background: i < r ? "#10b981" : i === r ? C : "#1e293b" }} />)}</div></div>
    <div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(r / ROUNDS.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div>
    <div style={{ padding: "18px 20px 0" }}>
      <div style={{ background: "#1e293b", borderRadius: 12, padding: "18px", marginBottom: 14, border: revealed ? `2px solid ${chosen === q.correct ? "#10b981" : "#f43f5e"}` : "2px solid #334155" }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>Round {r + 1}/{ROUNDS.length}</div><div style={{ fontSize: 14, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>{q.opts.map(opt => { const isC = opt === q.correct, isCh = opt === chosen; let bg = "#1e293b", border = "#334155", tc = "#94a3b8"; if (revealed) { if (isC) { bg = "#0d2a1e"; border = "#10b981"; tc = "#34d399"; } else if (isCh) { bg = "#2a0d0d"; border = "#f43f5e"; tc = "#f87171"; } } return <button key={opt} onClick={() => choose(opt)} style={{ background: bg, border: `2px solid ${border}`, borderRadius: 10, padding: "11px", fontSize: 12, fontWeight: 700, color: tc, cursor: revealed ? "default" : "pointer" }}>{opt}</button>; })}</div>
      {revealed && <><div style={{ background: chosen === q.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 10, padding: "12px 16px", borderLeft: `3px solid ${chosen === q.correct ? "#10b981" : "#f43f5e"}`, marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 700, color: chosen === q.correct ? "#34d399" : "#f87171", marginBottom: 4 }}>{chosen === q.correct ? "✓ Correct" : "✗ " + q.correct}</div><div style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.6 }}>{q.why}</div></div><button onClick={next} style={{ width: "100%", background: C, color: "#fff", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer", marginBottom: 20 }}>{r + 1 >= ROUNDS.length ? "Results →" : "Next →"}</button></>}
    </div>
  </div>);
}
