// ProjectileFormRecogniser.jsx — Ch3 Pillar 5 (shared across all projectile lessons)
import { useState } from "react";
const FORMS = [
  { label: "Independence principle", formula: "ax = 0,  ay = −g  →  solve x and y separately", note: "The foundation of all 2D projectile work. Time is the only coupling variable.", color: "#6366f1" },
  { label: "Decompose v₀", formula: "v₀x = v₀cosθ,   v₀y = v₀sinθ", note: "Always the first step. For horizontal launch, θ=0 → v₀y=0.", color: "#f59e0b" },
  { label: "Horizontal motion", formula: "x = v₀x·t   (vx constant, ax=0)", note: "Constant velocity. No equations needed beyond x = vt.", color: "#f59e0b" },
  { label: "Vertical motion", formula: "vy = v₀y−gt,  y = v₀y·t−½gt²,  vy²=v₀y²−2gy", note: "Standard SUVAT with a=−g. Identical to free-fall equations from Ch2.", color: "#10b981" },
  { label: "Trajectory (parabola)", formula: "y = x·tanθ − gx²/(2v₀²cos²θ)", note: "Eliminate t. Parabola in x,y space. Useful for wall/slope problems.", color: "#818cf8" },
  { label: "Range formula", formula: "R = v₀²·sin(2θ)/g   (level ground)", note: "Maximum at θ=45°. Symmetric: R(θ)=R(90°−θ). Only valid when landing height = launch height.", color: "#10b981" },
  { label: "Maximum height", formula: "H = v₀y²/(2g) = v₀²sin²θ/(2g)", note: "Set vy=0 at the peak. Depends only on the vertical component.", color: "#818cf8" },
  { label: "Time of flight (level)", formula: "t = 2v₀y/g = 2v₀sinθ/g", note: "From symmetry or solving y=0. Total flight time = 2 × time to peak.", color: "#64748b" },
  { label: "Final speed", formula: "|v_f| = √(vx²+vy_f²),   vy_f = v₀y − g·t", note: "Recombine components at any time. At same height as launch: |vf| = |v₀| (energy conservation).", color: "#f43f5e" },
  { label: "Elevated launch / cliff", formula: "Set y_f = −h  in  y = v₀y·t−½gt²  and solve quadratic for t", note: "Two solutions — take the positive (physical) one. Then R = vx·t.", color: "#f43f5e" },
];
const RECALL = [
  { q: "What are the two conditions that make projectile motion separable?", a: "ax=0 (no horizontal force) and ay=−g (only gravity acts vertically)" },
  { q: "Ball launched at 20 m/s at 30°. Find vx and vy₀.", a: "vx = 20cos30° ≈ 17.32 m/s,  vy₀ = 20sin30° = 10 m/s" },
  { q: "Range formula for level ground?", a: "R = v₀²sin(2θ)/g. Maximum at θ=45°." },
  { q: "How do you find time of flight for an elevated launch?", a: "Set y = −h (landing below start), solve quadratic: v₀y·t − ½g·t² = −h" },
  { q: "At the peak of a trajectory, what is true about the velocity?", a: "vy = 0 only. vx is unchanged. Speed = |vx| = v₀cosθ." },
  { q: "What is the trajectory equation (x,y form)?", a: "y = x·tanθ − gx²/(2v₀²cos²θ) — a downward parabola" },
];
export default function ProjectileFormRecogniser({ params = {} }) {
  const [mode, setMode] = useState("table"); const [expanded, setExpanded] = useState(null);
  const [ri, setRi] = useState(0); const [shown, setShown] = useState(false); const [rs, setRs] = useState(0); const [rdone, setRdone] = useState(false); const [rh, setRh] = useState([]);
  function nextR(knew) { setRh(h => [...h, { ...RECALL[ri], knew }]); if (knew) setRs(s => s + 1); if (ri + 1 >= RECALL.length) setRdone(true); else { setRi(n => n + 1); setShown(false); } }
  const C = "#6366f1";
  if (mode === "recall" && rdone) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>RECALL RESULTS</div><div style={{ fontSize: 28, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{rs}/{RECALL.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{rh.map((h, i) => <div key={i} style={{ background: h.knew ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "10px 14px", borderLeft: `2px solid ${h.knew ? "#10b981" : "#f43f5e"}` }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 2 }}>{h.q}</div><div style={{ fontSize: 13, fontFamily: "'Fira Code',monospace", color: "#e2e8f0" }}>{h.a}</div></div>)}</div><button onClick={() => { setMode("table"); setRi(0); setShown(false); setRs(0); setRdone(false); setRh([]); }} style={{ width: "100%", background: C, color: "#fff", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Back</button></div>);
  if (mode === "recall") { const q = RECALL[ri]; return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}><div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between" }}><span style={{ fontSize: 13, color: C, fontWeight: 700 }}>RECALL</span><span style={{ fontSize: 12, color: "#475569" }}>{ri + 1}/{RECALL.length}</span></div><div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(ri / RECALL.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div><div style={{ padding: 24 }}><div style={{ background: "#1e293b", borderRadius: 12, padding: "22px", textAlign: "center", marginBottom: 20 }}><div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>{!shown ? <button onClick={() => setShown(true)} style={{ width: "100%", background: "#1e293b", color: "#94a3b8", border: "2px solid #334155", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 700, cursor: "pointer" }}>Show Answer</button> : <><div style={{ background: "#0c1a2e", borderLeft: `3px solid ${C}`, borderRadius: 10, padding: "14px 18px", marginBottom: 12, fontFamily: "'Fira Code',monospace", fontSize: 13, color: "#a5b4fc" }}>{q.a}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><button onClick={() => nextR(false)} style={{ background: "#2a0d0d", color: "#f87171", border: "2px solid #f43f5e", borderRadius: 10, padding: 12, fontSize: 13, fontWeight: 700, cursor: "pointer" }}>✗ Didn't know</button><button onClick={() => nextR(true)} style={{ background: "#0d2a1e", color: "#34d399", border: "2px solid #10b981", borderRadius: 10, padding: 12, fontSize: 13, fontWeight: 700, cursor: "pointer" }}>✓ Knew it</button></div></>}</div></div>); }
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}><div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 5 · PROJECTILE REFERENCE</span><button onClick={() => setMode("recall")} style={{ background: "#1e293b", color: "#a5b4fc", border: `1px solid ${C}`, borderRadius: 8, padding: "5px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer" }}>Recall →</button></div>
  <div style={{ padding: "16px 20px 20px", display: "flex", flexDirection: "column", gap: 7 }}>{FORMS.map((f, i) => (<div key={i} onClick={() => setExpanded(expanded === i ? null : i)} style={{ background: expanded === i ? "#0c1a2e" : "#1e293b", borderRadius: 10, padding: "10px 14px", border: `1px solid ${expanded === i ? f.color : "#334155"}`, cursor: "pointer", transition: "all 0.2s" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><div style={{ fontSize: 12, fontWeight: 700, color: f.color }}>{f.label}</div><div style={{ fontSize: 11, fontFamily: "'Fira Code',monospace", color: "#64748b", marginTop: 1 }}>{f.formula}</div></div><span style={{ color: "#475569", fontSize: 12 }}>{expanded === i ? "▲" : "▼"}</span></div>{expanded === i && <div style={{ marginTop: 8, paddingTop: 8, borderTop: "1px solid #334155", fontSize: 12, color: "#94a3b8", lineHeight: 1.6 }}>{f.note}</div>}</div>))}</div></div>);
}
