// TwoObjectsPatternSpotter.jsx
import { useState } from "react";
const ROUNDS = [
  { q: "Car A is at x=0 with v=20 m/s. Car B is at x=60 m with v=15 m/s. When does A catch B?", opts: ["t = 6 s", "t = 12 s", "t = 4 s", "t = 8 s"], correct: "t = 12 s", why: "x_A = x_B → 20t = 60 + 15t → 5t = 60 → t = 12 s." },
  { q: "What is the standard method for two-object problems?", opts: ["Subtract velocities","Write x(t) for each, set equal","Subtract positions","Use relative velocity only"], correct: "Write x(t) for each, set equal", why: "Write x₁(t) and x₂(t) with their own initial conditions. Set x₁ = x₂ and solve for t. This always works." },
  { q: "Two balls head toward each other: Ball A at x=0, v=+10 m/s; Ball B at x=100, v=−8 m/s. Where do they meet?", opts: ["x = 44.4 m", "x = 55.6 m", "x = 50 m", "x = 80 m"], correct: "x = 55.6 m", why: "10t = 100−8t → 18t = 100 → t ≈ 5.56 s. x = 10(5.56) ≈ 55.6 m." },
  { q: "Ball dropped from 50 m at t=0. Ball thrown up from ground at v₀=20 m/s at same time. When do they meet?", opts: ["t = 2.5 s", "t = 5 s", "t = 1.25 s", "t = 4.0 s"], correct: "t = 2.5 s", why: "50−½(9.8)t² = 20t−½(9.8)t² → 50 = 20t → t = 2.5 s. The ½gt² terms cancel!" },
  { q: "If two objects moving in the same direction have the same acceleration, can the trailing one ever catch up?", opts: ["Never","Only if it has greater v₀","Only if they start at the same x","Always"], correct: "Only if it has greater v₀", why: "With same a, relative velocity is constant (v_rel = v₀A − v₀B). If trailing object is faster (v₀A > v₀B), it closes the gap at a constant rate." },
];
export default function TwoObjectsPatternSpotter({ params = {} }) {
  const [r, setR] = useState(0); const [chosen, setChosen] = useState(null); const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0); const [done, setDone] = useState(false); const [history, setHistory] = useState([]);
  const q = ROUNDS[r]; const C = "#0ea5e9";
  function choose(opt) { if (revealed) return; setChosen(opt); setRevealed(true); const ok = opt === q.correct; if (ok) setScore(s => s + 1); setHistory(h => [...h, { q: q.q, correct: ok, answer: q.correct }]); }
  function next() { if (r + 1 >= ROUNDS.length) setDone(true); else { setR(n => n + 1); setChosen(null); setRevealed(false); } }
  function reset() { setR(0); setChosen(null); setRevealed(false); setScore(0); setDone(false); setHistory([]); }
  if (done) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>TWO-OBJECT PATTERNS</div><div style={{ fontSize: 32, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{score}/{ROUNDS.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{history.map((h, i) => <div key={i} style={{ background: h.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "8px 14px", borderLeft: `2px solid ${h.correct ? "#10b981" : "#f43f5e"}` }}><div style={{ fontSize: 12, color: "#64748b" }}>{h.q.substring(0, 55)}</div><div style={{ fontSize: 12, fontWeight: 700, color: h.correct ? "#34d399" : "#f87171" }}>{h.answer}</div></div>)}</div><button onClick={reset} style={{ width: "100%", background: C, color: "#0f172a", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Try Again</button></div>);
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}>
    <div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 3 · TWO-OBJECT PATTERNS</span><div style={{ display: "flex", gap: 5 }}>{ROUNDS.map((_, i) => <div key={i} style={{ width: 7, height: 7, borderRadius: "50%", background: i < r ? "#10b981" : i === r ? C : "#1e293b" }} />)}</div></div>
    <div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(r / ROUNDS.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div>
    <div style={{ padding: "18px 20px 0" }}>
      <div style={{ background: "#1e293b", borderRadius: 12, padding: "18px", marginBottom: 14, border: revealed ? `2px solid ${chosen === q.correct ? "#10b981" : "#f43f5e"}` : "2px solid #334155" }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>Round {r + 1}/{ROUNDS.length}</div><div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>{q.opts.map(opt => { const isC = opt === q.correct, isCh = opt === chosen; let bg = "#1e293b", border = "#334155", tc = "#94a3b8"; if (revealed) { if (isC) { bg = "#0d2a1e"; border = "#10b981"; tc = "#34d399"; } else if (isCh) { bg = "#2a0d0d"; border = "#f43f5e"; tc = "#f87171"; } } return <button key={opt} onClick={() => choose(opt)} style={{ background: bg, border: `2px solid ${border}`, borderRadius: 10, padding: "11px", fontSize: 12, fontWeight: 700, color: tc, cursor: revealed ? "default" : "pointer" }}>{opt}</button>; })}</div>
      {revealed && <><div style={{ background: chosen === q.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 10, padding: "12px 16px", borderLeft: `3px solid ${chosen === q.correct ? "#10b981" : "#f43f5e"}`, marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 700, color: chosen === q.correct ? "#34d399" : "#f87171", marginBottom: 4 }}>{chosen === q.correct ? "✓ Correct" : "✗ " + q.correct}</div><div style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.6 }}>{q.why}</div></div><button onClick={next} style={{ width: "100%", background: C, color: "#0f172a", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer", marginBottom: 20 }}>{r + 1 >= ROUNDS.length ? "Results →" : "Next →"}</button></>}
    </div>
  </div>);
}
