// VariableAccelerationPatternSpotter.jsx — Ch2 L22 Pillar 3
import { useState } from "react";
const ROUNDS = [
  { q: "a(t) = 6t, v₀ = 2 m/s. What is v(t)?", opts: ["v = 2 + 6t", "v = 2 + 3t²", "v = 2 + 6t²", "v = 6t"], correct: "v = 2 + 3t²", why: "v = v₀ + ∫6t dt = 2 + 3t². Don't forget to integrate — ∫6t dt = 3t², not 6t." },
  { q: "Why can't you use v = v₀ + at when a = 6t?", opts: ["You can", "a is not constant — the formula only works for constant a", "t is not known", "v₀ must be zero"], correct: "a is not constant — the formula only works for constant a", why: "The kinematic equations assume a = const. When a depends on t, only integration gives the correct v(t)." },
  { q: "a(t) = cos(t), v₀ = 0. What is v(t)?", opts: ["v = sin(t)", "v = −sin(t)", "v = cos(t)", "v = t·cos(t)"], correct: "v = sin(t)", why: "v = ∫cos(t) dt = sin(t) + C. With v₀=0 at t=0: sin(0) + C = 0 → C = 0. So v = sin(t)." },
  { q: "v(t) = 3t². What is the displacement from t=1 to t=3?", opts: ["18 m", "26 m", "8 m", "9 m"], correct: "26 m", why: "Δx = ∫₁³ 3t² dt = [t³]₁³ = 27 − 1 = 26 m." },
  { q: "When is numerical integration (Euler method) needed instead of analytic integration?", opts: ["Always","When a(t) has no closed-form integral","When v₀ ≠ 0","When t is large"], correct: "When a(t) has no closed-form integral", why: "Analytic integration works when the antiderivative exists in closed form. Numerical methods (Euler, RK4) handle cases where it doesn't — e.g. a = e^{-t²}." },
];
export default function VariableAccelerationPatternSpotter({ params = {} }) {
  const [r, setR] = useState(0); const [chosen, setChosen] = useState(null); const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0); const [done, setDone] = useState(false); const [history, setHistory] = useState([]);
  const q = ROUNDS[r]; const C = "#f43f5e";
  function choose(opt) { if (revealed) return; setChosen(opt); setRevealed(true); const ok = opt === q.correct; if (ok) setScore(s => s + 1); setHistory(h => [...h, { q: q.q, correct: ok, answer: q.correct }]); }
  function next() { if (r + 1 >= ROUNDS.length) setDone(true); else { setR(n => n + 1); setChosen(null); setRevealed(false); } }
  function reset() { setR(0); setChosen(null); setRevealed(false); setScore(0); setDone(false); setHistory([]); }
  if (done) return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, padding: 24 }}><div style={{ fontSize: 13, color: C, fontWeight: 700, marginBottom: 12 }}>VARIABLE ACCELERATION PATTERNS</div><div style={{ fontSize: 32, fontWeight: 900, color: "#e2e8f0", marginBottom: 16 }}>{score}/{ROUNDS.length}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 20 }}>{history.map((h, i) => <div key={i} style={{ background: h.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 8, padding: "8px 14px", borderLeft: `2px solid ${h.correct ? "#10b981" : C}` }}><div style={{ fontSize: 12, color: "#64748b" }}>{h.q.substring(0, 55)}</div><div style={{ fontSize: 12, fontWeight: 700, color: h.correct ? "#34d399" : "#f87171" }}>{h.answer}</div></div>)}</div><button onClick={reset} style={{ width: "100%", background: C, color: "#fff", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer" }}>Try Again</button></div>);
  return (<div style={{ fontFamily: "'DM Sans',system-ui,sans-serif", background: "#0f172a", borderRadius: 16, overflow: "hidden" }}>
    <div style={{ padding: "14px 20px", background: "#0c1122", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span style={{ fontSize: 13, color: C, fontWeight: 700, letterSpacing: "0.08em" }}>PILLAR 3 · VARIABLE ACCELERATION</span><div style={{ display: "flex", gap: 5 }}>{ROUNDS.map((_, i) => <div key={i} style={{ width: 7, height: 7, borderRadius: "50%", background: i < r ? "#10b981" : i === r ? C : "#1e293b" }} />)}</div></div>
    <div style={{ height: 3, background: "#1e293b" }}><div style={{ height: "100%", width: `${(r / ROUNDS.length) * 100}%`, background: C, transition: "width 0.3s" }} /></div>
    <div style={{ padding: "18px 20px 0" }}>
      <div style={{ background: "#1e293b", borderRadius: 12, padding: "18px", marginBottom: 14, border: revealed ? `2px solid ${chosen === q.correct ? "#10b981" : C}` : "2px solid #334155" }}><div style={{ fontSize: 12, color: "#64748b", marginBottom: 5 }}>Round {r + 1}/{ROUNDS.length}</div><div style={{ fontSize: 15, fontWeight: 700, color: "#e2e8f0" }}>{q.q}</div></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>{q.opts.map(opt => { const isC = opt === q.correct, isCh = opt === chosen; let bg = "#1e293b", border = "#334155", tc = "#94a3b8"; if (revealed) { if (isC) { bg = "#0d2a1e"; border = "#10b981"; tc = "#34d399"; } else if (isCh) { bg = "#2a0d0d"; border = C; tc = "#f87171"; } } return <button key={opt} onClick={() => choose(opt)} style={{ background: bg, border: `2px solid ${border}`, borderRadius: 10, padding: "11px", fontSize: 12, fontWeight: 700, color: tc, cursor: revealed ? "default" : "pointer" }}>{opt}</button>; })}</div>
      {revealed && <><div style={{ background: chosen === q.correct ? "#0d2a1e" : "#2a0d0d", borderRadius: 10, padding: "12px 16px", borderLeft: `3px solid ${chosen === q.correct ? "#10b981" : C}`, marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 700, color: chosen === q.correct ? "#34d399" : "#f87171", marginBottom: 4 }}>{chosen === q.correct ? "✓ Correct" : "✗ " + q.correct}</div><div style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.6 }}>{q.why}</div></div><button onClick={next} style={{ width: "100%", background: C, color: "#fff", border: "none", borderRadius: 10, padding: 12, fontSize: 14, fontWeight: 800, cursor: "pointer", marginBottom: 20 }}>{r + 1 >= ROUNDS.length ? "Results →" : "Next →"}</button></>}
    </div>
  </div>);
}
