# UpSkillOS Funding
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (set up at https://github.com/sponsors)
github: [g4m3rm1k3]

# Open Collective (create page at https://opencollective.com)
# open_collective: upskillos

# Custom funding links
custom: ['https://upskillos.io/support']
