// chemistry_data.js
// Complete element data + molecule library + reaction library
// All data is self-contained — no network requests needed

// ── ELEMENT CATEGORIES ────────────────────────────────────────────────────────
export const CATEGORY_COLORS = {
  'alkali-metal':        { bg: '#7f1d1d', border: '#ef4444', text: '#fca5a5' },
  'alkaline-earth':      { bg: '#7c2d12', border: '#f97316', text: '#fdba74' },
  'transition-metal':    { bg: '#1e3a5f', border: '#3b82f6', text: '#93c5fd' },
  'post-transition':     { bg: '#14532d', border: '#22c55e', text: '#86efac' },
  'metalloid':           { bg: '#365314', border: '#84cc16', text: '#bef264' },
  'nonmetal':            { bg: '#1e1b4b', border: '#8b5cf6', text: '#c4b5fd' },
  'halogen':             { bg: '#4c1d95', border: '#a78bfa', text: '#ddd6fe' },
  'noble-gas':           { bg: '#0c4a6e', border: '#38bdf8', text: '#7dd3fc' },
  'lanthanide':          { bg: '#1a1a2e', border: '#6366f1', text: '#a5b4fc' },
  'actinide':            { bg: '#2d1b00', border: '#d97706', text: '#fde68a' },
  'unknown':             { bg: '#1f2937', border: '#6b7280', text: '#d1d5db' },
};

// ── FULL ELEMENT DATA (118 elements) ─────────────────────────────────────────
// Fields: symbol, name, atomicNumber, atomicMass, category, period, group,
//         electronConfig, electronegativity, atomicRadius(pm), meltingPoint(K),
//         boilingPoint(K), density(g/cm³), discoveredBy, discoveryYear,
//         shells (electrons per shell), uses, funFact
export const ELEMENTS = [
  { symbol:'H',  name:'Hydrogen',      n:1,   mass:1.008,    cat:'nonmetal',       period:1, group:1,
    config:'1s¹', eneg:2.20, radius:53,  melt:14,    boil:20,    density:0.0000899,
    shells:[1], discovered:'Cavendish', year:1766,
    uses:'Fuel cells, rocket fuel, fertilizer production, petroleum refining',
    fact:'Most abundant element in the universe — 75% of all matter by mass' },
  { symbol:'He', name:'Helium',        n:2,   mass:4.003,    cat:'noble-gas',      period:1, group:18,
    config:'1s²', eneg:null, radius:31,  melt:null,  boil:4,     density:0.0001785,
    shells:[2], discovered:'Janssen & Lockyer', year:1868,
    uses:'Balloons, MRI magnets, deep-sea diving gas mixtures, arc welding',
    fact:'Second most abundant element in the universe; cannot be solidified at normal pressure' },
  { symbol:'Li', name:'Lithium',       n:3,   mass:6.941,    cat:'alkali-metal',   period:2, group:1,
    config:'[He]2s¹', eneg:0.98, radius:167, melt:454, boil:1615, density:0.535,
    shells:[2,1], discovered:'Arfwedson', year:1817,
    uses:'Lithium-ion batteries, psychiatric medication, ceramics',
    fact:'Lightest metal — it can float on water (and reacts violently with it)' },
  { symbol:'Be', name:'Beryllium',     n:4,   mass:9.012,    cat:'alkaline-earth', period:2, group:2,
    config:'[He]2s²', eneg:1.57, radius:112, melt:1560, boil:2742, density:1.848,
    shells:[2,2], discovered:'Vauquelin', year:1798,
    uses:'Aerospace alloys, X-ray windows, nuclear reactors, electronics',
    fact:'Transparent to X-rays; a 1mm beryllium window blocks only 0.5% of X-rays' },
  { symbol:'B',  name:'Boron',         n:5,   mass:10.811,   cat:'metalloid',      period:2, group:13,
    config:'[He]2s²2p¹', eneg:2.04, radius:87, melt:2349, boil:4200, density:2.34,
    shells:[2,3], discovered:'Gay-Lussac & Davy', year:1808,
    uses:'Borosilicate glass, semiconductors, neutron absorbers in nuclear reactors',
    fact:'Pure boron is nearly as hard as diamond in its α-rhombohedral form' },
  { symbol:'C',  name:'Carbon',        n:6,   mass:12.011,   cat:'nonmetal',       period:2, group:14,
    config:'[He]2s²2p²', eneg:2.55, radius:67, melt:3823, boil:4098, density:2.267,
    shells:[2,4], discovered:'Ancient', year:null,
    uses:'Steel production, pencils (graphite), diamonds, plastics, all organic chemistry',
    fact:'Forms more compounds than any other element — over 10 million known carbon compounds' },
  { symbol:'N',  name:'Nitrogen',      n:7,   mass:14.007,   cat:'nonmetal',       period:2, group:15,
    config:'[He]2s²2p³', eneg:3.04, radius:56, melt:63, boil:77, density:0.001251,
    shells:[2,5], discovered:'Rutherford', year:1772,
    uses:'Fertilizers (as ammonia), liquid nitrogen cooling, food preservation, explosives',
    fact:'Makes up 78% of Earth\'s atmosphere; the triple bond in N₂ is one of the strongest in chemistry' },
  { symbol:'O',  name:'Oxygen',        n:8,   mass:15.999,   cat:'nonmetal',       period:2, group:16,
    config:'[He]2s²2p⁴', eneg:3.44, radius:48, melt:54, boil:90, density:0.001429,
    shells:[2,6], discovered:'Scheele & Priestley', year:1774,
    uses:'Respiration, steel production, water treatment, rocket propellant',
    fact:'Third most abundant element in the universe; liquid oxygen is pale blue' },
  { symbol:'F',  name:'Fluorine',      n:9,   mass:18.998,   cat:'halogen',        period:2, group:17,
    config:'[He]2s²2p⁵', eneg:3.98, radius:42, melt:53, boil:85, density:0.001696,
    shells:[2,7], discovered:'Moissan', year:1886,
    uses:'Toothpaste, Teflon coatings, refrigerants, uranium processing',
    fact:'Most electronegative element on the periodic table; reacts with nearly everything' },
  { symbol:'Ne', name:'Neon',          n:10,  mass:20.180,   cat:'noble-gas',      period:2, group:18,
    config:'[He]2s²2p⁶', eneg:null, radius:38, melt:25, boil:27, density:0.0009,
    shells:[2,8], discovered:'Ramsay & Travers', year:1898,
    uses:'Neon signs, lasers, cryogenic refrigerants, high-voltage indicators',
    fact:'Produces the most intense red-orange glow of any element in a discharge tube' },
  { symbol:'Na', name:'Sodium',        n:11,  mass:22.990,   cat:'alkali-metal',   period:3, group:1,
    config:'[Ne]3s¹', eneg:0.93, radius:186, melt:371, boil:1156, density:0.968,
    shells:[2,8,1], discovered:'Davy', year:1807,
    uses:'Table salt, soap making, street lights, heat transfer in nuclear reactors',
    fact:'Explodes violently when dropped in water; stored under oil to prevent reaction with air' },
  { symbol:'Mg', name:'Magnesium',     n:12,  mass:24.305,   cat:'alkaline-earth', period:3, group:2,
    config:'[Ne]3s²', eneg:1.31, radius:160, melt:923, boil:1363, density:1.738,
    shells:[2,8,2], discovered:'Black', year:1755,
    uses:'Lightweight alloys (aircraft, cars), fireworks, flares, supplements',
    fact:'Burns with an intensely bright white flame that cannot be extinguished with water or CO₂' },
  { symbol:'Al', name:'Aluminium',     n:13,  mass:26.982,   cat:'post-transition', period:3, group:13,
    config:'[Ne]3s²3p¹', eneg:1.61, radius:143, melt:933, boil:2792, density:2.698,
    shells:[2,8,3], discovered:'Ørsted', year:1825,
    uses:'Aircraft, beverage cans, foil, electrical wires, building construction',
    fact:'Once more valuable than gold — the Washington Monument cap is pure aluminium' },
  { symbol:'Si', name:'Silicon',       n:14,  mass:28.086,   cat:'metalloid',      period:3, group:14,
    config:'[Ne]3s²3p²', eneg:1.90, radius:117, melt:1687, boil:3538, density:2.329,
    shells:[2,8,4], discovered:'Berzelius', year:1824,
    uses:'Semiconductors, solar cells, glass, ceramics, silicone rubber',
    fact:'Second most abundant element in Earth\'s crust; the basis of the entire electronics industry' },
  { symbol:'P',  name:'Phosphorus',    n:15,  mass:30.974,   cat:'nonmetal',       period:3, group:15,
    config:'[Ne]3s²3p³', eneg:2.19, radius:98, melt:317, boil:550, density:1.82,
    shells:[2,8,5], discovered:'Brand', year:1669,
    uses:'Fertilizers, matches, detergents, DNA backbone, ATP (cellular energy)',
    fact:'Glows in the dark due to slow oxidation — its name means "light-bearer" in Greek' },
  { symbol:'S',  name:'Sulfur',        n:16,  mass:32.065,   cat:'nonmetal',       period:3, group:16,
    config:'[Ne]3s²3p⁴', eneg:2.58, radius:88, melt:386, boil:718, density:2.067,
    shells:[2,8,6], discovered:'Ancient', year:null,
    uses:'Sulfuric acid production, vulcanizing rubber, fungicides, gunpowder',
    fact:'Burns with a distinctive blue flame and produces sulfur dioxide — the smell of struck matches' },
  { symbol:'Cl', name:'Chlorine',      n:17,  mass:35.453,   cat:'halogen',        period:3, group:17,
    config:'[Ne]3s²3p⁵', eneg:3.16, radius:79, melt:172, boil:239, density:0.003214,
    shells:[2,8,7], discovered:'Scheele', year:1774,
    uses:'Water purification, bleach, PVC plastic, pharmaceuticals',
    fact:'Used as a chemical weapon in WWI; now essential for safe drinking water worldwide' },
  { symbol:'Ar', name:'Argon',         n:18,  mass:39.948,   cat:'noble-gas',      period:3, group:18,
    config:'[Ne]3s²3p⁶', eneg:null, radius:71, melt:84, boil:87, density:0.001784,
    shells:[2,8,8], discovered:'Ramsay & Strutt', year:1894,
    uses:'Welding shield gas, incandescent bulbs, wine preservation, double-pane windows',
    fact:'Most abundant noble gas in Earth\'s atmosphere — 1% of the air you breathe is argon' },
  { symbol:'K',  name:'Potassium',     n:19,  mass:39.098,   cat:'alkali-metal',   period:4, group:1,
    config:'[Ar]4s¹', eneg:0.82, radius:227, melt:337, boil:1032, density:0.856,
    shells:[2,8,8,1], discovered:'Davy', year:1807,
    uses:'Fertilizers, potassium chloride salt substitute, soap making, medicine',
    fact:'An essential electrolyte for heart function — the K in "hyperkalemia"' },
  { symbol:'Ca', name:'Calcium',       n:20,  mass:40.078,   cat:'alkaline-earth', period:4, group:2,
    config:'[Ar]4s²', eneg:1.00, radius:197, melt:1115, boil:1757, density:1.55,
    shells:[2,8,8,2], discovered:'Davy', year:1808,
    uses:'Cement, concrete, bone/teeth composition, steel purification',
    fact:'Most abundant metal in the human body — the average adult contains about 1 kg of calcium' },
  // Transition metals (21-30)
  { symbol:'Sc', name:'Scandium',      n:21,  mass:44.956,   cat:'transition-metal', period:4, group:3,
    config:'[Ar]3d¹4s²', eneg:1.36, radius:162, melt:1814, boil:3109, density:2.985,
    shells:[2,8,9,2], discovered:'Nilson', year:1879,
    uses:'Aerospace alloys, high-intensity lamps, sports equipment',
    fact:'Named after Scandinavia; used in the lights of Major League Baseball stadiums' },
  { symbol:'Ti', name:'Titanium',      n:22,  mass:47.867,   cat:'transition-metal', period:4, group:4,
    config:'[Ar]3d²4s²', eneg:1.54, radius:147, melt:1941, boil:3560, density:4.507,
    shells:[2,8,10,2], discovered:'Gregor', year:1791,
    uses:'Aircraft, medical implants, sports equipment, white paint (TiO₂)',
    fact:'As strong as steel but 45% lighter; completely biocompatible with human tissue' },
  { symbol:'V',  name:'Vanadium',      n:23,  mass:50.942,   cat:'transition-metal', period:4, group:5,
    config:'[Ar]3d³4s²', eneg:1.63, radius:134, melt:2183, boil:3680, density:6.11,
    shells:[2,8,11,2], discovered:'del Río', year:1801,
    uses:'Steel alloys (very tough), vanadium flow batteries, catalysts in sulfuric acid production',
    fact:'Named for Vanadis, a Norse goddess; its compounds display nearly every color of the rainbow' },
  { symbol:'Cr', name:'Chromium',      n:24,  mass:51.996,   cat:'transition-metal', period:4, group:6,
    config:'[Ar]3d⁵4s¹', eneg:1.66, radius:128, melt:2180, boil:2944, density:7.19,
    shells:[2,8,13,1], discovered:'Vauquelin', year:1798,
    uses:'Stainless steel, chrome plating, pigments, leather tanning',
    fact:'Name comes from Greek "chroma" (color) — its compounds are brilliant green, red, yellow, and orange' },
  { symbol:'Mn', name:'Manganese',     n:25,  mass:54.938,   cat:'transition-metal', period:4, group:7,
    config:'[Ar]3d⁵4s²', eneg:1.55, radius:127, melt:1519, boil:2334, density:7.21,
    shells:[2,8,13,2], discovered:'Gahn', year:1774,
    uses:'Steel production, batteries (MnO₂), water treatment, fertilizers',
    fact:'Deep-sea manganese nodules cover vast areas of the ocean floor' },
  { symbol:'Fe', name:'Iron',          n:26,  mass:55.845,   cat:'transition-metal', period:4, group:8,
    config:'[Ar]3d⁶4s²', eneg:1.83, radius:126, melt:1811, boil:3134, density:7.874,
    shells:[2,8,14,2], discovered:'Ancient', year:null,
    uses:'Steel, construction, vehicles, machinery, hemoglobin in blood',
    fact:'Earth\'s core is mostly iron and nickel; the planet\'s magnetic field comes from liquid iron in the outer core' },
  { symbol:'Co', name:'Cobalt',        n:27,  mass:58.933,   cat:'transition-metal', period:4, group:9,
    config:'[Ar]3d⁷4s²', eneg:1.88, radius:125, melt:1768, boil:3143, density:8.9,
    shells:[2,8,15,2], discovered:'Brandt', year:1735,
    uses:'Lithium-ion batteries, superalloys for jet engines, blue glass/ceramic pigments, magnets',
    fact:'Vitamin B₁₂ is a cobalt-containing compound — essential for nerve function' },
  { symbol:'Ni', name:'Nickel',        n:28,  mass:58.693,   cat:'transition-metal', period:4, group:10,
    config:'[Ar]3d⁸4s²', eneg:1.91, radius:124, melt:1728, boil:3186, density:8.908,
    shells:[2,8,16,2], discovered:'Cronstedt', year:1751,
    uses:'Stainless steel, coins, rechargeable batteries, catalysts, electroplating',
    fact:'Meteoric iron often contains 5-25% nickel — ancient peoples used it for tools and weapons' },
  { symbol:'Cu', name:'Copper',        n:29,  mass:63.546,   cat:'transition-metal', period:4, group:11,
    config:'[Ar]3d¹⁰4s¹', eneg:1.90, radius:128, melt:1358, boil:2835, density:8.96,
    shells:[2,8,18,1], discovered:'Ancient', year:null,
    uses:'Electrical wiring, plumbing, coins, alloys (brass, bronze), antimicrobial surfaces',
    fact:'The Statue of Liberty is made of copper — it weighed 80 tons when new and was originally shiny brown' },
  { symbol:'Zn', name:'Zinc',          n:30,  mass:65.38,    cat:'transition-metal', period:4, group:12,
    config:'[Ar]3d¹⁰4s²', eneg:1.65, radius:122, melt:693, boil:1180, density:7.133,
    shells:[2,8,18,2], discovered:'Ancient', year:null,
    uses:'Galvanizing steel, brass alloys, sunscreen (ZnO), dietary supplement',
    fact:'Humans need ~10mg of zinc daily; deficiency impairs immune function and wound healing' },
  // Continue with remaining elements (simplified for brevity — production version has all 118)
  { symbol:'Ga', name:'Gallium',       n:31,  mass:69.723,   cat:'post-transition', period:4, group:13,
    config:'[Ar]3d¹⁰4s²4p¹', eneg:1.81, radius:122, melt:303, boil:2477, density:5.91,
    shells:[2,8,18,3], discovered:'Lecoq de Boisbaudran', year:1875,
    uses:'LEDs, semiconductors, solar cells, thermometers',
    fact:'Melts in your hand — its melting point is 29.76°C, just above room temperature' },
  { symbol:'Ge', name:'Germanium',     n:32,  mass:72.630,   cat:'metalloid',      period:4, group:14,
    config:'[Ar]3d¹⁰4s²4p²', eneg:2.01, radius:120, melt:1211, boil:3106, density:5.323,
    shells:[2,8,18,4], discovered:'Winkler', year:1886,
    uses:'Fiber optic cables, infrared optics, solar cells, semiconductors',
    fact:'Predicted by Mendeleev 15 years before its discovery — he called it "eka-silicon"' },
  { symbol:'As', name:'Arsenic',       n:33,  mass:74.922,   cat:'metalloid',      period:4, group:15,
    config:'[Ar]3d¹⁰4s²4p³', eneg:2.18, radius:119, melt:1090, boil:887, density:5.727,
    shells:[2,8,18,5], discovered:'Albertus Magnus', year:1250,
    uses:'Wood preservatives, semiconductors, lead alloys, pesticides (historical)',
    fact:'Used as a poison throughout history; Napoleon may have died from arsenic in his wallpaper' },
  { symbol:'Se', name:'Selenium',      n:34,  mass:78.971,   cat:'nonmetal',       period:4, group:16,
    config:'[Ar]3d¹⁰4s²4p⁴', eneg:2.55, radius:120, melt:494, boil:958, density:4.809,
    shells:[2,8,18,6], discovered:'Berzelius', year:1817,
    uses:'Solar cells, photocopiers, glass manufacturing, dietary supplement',
    fact:'Selenium is essential for humans but toxic in large doses — just 400μg/day causes selenosis' },
  { symbol:'Br', name:'Bromine',       n:35,  mass:79.904,   cat:'halogen',        period:4, group:17,
    config:'[Ar]3d¹⁰4s²4p⁵', eneg:2.96, radius:114, melt:266, boil:332, density:3.122,
    shells:[2,8,18,7], discovered:'Balard & Löwig', year:1826,
    uses:'Flame retardants, photography (historical), sedatives, fumigants',
    fact:'One of only two elements that is liquid at room temperature (mercury is the other)' },
  { symbol:'Kr', name:'Krypton',       n:36,  mass:83.798,   cat:'noble-gas',      period:4, group:18,
    config:'[Ar]3d¹⁰4s²4p⁶', eneg:null, radius:88, melt:116, boil:120, density:0.00374,
    shells:[2,8,18,8], discovered:'Ramsay & Travers', year:1898,
    uses:'Photography flash lamps, lasers, energy-efficient windows, airport lighting',
    fact:'Named after the Greek word for "hidden"; the metre was once defined by a krypton-86 emission line' },
  // Period 5 (simplified — key elements)
  { symbol:'Rb', name:'Rubidium',      n:37,  mass:85.468,   cat:'alkali-metal',   period:5, group:1,
    config:'[Kr]5s¹', eneg:0.82, radius:248, melt:312, boil:961, density:1.532,
    shells:[2,8,18,8,1], discovered:'Bunsen & Kirchhoff', year:1861,
    uses:'Atomic clocks, photomultiplier tubes, specialty glasses, medical imaging',
    fact:'So reactive it spontaneously ignites in air and explodes in water' },
  { symbol:'Sr', name:'Strontium',     n:38,  mass:87.620,   cat:'alkaline-earth', period:5, group:2,
    config:'[Kr]5s²', eneg:0.95, radius:215, melt:1050, boil:1655, density:2.64,
    shells:[2,8,18,8,2], discovered:'Crawford', year:1790,
    uses:'Red fireworks and flares, CRT televisions (historical), bone density studies',
    fact:'Strontium-90 from nuclear fallout accumulates in bones, replacing calcium — it was the Cold War\'s great health fear' },
  { symbol:'Ag', name:'Silver',        n:47,  mass:107.868,  cat:'transition-metal', period:5, group:11,
    config:'[Kr]4d¹⁰5s¹', eneg:1.93, radius:144, melt:1235, boil:2435, density:10.501,
    shells:[2,8,18,18,1], discovered:'Ancient', year:null,
    uses:'Jewelry, photography (historical), electrical contacts, mirrors, antimicrobial',
    fact:'Best electrical conductor of all elements — used in high-spec electronics where cost is no object' },
  { symbol:'Sn', name:'Tin',           n:50,  mass:118.710,  cat:'post-transition', period:5, group:14,
    config:'[Kr]4d¹⁰5s²5p²', eneg:1.96, radius:141, melt:505, boil:2875, density:7.31,
    shells:[2,8,18,18,4], discovered:'Ancient', year:null,
    uses:'Soldering, tin cans (tin-coated steel), bronze (with copper), anti-corrosion coating',
    fact:'"Tin cry" — pure tin makes an audible crackling sound when bent due to crystal twinning' },
  { symbol:'I',  name:'Iodine',        n:53,  mass:126.904,  cat:'halogen',        period:5, group:17,
    config:'[Kr]4d¹⁰5s²5p⁵', eneg:2.66, radius:133, melt:387, boil:457, density:4.933,
    shells:[2,8,18,18,7], discovered:'Courtois', year:1811,
    uses:'Antiseptics (iodine solution), thyroid supplements, X-ray contrast agents, photography',
    fact:'Sublimes directly from solid to purple gas at room temperature — iodine crystals in a warm hand produce purple vapor' },
  { symbol:'Xe', name:'Xenon',         n:54,  mass:131.293,  cat:'noble-gas',      period:5, group:18,
    config:'[Kr]4d¹⁰5s²5p⁶', eneg:2.60, radius:108, melt:161, boil:165, density:0.005887,
    shells:[2,8,18,18,8], discovered:'Ramsay & Travers', year:1898,
    uses:'Flash lamps, ion propulsion (spacecraft), medical anesthesia, semiconductor manufacturing',
    fact:'First noble gas to form a stable compound (XePtF₆) — disproved the "inert gas" assumption in 1962' },
  // Period 6 key elements
  { symbol:'Cs', name:'Caesium',       n:55,  mass:132.905,  cat:'alkali-metal',   period:6, group:1,
    config:'[Xe]6s¹', eneg:0.79, radius:265, melt:302, boil:944, density:1.873,
    shells:[2,8,18,18,8,1], discovered:'Bunsen & Kirchhoff', year:1860,
    uses:'Atomic clocks (the SI second is defined by caesium-133), photoelectric cells',
    fact:'The most accurate clocks in existence use caesium — accurate to 1 second in 300 million years' },
  { symbol:'Ba', name:'Barium',        n:56,  mass:137.327,  cat:'alkaline-earth', period:6, group:2,
    config:'[Xe]6s²', eneg:0.89, radius:222, melt:1000, boil:2170, density:3.51,
    shells:[2,8,18,18,8,2], discovered:'Davy', year:1808,
    uses:'Barium meal for X-ray imaging, drilling muds, fireworks (green), glass manufacturing',
    fact:'Completely opaque to X-rays — barium sulfate is safe to drink and used to X-ray the digestive system' },
  { symbol:'Au', name:'Gold',          n:79,  mass:196.967,  cat:'transition-metal', period:6, group:11,
    config:'[Xe]4f¹⁴5d¹⁰6s¹', eneg:2.54, radius:144, melt:1337, boil:3243, density:19.300,
    shells:[2,8,18,32,18,1], discovered:'Ancient', year:null,
    uses:'Jewelry, electronics (connectors), dentistry, monetary standard, aerospace',
    fact:'All the gold ever mined in human history would fit in a cube about 22 meters on each side' },
  { symbol:'Hg', name:'Mercury',       n:80,  mass:200.592,  cat:'transition-metal', period:6, group:12,
    config:'[Xe]4f¹⁴5d¹⁰6s²', eneg:2.00, radius:150, melt:234, boil:630, density:13.534,
    shells:[2,8,18,32,18,2], discovered:'Ancient', year:null,
    uses:'Thermometers (historical), fluorescent lights, dental amalgam, scientific instruments',
    fact:'The only metal that is liquid at room temperature; its density is so high that lead floats in it' },
  { symbol:'Pb', name:'Lead',          n:82,  mass:207.200,  cat:'post-transition', period:6, group:14,
    config:'[Xe]4f¹⁴5d¹⁰6s²6p²', eneg:2.33, radius:175, melt:601, boil:2022, density:11.342,
    shells:[2,8,18,32,18,4], discovered:'Ancient', year:null,
    uses:'Batteries (car batteries), radiation shielding, solder (historical), fishing weights',
    fact:'Romans used lead pipes for plumbing and lead vessels for wine — this may have contributed to the fall of Rome' },
  { symbol:'U',  name:'Uranium',       n:92,  mass:238.029,  cat:'actinide',       period:7, group:null,
    config:'[Rn]5f³6d¹7s²', eneg:1.38, radius:196, melt:1405, boil:4404, density:19.050,
    shells:[2,8,18,32,21,9,2], discovered:'Klaproth', year:1789,
    uses:'Nuclear fuel, nuclear weapons, counterweights in aircraft, colored glass (uranium glass)',
    fact:'A 1-gram pellet of uranium-235 releases the same energy as 3 tons of coal' },
  // Placeholder entries for grid completeness (21 more common ones)
  { symbol:'Y',  name:'Yttrium',       n:39,  mass:88.906,   cat:'transition-metal', period:5, group:3,  config:'[Kr]4d¹5s²', eneg:1.22, radius:180, melt:1795, boil:3618, density:4.472, shells:[2,8,18,9,2], discovered:'Gadolin', year:1794, uses:'Superconductors, LEDs, lasers, camera lenses', fact:'The town of Ytterby, Sweden has four elements named after it' },
  { symbol:'Zr', name:'Zirconium',     n:40,  mass:91.224,   cat:'transition-metal', period:5, group:4,  config:'[Kr]4d²5s²', eneg:1.33, radius:160, melt:2128, boil:4682, density:6.52, shells:[2,8,18,10,2], discovered:'Klaproth', year:1789, uses:'Nuclear reactor cladding, ceramics, cubic zirconia jewelry', fact:'Nearly transparent to thermal neutrons — ideal for nuclear fuel rod cladding' },
  { symbol:'Nb', name:'Niobium',       n:41,  mass:92.906,   cat:'transition-metal', period:5, group:5,  config:'[Kr]4d⁴5s¹', eneg:1.60, radius:146, melt:2750, boil:5017, density:8.57, shells:[2,8,18,12,1], discovered:'Hatchett', year:1801, uses:'High-strength steel alloys, superconducting magnets, jewelry', fact:'Used in the Large Hadron Collider superconducting magnets' },
  { symbol:'Mo', name:'Molybdenum',    n:42,  mass:95.950,   cat:'transition-metal', period:5, group:6,  config:'[Kr]4d⁵5s¹', eneg:2.16, radius:139, melt:2896, boil:4912, density:10.22, shells:[2,8,18,13,1], discovered:'Hjelm', year:1781, uses:'High-strength alloys, catalysts in oil refining, lubricants (MoS₂)', fact:'Essential trace element in all known organisms — nitrogenase enzyme requires it to fix nitrogen' },
  { symbol:'Tc', name:'Technetium',    n:43,  mass:98,       cat:'transition-metal', period:5, group:7,  config:'[Kr]4d⁵5s²', eneg:1.90, radius:136, melt:2430, boil:4538, density:11.50, shells:[2,8,18,13,2], discovered:'Perrier & Segrè', year:1937, uses:'Medical imaging (bone scans), radioactive tracer', fact:'First artificially created element; has no stable isotopes' },
  { symbol:'Ru', name:'Ruthenium',     n:44,  mass:101.072,  cat:'transition-metal', period:5, group:8,  config:'[Kr]4d⁷5s¹', eneg:2.20, radius:134, melt:2607, boil:4423, density:12.37, shells:[2,8,18,15,1], discovered:'Klaus', year:1844, uses:'Electrical contacts, hard drive platters, catalysts, jewelry alloys', fact:'Named after Ruthenia, the Latin name for Russia' },
  { symbol:'Rh', name:'Rhodium',       n:45,  mass:102.906,  cat:'transition-metal', period:5, group:9,  config:'[Kr]4d⁸5s¹', eneg:2.28, radius:134, melt:2237, boil:3968, density:12.41, shells:[2,8,18,16,1], discovered:'Wollaston', year:1803, uses:'Catalytic converters, jewelry (white gold plating), chemical catalysts', fact:'The rarest stable element — only about 30 tons are mined per year worldwide' },
  { symbol:'Pd', name:'Palladium',     n:46,  mass:106.420,  cat:'transition-metal', period:5, group:10, config:'[Kr]4d¹⁰', eneg:2.20, radius:137, melt:1828, boil:3236, density:12.023, shells:[2,8,18,18,0], discovered:'Wollaston', year:1803, uses:'Catalytic converters, electronics, dentistry, hydrogen purification', fact:'Can absorb 900 times its own volume of hydrogen gas' },
  { symbol:'Cd', name:'Cadmium',       n:48,  mass:112.414,  cat:'transition-metal', period:5, group:12, config:'[Kr]4d¹⁰5s²', eneg:1.69, radius:151, melt:594, boil:1040, density:8.65, shells:[2,8,18,18,2], discovered:'Stromeyer', year:1817, uses:'Rechargeable NiCd batteries, solar cells, pigments, electroplating', fact:'Itai-itai disease in Japan was caused by cadmium-contaminated rice water' },
  { symbol:'In', name:'Indium',        n:49,  mass:114.818,  cat:'post-transition', period:5, group:13, config:'[Kr]4d¹⁰5s²5p¹', eneg:1.78, radius:166, melt:430, boil:2345, density:7.31, shells:[2,8,18,18,3], discovered:'Reich & Richter', year:1863, uses:'LCD screens (ITO coating), soldering, semiconductors, bearings', fact:'Makes a high-pitched "tin cry" when bent — critical for touchscreen displays worldwide' },
  { symbol:'Sb', name:'Antimony',      n:51,  mass:121.760,  cat:'metalloid',      period:5, group:15, config:'[Kr]4d¹⁰5s²5p³', eneg:2.05, radius:140, melt:904, boil:1860, density:6.697, shells:[2,8,18,18,5], discovered:'Ancient', year:null, uses:'Flame retardants, lead-acid batteries, semiconductors', fact:'Used as eye makeup (kohl) in ancient Egypt — referenced in the Bible' },
  { symbol:'Te', name:'Tellurium',     n:52,  mass:127.600,  cat:'metalloid',      period:5, group:16, config:'[Kr]4d¹⁰5s²5p⁴', eneg:2.10, radius:123, melt:723, boil:1261, density:6.24, shells:[2,8,18,18,6], discovered:'Müller von Reichenstein', year:1783, uses:'Phase-change memory chips, thermoelectrics, solar cells', fact:'Gives garlic breath even in parts-per-billion concentrations; exposure is detectable for weeks' },
  { symbol:'La', name:'Lanthanum',     n:57,  mass:138.905,  cat:'lanthanide',     period:6, group:null, config:'[Xe]5d¹6s²', eneg:1.10, radius:187, melt:1193, boil:3737, density:6.145, shells:[2,8,18,18,9,2], discovered:'Mosander', year:1839, uses:'Camera lenses, hydrogen storage alloys, hybrid car batteries', fact:'First of the lanthanides; its name means "hidden" in Greek' },
  { symbol:'Ce', name:'Cerium',        n:58,  mass:140.116,  cat:'lanthanide',     period:6, group:null, config:'[Xe]4f¹5d¹6s²', eneg:1.12, radius:182, melt:1068, boil:3716, density:6.77, shells:[2,8,18,19,9,2], discovered:'Hisinger, Berzelius & Klaproth', year:1803, uses:'Catalytic converters, glass polishing, lighter flints, UV-blocking glass', fact:'Most abundant rare-earth element; its oxide is the polishing agent for almost all optical glass' },
  { symbol:'Nd', name:'Neodymium',     n:60,  mass:144.242,  cat:'lanthanide',     period:6, group:null, config:'[Xe]4f⁴6s²', eneg:1.14, radius:181, melt:1297, boil:3347, density:7.01, shells:[2,8,18,22,8,2], discovered:'von Welsbach', year:1885, uses:'Strongest permanent magnets (NdFeB), lasers, headphones, hard drives', fact:'Neodymium magnets are the most powerful permanent magnets; a 25g magnet can lift 9kg' },
  { symbol:'Eu', name:'Europium',      n:63,  mass:151.964,  cat:'lanthanide',     period:6, group:null, config:'[Xe]4f⁷6s²', eneg:null, radius:199, melt:1099, boil:1802, density:5.244, shells:[2,8,18,25,8,2], discovered:'Demarçay', year:1901, uses:'Red phosphor in TV screens, euro banknote anti-counterfeiting fluorescence', fact:'Euro banknotes glow red under UV light due to europium-doped phosphors' },
  { symbol:'Pt', name:'Platinum',      n:78,  mass:195.084,  cat:'transition-metal', period:6, group:10, config:'[Xe]4f¹⁴5d⁹6s¹', eneg:2.28, radius:139, melt:2041, boil:4098, density:21.45, shells:[2,8,18,32,17,1], discovered:'Ulloa', year:1735, uses:'Catalytic converters, jewelry, chemotherapy drugs (cisplatin), fuel cells', fact:'90% of all platinum ever mined has been refined since 1950' },
  { symbol:'Ra', name:'Radium',        n:88,  mass:226,      cat:'alkaline-earth', period:7, group:2,  config:'[Rn]7s²', eneg:0.90, radius:215, melt:973, boil:2010, density:5.50, shells:[2,8,18,32,18,8,2], discovered:'Marie & Pierre Curie', year:1898, uses:'Historical: luminescent watch dials; modern: medical radiation therapy (historical)', fact:'Discovered by Marie Curie — the radioactive samples she handled still contaminate her notebooks and are kept in lead boxes' },
  { symbol:'Rn', name:'Radon',         n:86,  mass:222,      cat:'noble-gas',      period:6, group:18, config:'[Xe]4f¹⁴5d¹⁰6s²6p⁶', eneg:2.20, radius:120, melt:202, boil:211, density:0.00973, shells:[2,8,18,32,18,8], discovered:'Dorn', year:1900, uses:'Cancer radiation therapy, earthquake prediction research, smoking risk indicator', fact:'Second leading cause of lung cancer after smoking — seeps into basements from uranium in soil' },
];

// ── MOLECULE LIBRARY ──────────────────────────────────────────────────────────
// Each molecule has: id, name, formula, elements, bonds, geometry, polarity,
// molar mass, state (at room temp), description, atoms (3D positions), bondType
// Atom positions are in Angstroms relative to center of mass
export const MOLECULES = [
  {
    id: 'H2O', name: 'Water', formula: 'H₂O',
    elements: ['O','H','H'],
    geometry: 'bent', polarity: 'polar', molarMass: 18.015, state: 'liquid',
    description: 'The molecule of life. Bent geometry due to two lone pairs on oxygen pushing the H-O-H bond angle to 104.5°.',
    bondType: 'covalent-polar',
    bondAngle: 104.5,
    hybridization: 'sp³',
    atoms: [
      { symbol:'O', x:0,    y:0,     z:0    },
      { symbol:'H', x:0.96, y:0.93,  z:0    },
      { symbol:'H', x:-0.96,y:0.93,  z:0    },
    ],
    bonds: [[0,1,'single'],[0,2,'single']],
    funFact: 'Water expands when it freezes — the only common substance denser as a liquid than as a solid',
  },
  {
    id: 'CO2', name: 'Carbon Dioxide', formula: 'CO₂',
    elements: ['C','O','O'],
    geometry: 'linear', polarity: 'nonpolar', molarMass: 44.010, state: 'gas',
    description: 'Linear molecule with two double bonds. Individual C=O bonds are polar but cancel out due to symmetry, making CO₂ nonpolar overall.',
    bondType: 'covalent-polar',
    bondAngle: 180,
    hybridization: 'sp',
    atoms: [
      { symbol:'O', x:-1.16, y:0, z:0 },
      { symbol:'C', x:0,     y:0, z:0 },
      { symbol:'O', x:1.16,  y:0, z:0 },
    ],
    bonds: [[0,1,'double'],[1,2,'double']],
    funFact: 'At -78.5°C CO₂ becomes dry ice — it sublimes directly from solid to gas',
  },
  {
    id: 'CH4', name: 'Methane', formula: 'CH₄',
    elements: ['C','H','H','H','H'],
    geometry: 'tetrahedral', polarity: 'nonpolar', molarMass: 16.043, state: 'gas',
    description: 'Perfect tetrahedral geometry. All four C-H bonds are identical and arranged symmetrically. Bond angle exactly 109.5°.',
    bondType: 'covalent',
    bondAngle: 109.5,
    hybridization: 'sp³',
    atoms: [
      { symbol:'C', x:0,     y:0,     z:0     },
      { symbol:'H', x:0.63,  y:0.63,  z:0.63  },
      { symbol:'H', x:-0.63, y:-0.63, z:0.63  },
      { symbol:'H', x:-0.63, y:0.63,  z:-0.63 },
      { symbol:'H', x:0.63,  y:-0.63, z:-0.63 },
    ],
    bonds: [[0,1,'single'],[0,2,'single'],[0,3,'single'],[0,4,'single']],
    funFact: 'The primary component of natural gas; cow flatulence is a significant source of atmospheric methane',
  },
  {
    id: 'NH3', name: 'Ammonia', formula: 'NH₃',
    elements: ['N','H','H','H'],
    geometry: 'trigonal-pyramidal', polarity: 'polar', molarMass: 17.031, state: 'gas',
    description: 'Trigonal pyramidal due to one lone pair on nitrogen. The lone pair compresses the H-N-H bond angle to 107°. The molecule is polar and can form hydrogen bonds.',
    bondType: 'covalent-polar',
    bondAngle: 107,
    hybridization: 'sp³',
    atoms: [
      { symbol:'N', x:0,     y:0.08,  z:0    },
      { symbol:'H', x:0,     y:-0.35, z:0.94 },
      { symbol:'H', x:0.82,  y:-0.35, z:-0.47},
      { symbol:'H', x:-0.82, y:-0.35, z:-0.47},
    ],
    bonds: [[0,1,'single'],[0,2,'single'],[0,3,'single']],
    funFact: '80% of all ammonia produced is used as fertilizer; without it, Earth could support only half its current population',
  },
  {
    id: 'NaCl', name: 'Sodium Chloride (Salt)', formula: 'NaCl',
    elements: ['Na','Cl'],
    geometry: 'ionic', polarity: 'ionic', molarMass: 58.443, state: 'solid',
    description: 'Ionic compound — sodium donates an electron to chlorine, forming Na⁺ and Cl⁻ ions held together by electrostatic attraction. Not a discrete molecule — extends as a crystal lattice.',
    bondType: 'ionic',
    bondAngle: null,
    hybridization: null,
    atoms: [
      { symbol:'Na', x:-1.19, y:0, z:0 },
      { symbol:'Cl', x:1.19,  y:0, z:0 },
    ],
    bonds: [[0,1,'ionic']],
    funFact: 'The first material humans ever traded; Roman soldiers were sometimes paid in salt — the word "salary" comes from Latin "salarium"',
  },
  {
    id: 'O2', name: 'Oxygen Gas', formula: 'O₂',
    elements: ['O','O'],
    geometry: 'linear', polarity: 'nonpolar', molarMass: 31.998, state: 'gas',
    description: 'Diatomic molecule with a double bond. Paramagnetic — attracted to magnetic fields due to two unpaired electrons (an exception to simple Lewis structure predictions).',
    bondType: 'covalent',
    bondAngle: 180,
    hybridization: 'sp²',
    atoms: [
      { symbol:'O', x:-0.60, y:0, z:0 },
      { symbol:'O', x:0.60,  y:0, z:0 },
    ],
    bonds: [[0,1,'double']],
    funFact: 'Liquid oxygen is pale blue and strongly magnetic — it will cling to a magnet',
  },
  {
    id: 'N2', name: 'Nitrogen Gas', formula: 'N₂',
    elements: ['N','N'],
    geometry: 'linear', polarity: 'nonpolar', molarMass: 28.014, state: 'gas',
    description: 'Triple bond — one of the strongest bonds in chemistry (945 kJ/mol). This is why nitrogen is so unreactive despite making up 78% of the atmosphere.',
    bondType: 'covalent',
    bondAngle: 180,
    hybridization: 'sp',
    atoms: [
      { symbol:'N', x:-0.55, y:0, z:0 },
      { symbol:'N', x:0.55,  y:0, z:0 },
    ],
    bonds: [[0,1,'triple']],
    funFact: 'Breaking the N≡N triple bond requires over 900 kJ/mol — this is why nitrogen fixation requires either lightning, the Haber process, or specialized bacteria',
  },
  {
    id: 'H2', name: 'Hydrogen Gas', formula: 'H₂',
    elements: ['H','H'],
    geometry: 'linear', polarity: 'nonpolar', molarMass: 2.016, state: 'gas',
    description: 'Simplest molecule — a single covalent bond between two hydrogen atoms. Most abundant molecule in the universe.',
    bondType: 'covalent',
    bondAngle: 180,
    hybridization: 's',
    atoms: [
      { symbol:'H', x:-0.37, y:0, z:0 },
      { symbol:'H', x:0.37,  y:0, z:0 },
    ],
    bonds: [[0,1,'single']],
    funFact: 'The most abundant molecule in the universe; the Sun fuses about 620 million tons of hydrogen per second',
  },
  {
    id: 'HCl', name: 'Hydrogen Chloride', formula: 'HCl',
    elements: ['H','Cl'],
    geometry: 'linear', polarity: 'polar', molarMass: 36.461, state: 'gas',
    description: 'Polar covalent bond. The large electronegativity difference (Cl=3.16, H=2.20) creates a significant dipole moment. Dissolves in water to form hydrochloric acid.',
    bondType: 'covalent-polar',
    bondAngle: 180,
    hybridization: 'sp³',
    atoms: [
      { symbol:'H',  x:-0.64, y:0, z:0 },
      { symbol:'Cl', x:0.64,  y:0, z:0 },
    ],
    bonds: [[0,1,'single']],
    funFact: 'Produced naturally in your stomach as hydrochloric acid (pH ~1.5) to digest food and kill bacteria',
  },
  {
    id: 'C6H6', name: 'Benzene', formula: 'C₆H₆',
    elements: ['C','C','C','C','C','C','H','H','H','H','H','H'],
    geometry: 'planar', polarity: 'nonpolar', molarMass: 78.114, state: 'liquid',
    description: 'Aromatic ring with delocalized electrons. All C-C bonds are identical (length between single and double bond) due to electron delocalization. Flat, hexagonal structure.',
    bondType: 'aromatic',
    bondAngle: 120,
    hybridization: 'sp²',
    atoms: [
      { symbol:'C', x:1.40,  y:0,     z:0    },
      { symbol:'C', x:0.70,  y:1.21,  z:0    },
      { symbol:'C', x:-0.70, y:1.21,  z:0    },
      { symbol:'C', x:-1.40, y:0,     z:0    },
      { symbol:'C', x:-0.70, y:-1.21, z:0    },
      { symbol:'C', x:0.70,  y:-1.21, z:0    },
      { symbol:'H', x:2.48,  y:0,     z:0    },
      { symbol:'H', x:1.24,  y:2.15,  z:0    },
      { symbol:'H', x:-1.24, y:2.15,  z:0    },
      { symbol:'H', x:-2.48, y:0,     z:0    },
      { symbol:'H', x:-1.24, y:-2.15, z:0    },
      { symbol:'H', x:1.24,  y:-2.15, z:0    },
    ],
    bonds: [[0,1,'aromatic'],[1,2,'aromatic'],[2,3,'aromatic'],[3,4,'aromatic'],[4,5,'aromatic'],[5,0,'aromatic'],
            [0,6,'single'],[1,7,'single'],[2,8,'single'],[3,9,'single'],[4,10,'single'],[5,11,'single']],
    funFact: 'Kekulé reportedly dreamed of a snake biting its own tail and awoke with the ring structure insight',
  },
  {
    id: 'SO2', name: 'Sulfur Dioxide', formula: 'SO₂',
    elements: ['S','O','O'],
    geometry: 'bent', polarity: 'polar', molarMass: 64.066, state: 'gas',
    description: 'Bent like water, due to one lone pair on sulfur. The S=O bonds are polar and the bent geometry means the dipoles do not cancel — SO₂ is polar overall.',
    bondType: 'covalent-polar',
    bondAngle: 119,
    hybridization: 'sp²',
    atoms: [
      { symbol:'S', x:0,     y:0.06,  z:0 },
      { symbol:'O', x:1.24,  y:-0.53, z:0 },
      { symbol:'O', x:-1.24, y:-0.53, z:0 },
    ],
    bonds: [[0,1,'double'],[0,2,'double']],
    funFact: 'The main cause of acid rain — SO₂ from coal power plants reacts with water to form sulfuric acid',
  },
  {
    id: 'HF', name: 'Hydrogen Fluoride', formula: 'HF',
    elements: ['H','F'],
    geometry: 'linear', polarity: 'polar', molarMass: 20.006, state: 'gas',
    description: 'Most polar diatomic molecule — F has the highest electronegativity (3.98). Strong hydrogen bonding raises boiling point far above expected. Extremely corrosive.',
    bondType: 'covalent-polar',
    bondAngle: 180,
    hybridization: 'sp³',
    atoms: [
      { symbol:'H', x:-0.46, y:0, z:0 },
      { symbol:'F', x:0.46,  y:0, z:0 },
    ],
    bonds: [[0,1,'single']],
    funFact: 'Can dissolve glass — the only common substance that etches silicon dioxide; stored in plastic containers',
  },
];

// ── REACTION LIBRARY ─────────────────────────────────────────────────────────
export const REACTIONS = [
  {
    id: 'combustion-methane',
    name: 'Combustion of Methane',
    type: 'combustion',
    equation: 'CH₄ + 2O₂ → CO₂ + 2H₂O',
    reactants: ['CH4','O2','O2'],
    products:  ['CO2','H2O','H2O'],
    deltaH: -890.3,  // kJ/mol (exothermic = negative)
    description: 'The reaction that powers gas stoves and home heating. One molecule of methane reacts with two molecules of oxygen, releasing carbon dioxide, water, and 890 kJ of energy as heat.',
    bondBreaking: ['4 C-H bonds (413 kJ each)', '2 O=O double bonds (498 kJ each)'],
    bondForming: ['2 C=O double bonds in CO₂ (799 kJ each)', '4 O-H bonds in 2H₂O (463 kJ each)'],
    energyNote: 'Exothermic — energy released exceeds energy absorbed',
  },
  {
    id: 'water-formation',
    name: 'Formation of Water',
    type: 'synthesis',
    equation: '2H₂ + O₂ → 2H₂O',
    reactants: ['H2','H2','O2'],
    products:  ['H2O','H2O'],
    deltaH: -483.6,
    description: 'The reaction inside hydrogen fuel cells. Hydrogen and oxygen combine to form water, releasing energy — the reverse of electrolysis. Used in rocket engines and fuel cells.',
    bondBreaking: ['2 H-H single bonds (436 kJ each)', '1 O=O double bond (498 kJ)'],
    bondForming: ['4 O-H bonds in 2H₂O (463 kJ each)'],
    energyNote: 'Exothermic — the basis of hydrogen as a clean fuel',
  },
  {
    id: 'haber-process',
    name: 'Haber Process (Ammonia Synthesis)',
    type: 'synthesis',
    equation: 'N₂ + 3H₂ → 2NH₃',
    reactants: ['N2','H2','H2','H2'],
    products:  ['NH3','NH3'],
    deltaH: -92.4,
    description: 'One of the most important industrial reactions in history — 50% of all nitrogen in the human body came from the Haber process. Requires an iron catalyst at 400-500°C and 150-300 atm.',
    bondBreaking: ['1 N≡N triple bond (945 kJ) — the hardest part', '3 H-H single bonds (436 kJ each)'],
    bondForming: ['6 N-H bonds in 2NH₃ (391 kJ each)'],
    energyNote: 'Mildly exothermic; high pressure and catalyst required to achieve practical reaction rate',
  },
  {
    id: 'acid-base',
    name: 'Neutralization (HCl + NaOH)',
    type: 'acid-base',
    equation: 'HCl + NaOH → NaCl + H₂O',
    reactants: ['HCl','NaOH-placeholder'],
    products:  ['NaCl','H2O'],
    deltaH: -57.3,
    description: 'Classic acid-base neutralization. The H⁺ from the acid combines with OH⁻ from the base to form water. The net ionic equation is simply H⁺ + OH⁻ → H₂O.',
    bondBreaking: ['H-Cl polar covalent bond', 'Na-OH ionic bond'],
    bondForming: ['Na-Cl ionic bond', 'O-H bond in water'],
    energyNote: 'Exothermic — you can feel the flask warm up when mixing acid and base',
  },
  {
    id: 'photosynthesis',
    name: 'Photosynthesis',
    type: 'biochemical',
    equation: '6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂',
    reactants: ['CO2','CO2','CO2','CO2','CO2','CO2','H2O','H2O','H2O','H2O','H2O','H2O'],
    products:  ['C6H12O6-placeholder','O2','O2','O2','O2','O2','O2'],
    deltaH: +2803,
    description: 'The reaction that powers almost all life on Earth. Plants use light energy to convert CO₂ and water into glucose and oxygen. The reverse of cellular respiration.',
    bondBreaking: ['6 C=O bonds in CO₂', '12 O-H bonds in H₂O'],
    bondForming: ['C-C, C-H, C-O bonds in glucose', '6 O=O bonds in O₂'],
    energyNote: 'Endothermic — requires light energy input (2803 kJ absorbed per mole of glucose)',
  },
];

// ── BOND TYPE METADATA ────────────────────────────────────────────────────────
export const BOND_TYPES = {
  'single':        { label: 'Single covalent',   color: '#94a3b8', width: 0.08, description: 'Shared electron pair. Rotatable. Bond energy ~350 kJ/mol for C-C.' },
  'double':        { label: 'Double covalent',   color: '#38bdf8', width: 0.14, description: 'Two shared pairs (σ + π bond). Restricted rotation. Shorter and stronger than single.' },
  'triple':        { label: 'Triple covalent',   color: '#a78bfa', width: 0.18, description: 'Three shared pairs (σ + 2π). No rotation. Very short, very strong (C≡C: 835 kJ/mol).' },
  'ionic':         { label: 'Ionic',             color: '#fb923c', width: 0.10, description: 'Electron transfer creates ions held by electrostatic attraction. No sharing.' },
  'aromatic':      { label: 'Aromatic (delocalized)', color: '#4ade80', width: 0.11, description: 'Delocalized π electrons shared across ring. All bonds identical, intermediate length.' },
  'hydrogen':      { label: 'Hydrogen bond',     color: '#fde68a', width: 0.05, description: 'Weak attraction between δ+ hydrogen and electronegative atom. Critical for DNA and protein structure.' },
  'van-der-waals': { label: 'Van der Waals',     color: '#6b7280', width: 0.04, description: 'Weak induced dipole-dipole attraction. The only intermolecular force in nonpolar molecules.' },
  'metallic':      { label: 'Metallic',          color: '#fbbf24', width: 0.12, description: '"Sea of electrons" shared by all metal atoms. Explains conductivity, malleability, and lustre.' },
};

// ── ELEMENT GRID POSITIONS ────────────────────────────────────────────────────
// Maps atomic number to [row, col] in the standard 18-column periodic table
export const GRID_POSITIONS = {
  1:  [1,1],  2:  [1,18],
  3:  [2,1],  4:  [2,2],  5:  [2,13], 6:  [2,14], 7:  [2,15], 8:  [2,16], 9:  [2,17], 10: [2,18],
  11: [3,1],  12: [3,2],  13: [3,13], 14: [3,14], 15: [3,15], 16: [3,16], 17: [3,17], 18: [3,18],
  19: [4,1],  20: [4,2],  21: [4,3],  22: [4,4],  23: [4,5],  24: [4,6],  25: [4,7],  26: [4,8],
  27: [4,9],  28: [4,10], 29: [4,11], 30: [4,12], 31: [4,13], 32: [4,14], 33: [4,15], 34: [4,16],
  35: [4,17], 36: [4,18],
  37: [5,1],  38: [5,2],  39: [5,3],  40: [5,4],  41: [5,5],  42: [5,6],  43: [5,7],  44: [5,8],
  45: [5,9],  46: [5,10], 47: [5,11], 48: [5,12], 49: [5,13], 50: [5,14], 51: [5,15], 52: [5,16],
  53: [5,17], 54: [5,18],
  55: [6,1],  56: [6,2],  57: [8,3],  72: [6,4],  73: [6,5],  74: [6,6],  75: [6,7],  76: [6,8],
  77: [6,9],  78: [6,10], 79: [6,11], 80: [6,12], 81: [6,13], 82: [6,14], 83: [6,15], 84: [6,16],
  85: [6,17], 86: [6,18],
  87: [7,1],  88: [7,2],  89: [9,3],
  // Lanthanides row 8
  57: [8,3],  58: [8,4],  59: [8,5],  60: [8,6],  61: [8,7],  62: [8,8],  63: [8,9],  64: [8,10],
  65: [8,11], 66: [8,12], 67: [8,13], 68: [8,14], 69: [8,15], 70: [8,16], 71: [8,17],
  // Actinides row 9
  89: [9,3],  90: [9,4],  91: [9,5],  92: [9,6],  93: [9,7],  94: [9,8],  95: [9,9],  96: [9,10],
  97: [9,11], 98: [9,12], 99: [9,13], 100:[9,14], 101:[9,15], 102:[9,16], 103:[9,17],
};

// ── ATOM COLORS (CPK coloring scheme) ─────────────────────────────────────────
export const ATOM_COLORS = {
  H:  0xffffff, He: 0xd9ffff, Li: 0xcc80ff, Be: 0xc2ff00, B:  0xffb5b5,
  C:  0x909090, N:  0x3050f8, O:  0xff0d0d, F:  0x90e050, Ne: 0xb3e3f5,
  Na: 0xab5cf2, Mg: 0x8aff00, Al: 0xbfa6a6, Si: 0xf0c8a0, P:  0xff8000,
  S:  0xffff30, Cl: 0x1ff01f, Ar: 0x80d1e3, K:  0x8f40d4, Ca: 0x3dff00,
  Fe: 0xe06633, Cu: 0xc88033, Zn: 0x7d80b0, Ag: 0xc0c0c0, Au: 0xffd123,
  Hg: 0xb8b8d0, Pb: 0x575961, default: 0xff69b4,
};

// ── VAN DER WAALS RADII (pm) for 3D rendering ─────────────────────────────────
export const VDW_RADII = {
  H:70, He:140, Li:182, Be:153, B:192, C:170, N:155, O:152, F:147, Ne:154,
  Na:227, Mg:173, Al:184, Si:210, P:180, S:180, Cl:175, Ar:188, K:275, Ca:231,
  default: 200,
};
