export default {
  id: 'py-4-12-mega-challenge',
  slug: 'oop-mega-challenge',
  chapter: 4.1,
  order: 12,
  title: 'Capstone: Library Management System',
  subtitle: 'Build a complete system using every OOP concept from this chapter',
  tags: ['capstone', 'project', 'ABC', 'property', 'enum', 'composition', 'polymorphism', 'facade', 'dataclass'],

  hook: {
    question: 'Can you combine every OOP concept — ABCs, properties, inheritance, polymorphism, composition, enums, and magic methods — into one coherent system?',
    realWorldContext:
      'A Library Management System is a classic domain for applying OOP because it has naturally distinct entities: ' +
      'different types of media (books, DVDs, ebooks, magazines), different types of members (student, staff, premium), ' +
      'and complex rules (checkout limits, late fees, discount policies). ' +
      'This capstone brings together everything from the chapter: ' +
      'abstract base classes enforce the media and member contracts, ' +
      'properties validate access, enums represent status, ' +
      'inheritance models IS-A relationships (EBook IS-A Book), ' +
      'polymorphism handles checkout duration and late fees per media type, ' +
      'composition builds the `Library` facade, and ' +
      'magic methods make items printable and hashable. ' +
      'Study the architecture carefully — then extend it.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      'The system has four layers. **Enums** (`MediaStatus`, `MembershipType`) give type-safe status values. ' +
      '**Media classes** (`LibraryMedia` ABC → `Book`, `EBook`, `DVD`, `Magazine`) define what can be borrowed. ' +
      '**Member classes** (`LibraryMember` ABC → `StudentMember`, `StaffMember`, `PremiumMember`) define who borrows. ' +
      '**Library** is the facade — it coordinates between media and members and logs transactions.',

      'Every abstract method in `LibraryMedia` is a hook for polymorphism: ' +
      '`checkout_duration()` returns 21 for books, 7 for DVDs, 14 for ebooks. ' +
      '`late_fee_per_day()` returns different rates. ' +
      'The base class `checkout()` and `checkin()` methods call these hooks — ' +
      'one implementation handles all media types correctly.',

      '`PremiumMember` overrides `return_item()` to apply a 50% late fee discount — method overriding in service of a real business rule. ' +
      '`StaffMember` adds a `department` property. ' +
      'All member types share `can_borrow()`, `borrow()`, `pay_fine()`, and `status()` from the base class.',
    ],
    callouts: [
      {
        type: 'sequencing',
        title: 'How to read this system',
        body: '1. Read the enums first — they are simple. 2. Read LibraryMedia and one concrete subclass (Book). 3. Read LibraryMember and one subclass (StudentMember). 4. Read Library last. 5. Run the demo() and trace each call manually.',
      },
      {
        type: 'insight',
        title: 'Where to extend this system',
        body: 'Natural extensions: add a `Reservation` system, add `AudioBook` as a new media type (zero code changes to Library), add `JuniorMember` with stricter limits, add a `FineWaiver` policy using the Strategy pattern, or replace the dict "database" with a real SQLite database using the ORM from lesson 4.11.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.12 — Library Management System',
        mathBridge: 'Run each cell in order. After the demo, try adding a new media type (AudioBook) and a new member type (JuniorMember with a limit of 1 item).',
        caption: 'A complete Library Management System demonstrating every OOP concept from the chapter.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Enums and LibraryMedia ABC',
              prose:
                '`MediaStatus` and `MembershipType` are enums — type-safe named constants. ' +
                '`LibraryMedia` is the ABC for all borrowable items. ' +
                'It defines the shared state (id, title, status, due date) and shared logic (checkout, checkin, late fee calculation). ' +
                'Three abstract methods are the polymorphic hooks subclasses must implement.',
              code: [
                'from abc import ABC, abstractmethod',
                'from datetime import datetime, timedelta',
                'from enum import Enum, auto',
                'from typing import Optional, List, Dict',
                '',
                '',
                'class MediaStatus(Enum):',
                '    AVAILABLE   = auto()',
                '    CHECKED_OUT = auto()',
                '    RESERVED    = auto()',
                '    DAMAGED     = auto()',
                '',
                'class MembershipType(Enum):',
                '    STUDENT = "student"',
                '    STAFF   = "staff"',
                '    PREMIUM = "premium"',
                '',
                '',
                'class LibraryMedia(ABC):',
                '    def __init__(self, item_id: str, title: str, year: int):',
                '        self._item_id = item_id',
                '        self._title = title',
                '        self._year = year',
                '        self._status = MediaStatus.AVAILABLE',
                '        self._borrower_id: Optional[str] = None',
                '        self._due_date: Optional[datetime] = None',
                '',
                '    @property',
                '    def item_id(self):   return self._item_id',
                '    @property',
                '    def title(self):     return self._title',
                '    @property',
                '    def status(self):    return self._status',
                '    @property',
                '    def is_available(self): return self._status == MediaStatus.AVAILABLE',
                '    @property',
                '    def due_date(self):  return self._due_date',
                '',
                '    @abstractmethod',
                '    def checkout_duration(self) -> int: pass',
                '    @abstractmethod',
                '    def late_fee_per_day(self) -> float: pass',
                '    @abstractmethod',
                '    def media_type(self) -> str: pass',
                '',
                '    def checkout(self, member_id: str) -> datetime:',
                '        if not self.is_available:',
                '            raise RuntimeError(f"\'{self._title}\' is not available")',
                '        self._status = MediaStatus.CHECKED_OUT',
                '        self._borrower_id = member_id',
                '        self._due_date = datetime.now() + timedelta(days=self.checkout_duration())',
                '        return self._due_date',
                '',
                '    def checkin(self) -> float:',
                '        if self._status != MediaStatus.CHECKED_OUT:',
                '            raise RuntimeError(f"\'{self._title}\' is not checked out")',
                '        fee = self._calculate_late_fee()',
                '        self._status = MediaStatus.AVAILABLE',
                '        self._borrower_id = None',
                '        self._due_date = None',
                '        return fee',
                '',
                '    def _calculate_late_fee(self) -> float:',
                '        if self._due_date and datetime.now() > self._due_date:',
                '            days = (datetime.now() - self._due_date).days',
                '            return days * self.late_fee_per_day()',
                '        return 0.0',
                '',
                '    def __repr__(self):',
                '        return f"{self.__class__.__name__}(id={self._item_id!r}, title={self._title!r})"',
                '',
                '    def __str__(self):',
                '        return f"[{self.media_type()}] {self._title} ({self._year}) — {self._status.name}"',
                '',
                '    def __eq__(self, other):',
                '        return isinstance(other, LibraryMedia) and self._item_id == other._item_id',
                '',
                '    def __hash__(self):',
                '        return hash(self._item_id)',
                '',
                'print("LibraryMedia ABC defined.")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'Concrete media types',
              prose:
                'Each subclass implements the three abstract methods with its own rules. ' +
                '`EBook` inherits from `Book` — it IS-A `Book` with different duration/fee. ' +
                'Adding a new media type (e.g. `AudioBook`) requires only these three methods — all checkout/checkin logic is inherited.',
              code: [
                'class Book(LibraryMedia):',
                '    def __init__(self, item_id, title, author, isbn, year, pages):',
                '        super().__init__(item_id, title, year)',
                '        self.author = author',
                '        self.isbn = isbn',
                '        self.pages = pages',
                '',
                '    def checkout_duration(self): return 21    # 3 weeks',
                '    def late_fee_per_day(self):  return 0.25  # $0.25/day',
                '    def media_type(self):        return "BOOK"',
                '',
                '    def __str__(self):',
                '        return f"[BOOK] \'{self._title}\' by {self.author} ({self._year})"',
                '',
                '',
                'class EBook(Book):',
                '    def __init__(self, item_id, title, author, isbn, year, file_size_mb):',
                '        super().__init__(item_id, title, author, isbn, year, 0)',
                '        self.file_size_mb = file_size_mb',
                '',
                '    def checkout_duration(self): return 14    # 2 weeks',
                '    def late_fee_per_day(self):  return 0.10  # digital — cheaper',
                '    def media_type(self):        return "EBOOK"',
                '',
                '',
                'class DVD(LibraryMedia):',
                '    def __init__(self, item_id, title, director, year, runtime_min):',
                '        super().__init__(item_id, title, year)',
                '        self.director = director',
                '        self.runtime_min = runtime_min',
                '',
                '    def checkout_duration(self): return 7     # 1 week',
                '    def late_fee_per_day(self):  return 1.00  # $1/day',
                '    def media_type(self):        return "DVD"',
                '',
                '',
                'class Magazine(LibraryMedia):',
                '    def __init__(self, item_id, title, issue, year, month):',
                '        super().__init__(item_id, title, year)',
                '        self.issue = issue',
                '        self.month = month',
                '',
                '    def checkout_duration(self): return 7',
                '    def late_fee_per_day(self):  return 0.50',
                '    def media_type(self):        return "MAGAZINE"',
                '',
                '',
                '# Polymorphism — same call, different behaviour per type',
                'items = [',
                '    Book("B001", "Clean Code", "Robert Martin", "isbn", 2008, 464),',
                '    EBook("E001", "Python Tricks", "Dan Bader", "isbn", 2017, 15.5),',
                '    DVD("D001", "Inception", "Nolan", 2010, 148),',
                '    Magazine("M001", "Science Today", "45", 2024, "March"),',
                ']',
                '',
                'for item in items:',
                '    print(f"{item.media_type():10s}  checkout={item.checkout_duration():2d}d  fee=${item.late_fee_per_day():.2f}/day")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'Member hierarchy',
              prose:
                '`LibraryMember` defines the shared contract. Each subclass sets `max_items()` and `membership_type()`. ' +
                '`PremiumMember` overrides `return_item()` to apply a 50% late fee discount — demonstrating method overriding for a real business rule.',
              code: [
                'class LibraryMember(ABC):',
                '    def __init__(self, member_id: str, name: str, email: str):',
                '        self._member_id = member_id',
                '        self._name = name',
                '        self._email = email',
                '        self._checked_out: List[LibraryMedia] = []',
                '        self._fine_balance = 0.0',
                '',
                '    @property',
                '    def member_id(self):          return self._member_id',
                '    @property',
                '    def name(self):               return self._name',
                '    @property',
                '    def fine_balance(self):       return self._fine_balance',
                '    @property',
                '    def checked_out_count(self):  return len(self._checked_out)',
                '',
                '    @abstractmethod',
                '    def max_items(self) -> int: pass',
                '    @abstractmethod',
                '    def membership_type(self) -> MembershipType: pass',
                '',
                '    def can_borrow(self):',
                '        return self.checked_out_count < self.max_items() and self._fine_balance < 10.0',
                '',
                '    def borrow(self, item: LibraryMedia) -> datetime:',
                '        if not self.can_borrow():',
                '            if self._fine_balance >= 10.0:',
                '                raise RuntimeError(f"Outstanding fine: ${self._fine_balance:.2f}")',
                '            raise RuntimeError(f"Limit reached ({self.max_items()} items)")',
                '        due_date = item.checkout(self._member_id)',
                '        self._checked_out.append(item)',
                '        return due_date',
                '',
                '    def return_item(self, item: LibraryMedia) -> float:',
                '        if item not in self._checked_out:',
                '            raise RuntimeError(f"\'{item.title}\' not checked out by {self._name}")',
                '        fee = item.checkin()',
                '        self._checked_out.remove(item)',
                '        if fee > 0: self._fine_balance += fee',
                '        return fee',
                '',
                '    def pay_fine(self, amount: float):',
                '        amount = min(amount, self._fine_balance)',
                '        self._fine_balance -= amount',
                '        print(f"{self._name} paid ${amount:.2f}. Remaining: ${self._fine_balance:.2f}")',
                '',
                '    def status(self):',
                '        print(f"=== {self._name} [{self.membership_type().value.upper()}] ===")',
                '        print(f"  Borrowed: {self.checked_out_count}/{self.max_items()}")',
                '        print(f"  Fine:     ${self._fine_balance:.2f}")',
                '        for item in self._checked_out:',
                '            print(f"    - {item}")',
                '',
                '',
                'class StudentMember(LibraryMember):',
                '    def max_items(self):       return 3',
                '    def membership_type(self): return MembershipType.STUDENT',
                '',
                'class StaffMember(LibraryMember):',
                '    def max_items(self):       return 10',
                '    def membership_type(self): return MembershipType.STAFF',
                '',
                'class PremiumMember(LibraryMember):',
                '    def max_items(self):       return 7',
                '    def membership_type(self): return MembershipType.PREMIUM',
                '',
                '    def return_item(self, item):',
                '        if item not in self._checked_out:',
                '            raise RuntimeError(f"Not checked out by {self._name}")',
                '        fee = item.checkin()',
                '        self._checked_out.remove(item)',
                '        discounted = fee * 0.5',
                '        if discounted > 0:',
                '            self._fine_balance += discounted',
                '            print(f"Premium discount: ${fee:.2f} → ${discounted:.2f}")',
                '        return discounted',
                '',
                'print("Member classes defined.")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 4,
              cellTitle: 'Library facade and full demo',
              prose:
                '`Library` is a facade — it coordinates between media and members and hides the complexity. ' +
                'It also provides search, available-items filtering, and a catalog summary. ' +
                'The demo exercises all features: checkouts, returns, search, limit enforcement, and catalog reporting.',
              code: [
                'class Library:',
                '    def __init__(self, name: str):',
                '        self.name = name',
                '        self._catalog:  Dict[str, LibraryMedia]  = {}',
                '        self._members:  Dict[str, LibraryMember] = {}',
                '        self._log: List[dict] = []',
                '',
                '    def add_item(self, item):   self._catalog[item.item_id] = item',
                '    def add_member(self, m):    self._members[m.member_id] = m',
                '',
                '    def checkout(self, member_id, item_id):',
                '        m = self._members[member_id]',
                '        item = self._catalog[item_id]',
                '        due = m.borrow(item)',
                '        self._log.append({"type": "checkout", "member": member_id, "item": item_id})',
                '        print(f"✓ {m.name} borrowed \'{item.title}\'. Due: {due.strftime(\'%Y-%m-%d\')}")',
                '        return due',
                '',
                '    def checkin(self, member_id, item_id):',
                '        m = self._members[member_id]',
                '        item = self._catalog[item_id]',
                '        fee = m.return_item(item)',
                '        self._log.append({"type": "checkin", "member": member_id, "item": item_id, "fee": fee})',
                '        msg = f"Late fee: ${fee:.2f}" if fee > 0 else "On time."',
                '        print(f"✓ \'{item.title}\' returned. {msg}")',
                '        return fee',
                '',
                '    def search(self, query, media_type=None):',
                '        q = query.lower()',
                '        return [',
                '            item for item in self._catalog.values()',
                '            if q in item.title.lower()',
                '            and (media_type is None or item.media_type() == media_type.upper())',
                '        ]',
                '',
                '    def available_items(self, media_type=None):',
                '        items = [i for i in self._catalog.values() if i.is_available]',
                '        return [i for i in items if not media_type or i.media_type() == media_type.upper()]',
                '',
                '    def catalog_summary(self):',
                '        print(f"\\n=== {self.name} — Catalog ===")',
                '        types = {}',
                '        for item in self._catalog.values():',
                '            t = item.media_type()',
                '            types.setdefault(t, {"total": 0, "available": 0})',
                '            types[t]["total"] += 1',
                '            if item.is_available: types[t]["available"] += 1',
                '        for t, c in sorted(types.items()):',
                '            print(f"  {t:10s} {c[\'available\']}/{c[\'total\']} available")',
                '        print(f"  Members: {len(self._members)}")',
                '',
                '',
                '# ---- DEMO ----',
                'lib = Library("City Public Library")',
                '',
                'lib.add_item(Book("B001", "Clean Code", "Robert Martin", "isbn", 2008, 464))',
                'lib.add_item(Book("B002", "The Pragmatic Programmer", "Hunt & Thomas", "isbn", 1999, 352))',
                'lib.add_item(EBook("E001", "Python Tricks", "Dan Bader", "isbn", 2017, 15.5))',
                'lib.add_item(DVD("D001", "Inception", "Nolan", 2010, 148))',
                'lib.add_item(DVD("D002", "The Matrix", "Wachowskis", 1999, 136))',
                'lib.add_item(Magazine("M001", "Science Today", "Issue 45", 2024, "March"))',
                '',
                'lib.add_member(StudentMember("S001", "Alice Johnson", "alice@uni.edu"))',
                'lib.add_member(StaffMember("ST001", "Dr. Bob Smith", "bob@uni.edu"))',
                'lib.add_member(PremiumMember("P001", "Carol White", "carol@gmail.com"))',
                '',
                'lib.catalog_summary()',
                '',
                'lib.checkout("S001",  "B001")',
                'lib.checkout("S001",  "E001")',
                'lib.checkout("ST001", "D001")',
                'lib.checkout("P001",  "B002")',
                '',
                'print()',
                'lib._members["S001"].status()',
                '',
                'lib.checkin("S001", "B001")',
                '',
                'print("\\n=== Search: Python ===")',
                'for item in lib.search("Python"):',
                '    print(f"  {item}")',
                '',
                'print("\\n=== Available Books ===")',
                'for item in lib.available_items("BOOK"):',
                '    print(f"  {item}")',
                '',
                '# Test student borrow limit (max 3)',
                'print("\\n=== Testing Borrow Limit ===")',
                'lib.checkout("S001", "M001")   # 2nd item',
                'lib.checkout("S001", "D002")   # 3rd item — at limit',
                'try:',
                '    lib.checkout("S001", "B002")  # 4th — should fail',
                'except RuntimeError as e:',
                '    print(f"Blocked as expected: {e}")',
                '',
                'lib.catalog_summary()',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: '`EBook` inherits from `Book`. Which OOP relationship does this represent?',
      options: [
        'HAS-A (composition)',
        'IS-A (inheritance) — an EBook is a Book with different checkout rules',
        'USES-A (dependency)',
      ],
      correct: 1,
    },
    {
      id: 'q2',
      type: 'choice',
      text: '`Library.checkout()` calls `member.borrow(item)` which calls `item.checkout(member_id)`. Which pattern is `Library` using?',
      options: [
        'Strategy — it swaps checkout algorithms',
        'Facade — it provides a simple interface over a complex subsystem',
        'Observer — it notifies subscribers when items are checked out',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'Why does `PremiumMember` override `return_item()` instead of changing `LibraryMember.return_item()`?',
      options: [
        'Because `LibraryMember` is abstract and cannot have method implementations',
        'To apply a 50% discount without changing behaviour for Student and Staff members',
        'Python requires all methods to be overridden in subclasses',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'Adding `AudioBook` as a new media type requires changes to:',
      options: [
        'Library, LibraryMember, and all existing media classes',
        'Only the new AudioBook class — the rest of the system is open for extension',
        'The checkout() and checkin() methods in LibraryMedia',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    'ABCs define contracts — LibraryMedia and LibraryMember enforce what every subtype must implement.',
    'Three abstract methods (checkout_duration, late_fee_per_day, media_type) are the polymorphic hooks.',
    'Base-class methods (checkout, checkin) call those hooks — one implementation works for all media types.',
    'PremiumMember overrides return_item() to customise behaviour without touching other member types.',
    'Library is a Facade — it hides the complexity of coordinating members, items, and transactions.',
    'Adding a new type means adding a class — not editing existing code (Open/Closed Principle).',
  ],

  checkpoints: ['read-intuition'],
}
