// PositionGraphPatternSpotter.jsx — shared for graph lessons
import { useState } from "react";
const ROUNDS=[
  {q:"A straight x–t line with positive slope means…",opts:["Constant acceleration","Constant velocity","Object at rest","Negative velocity"],correct:"Constant velocity",why:"Slope of x–t = velocity. Constant (non-zero) slope = constant velocity = zero acceleration."},
  {q:"An x–t graph curves upward (increasing slope). What is happening?",opts:["Constant velocity","Decelerating","Accelerating in +x","Moving backward"],correct:"Accelerating in +x",why:"Increasing slope = increasing velocity = positive acceleration."},
  {q:"A horizontal x–t line means the object is…",opts:["Moving at constant speed","Accelerating","At rest","Moving in a circle"],correct:"At rest",why:"Horizontal line → slope = 0 → v = 0. The position is not changing."},
  {q:"The v–t graph for constant acceleration is…",opts:["A curve","A horizontal line","A sloped straight line","A parabola"],correct:"A sloped straight line",why:"v = v₀ + at is linear in t. Slope = a (constant), so the graph is a straight line."},
  {q:"The area under a v–t curve from t₁ to t₂ gives you…",opts:["Average velocity","Displacement Δx","Distance","Acceleration"],correct:"Displacement Δx",why:"Δx = ∫v dt = area under v–t graph. This follows from the fundamental theorem of calculus."},
  {q:"A v–t graph crosses zero (changes sign). What physically happened?",opts:["Object stopped permanently","Object reversed direction","Acceleration became zero","Speed increased"],correct:"Object reversed direction",why:"v = 0 means instantaneous rest. Sign change means the object was moving in one direction, stopped, then moved the other way."},
];
export default function PositionGraphPatternSpotter({params={}}){
  const [r,setR]=useState(0);const [chosen,setChosen]=useState(null);const [revealed,setRevealed]=useState(false);const [score,setScore]=useState(0);const [done,setDone]=useState(false);const [history,setHistory]=useState([]);
  const q=ROUNDS[r];const C="#6366f1";
  function choose(opt){if(revealed)return;setChosen(opt);setRevealed(true);const ok=opt===q.correct;if(ok)setScore(s=>s+1);setHistory(h=>[...h,{q:q.q,correct:ok,answer:q.correct}]);}
  function next(){if(r+1>=ROUNDS.length)setDone(true);else{setR(n=>n+1);setChosen(null);setRevealed(false);}}
  function reset(){setR(0);setChosen(null);setRevealed(false);setScore(0);setDone(false);setHistory([]);}
  if(done)return(<div style={{fontFamily:"'DM Sans',system-ui,sans-serif",background:"#0f172a",borderRadius:16,padding:24}}><div style={{fontSize:13,color:C,fontWeight:700,marginBottom:12}}>MOTION GRAPH PATTERNS</div><div style={{fontSize:32,fontWeight:900,color:"#e2e8f0",marginBottom:16}}>{score}/{ROUNDS.length}</div><div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:20}}>{history.map((h,i)=><div key={i} style={{background:h.correct?"#0d2a1e":"#2a0d0d",borderRadius:8,padding:"8px 14px",borderLeft:`2px solid ${h.correct?"#10b981":"#f43f5e"}`}}><div style={{fontSize:12,color:"#64748b"}}>{h.q.substring(0,55)}</div><div style={{fontSize:12,fontWeight:700,color:h.correct?"#34d399":"#f87171"}}>{h.answer}</div></div>)}</div><button onClick={reset} style={{width:"100%",background:C,color:"#fff",border:"none",borderRadius:10,padding:12,fontSize:14,fontWeight:800,cursor:"pointer"}}>Try Again</button></div>);
  return(<div style={{fontFamily:"'DM Sans',system-ui,sans-serif",background:"#0f172a",borderRadius:16,overflow:"hidden"}}>
    <div style={{padding:"14px 20px",background:"#0c1122",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:13,color:C,fontWeight:700,letterSpacing:"0.08em"}}>PILLAR 3 · MOTION GRAPH PATTERNS</span><div style={{display:"flex",gap:5}}>{ROUNDS.map((_,i)=><div key={i} style={{width:7,height:7,borderRadius:"50%",background:i<r?"#10b981":i===r?C:"#1e293b"}}/>)}</div></div>
    <div style={{height:3,background:"#1e293b"}}><div style={{height:"100%",width:`${(r/ROUNDS.length)*100}%`,background:C,transition:"width 0.3s"}}/></div>
    <div style={{padding:"18px 20px 0"}}>
      <div style={{background:"#1e293b",borderRadius:12,padding:"18px",marginBottom:14,border:revealed?`2px solid ${chosen===q.correct?"#10b981":"#f43f5e"}`:"2px solid #334155"}}><div style={{fontSize:12,color:"#64748b",marginBottom:5}}>Round {r+1}/{ROUNDS.length}</div><div style={{fontSize:15,fontWeight:700,color:"#e2e8f0"}}>{q.q}</div></div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}>{q.opts.map(opt=>{const isC=opt===q.correct,isCh=opt===chosen;let bg="#1e293b",border="#334155",tc="#94a3b8";if(revealed){if(isC){bg="#0d2a1e";border="#10b981";tc="#34d399";}else if(isCh){bg="#2a0d0d";border="#f43f5e";tc="#f87171";}}return<button key={opt} onClick={()=>choose(opt)} style={{background:bg,border:`2px solid ${border}`,borderRadius:10,padding:"11px",fontSize:12,fontWeight:700,color:tc,cursor:revealed?"default":"pointer"}}>{opt}</button>;})}</div>
      {revealed&&<><div style={{background:chosen===q.correct?"#0d2a1e":"#2a0d0d",borderRadius:10,padding:"12px 16px",borderLeft:`3px solid ${chosen===q.correct?"#10b981":"#f43f5e"}`,marginBottom:12}}><div style={{fontSize:13,fontWeight:700,color:chosen===q.correct?"#34d399":"#f87171",marginBottom:4}}>{chosen===q.correct?"✓ Correct":"✗ "+q.correct}</div><div style={{fontSize:13,color:"#94a3b8",lineHeight:1.6}}>{q.why}</div></div><button onClick={next} style={{width:"100%",background:C,color:"#fff",border:"none",borderRadius:10,padding:12,fontSize:14,fontWeight:800,cursor:"pointer",marginBottom:20}}>{r+1>=ROUNDS.length?"Results →":"Next →"}</button></>}
    </div>
  </div>);
}
