export default {
  id: 'py-4-11-advanced-projects',
  slug: 'oop-advanced-projects',
  chapter: 4.11,
  order: 11,
  title: 'Advanced Projects: ORM and Event Pipeline',
  subtitle: 'Putting metaclasses, descriptors, and patterns together in real systems',
  tags: ['ORM', 'metaclass', 'descriptor', 'event bus', 'pipeline', 'method chaining', 'advanced'],

  hook: {
    question: 'How do frameworks like Django let you define a database model as a plain Python class — with no explicit `__init__`, automatic SQL generation, and built-in query methods?',
    realWorldContext:
      'An ORM (Object-Relational Mapper) is one of the most sophisticated uses of Python\'s OOP system. ' +
      'Django\'s `Model` class combines metaclasses (to collect field descriptors at class-definition time), ' +
      'descriptors (to validate and store field values), class methods (`objects.all()`, `objects.filter()`), ' +
      'and magic methods (`__repr__`, `__eq__`) into a seamless API. ' +
      'An event pipeline uses composition, method chaining, and the observer pattern to process data ' +
      'through a series of steps while keeping each step decoupled. ' +
      'These two projects demonstrate that everything in the OOP chapter is not academic — ' +
      'it is exactly how production Python frameworks are built.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      'The mini-ORM combines three techniques you have already seen. ' +
      '`Field` is a descriptor — it validates and stores values. ' +
      '`ModelMeta` is a metaclass — it inspects the class body at definition time and collects all `Field` instances into `_fields`. ' +
      '`Model` is the base class that provides `save()`, `all()`, and `find_by_id()` using those collected fields.',

      'Defining `name = Field(str)` at the class level is the same pattern as `age = RangeAttribute(0, 150)` from the descriptors lesson. ' +
      'The metaclass sees `Field` instances in the namespace and registers them. ' +
      'When you later write `user.name = "Alice"`, Python routes through `Field.__set__`, which validates the type.',

      'The event pipeline uses **method chaining** (`DataPipeline(...).load().transform().filter().output()`), ' +
      'an **event bus** (the Observer pattern from the design patterns lesson), ' +
      'and **composition** (the pipeline holds a bus, not inherits from it). ' +
      'Each step emits an event — logging, monitoring, or error handling can hook in without touching the pipeline code.',
    ],
    callouts: [
      {
        type: 'insight',
        title: 'These are not toy examples',
        body: 'The mini-ORM here follows the same architecture as Django\'s `models.Model`. The event pipeline follows the same architecture as Apache Kafka connectors and pandas pipelines. Understanding this code means you can read and contribute to real framework internals.',
      },
      {
        type: 'sequencing',
        title: 'Read the ORM in this order',
        body: '1. `Field` — understand the descriptor. 2. `ModelMeta` — understand how it collects fields. 3. `Model` — understand how save/find work. 4. `User`/`Product` — see how clean the user-facing API is as a result.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.11 — Advanced Projects',
        mathBridge: 'Run each cell and trace through the call chain. For the ORM, add print statements inside Field.__set__ to see when validation fires.',
        caption: 'Build a mini ORM using metaclasses and descriptors, and an event-driven data pipeline.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Mini ORM — Field descriptor',
              prose:
                '`Field` stores values under `_field_name` on the instance. ' +
                'It validates the type and will attempt a coercion before failing. ' +
                'Required fields raise `ValueError` if set to `None`. ' +
                '`__set_name__` is called by Python when the field is defined on the class body.',
              code: [
                'class Field:',
                '    """A descriptor for ORM model fields."""',
                '',
                '    def __init__(self, field_type, required=True, default=None, unique=False):',
                '        self.field_type = field_type',
                '        self.required = required',
                '        self.default = default',
                '        self.unique = unique',
                '        self.name = None',
                '',
                '    def __set_name__(self, owner, name):',
                '        self.name = name',
                '        self.private_name = f"_field_{name}"',
                '',
                '    def __get__(self, obj, objtype=None):',
                '        if obj is None: return self',
                '        return getattr(obj, self.private_name, self.default)',
                '',
                '    def __set__(self, obj, value):',
                '        if value is None:',
                '            if self.required and self.default is None:',
                '                raise ValueError(f"Field \'{self.name}\' is required")',
                '            value = self.default',
                '        elif not isinstance(value, self.field_type):',
                '            try:',
                '                value = self.field_type(value)   # attempt coercion',
                '            except (ValueError, TypeError):',
                '                raise TypeError(',
                '                    f"Field \'{self.name}\' expected {self.field_type.__name__}, "',
                '                    f"got {type(value).__name__}"',
                '                )',
                '        setattr(obj, self.private_name, value)',
                '',
                '',
                '# Test the descriptor alone',
                'class Demo:',
                '    name  = Field(str)',
                '    price = Field(float, default=0.0)',
                '',
                'd = Demo()',
                'd.name = "Widget"',
                'd.price = "9.99"   # string — auto-coerced to float',
                'print(d.name, d.price)',
                '',
                'try:',
                '    d.name = None',
                'except ValueError as e:',
                '    print(f"Error: {e}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'Mini ORM — ModelMeta metaclass and Model base class',
              prose:
                '`ModelMeta.__new__` scans the class body at definition time and collects every `Field` instance into `_fields`. ' +
                '`Model` uses `_fields` to build `__init__`, `save()`, `all()`, and `find_by_id()`. ' +
                'Notice how clean the `User` and `Product` definitions are — just field declarations.',
              code: [
                'class ModelMeta(type):',
                '    """Metaclass: collects Field descriptors at class-definition time."""',
                '',
                '    def __new__(mcs, name, bases, namespace):',
                '        fields = {}',
                '        for attr_name, attr_value in namespace.items():',
                '            if isinstance(attr_value, Field):',
                '                fields[attr_name] = attr_value',
                '        for base in bases:',
                '            if hasattr(base, "_fields"):',
                '                fields.update(base._fields)',
                '        namespace["_fields"] = fields',
                '        namespace["_table_name"] = name.lower() + "s"',
                '        return super().__new__(mcs, name, bases, namespace)',
                '',
                '',
                'class Model(metaclass=ModelMeta):',
                '    _database = {}',
                '',
                '    def __init__(self, **kwargs):',
                '        for field_name, field in self._fields.items():',
                '            value = kwargs.get(field_name, field.default)',
                '            if value is not None:',
                '                setattr(self, field_name, value)',
                '        self._id = None',
                '',
                '    def save(self):',
                '        import uuid',
                '        table = self.__class__._table_name',
                '        if table not in Model._database:',
                '            Model._database[table] = {}',
                '        if self._id is None:',
                '            self._id = str(uuid.uuid4())[:8]',
                '        Model._database[table][self._id] = self.to_dict()',
                '        return self',
                '',
                '    @classmethod',
                '    def all(cls):',
                '        results = []',
                '        for id, data in Model._database.get(cls._table_name, {}).items():',
                '            obj = cls(**data)',
                '            obj._id = id',
                '            results.append(obj)',
                '        return results',
                '',
                '    @classmethod',
                '    def find_by_id(cls, id):',
                '        data = Model._database.get(cls._table_name, {}).get(id)',
                '        if data:',
                '            obj = cls(**data)',
                '            obj._id = id',
                '            return obj',
                '        return None',
                '',
                '    def to_dict(self):',
                '        return {name: getattr(self, name) for name in self._fields}',
                '',
                '    def __repr__(self):',
                '        attrs = ", ".join(f"{k}={getattr(self, k)!r}" for k in self._fields)',
                '        return f"{self.__class__.__name__}({attrs})"',
                '',
                '',
                '# User-facing model definitions — just field declarations',
                'class User(Model):',
                '    name   = Field(str)',
                '    email  = Field(str, unique=True)',
                '    age    = Field(int)',
                '    active = Field(bool, default=True)',
                '',
                'class Product(Model):',
                '    title    = Field(str)',
                '    price    = Field(float)',
                '    category = Field(str, default="General")',
                '',
                '',
                'u1 = User(name="Alice", email="alice@example.com", age=30).save()',
                'u2 = User(name="Bob",   email="bob@example.com",   age=25).save()',
                'p1 = Product(title="Laptop", price=999.99, category="Electronics").save()',
                'p2 = Product(title="Book",   price=29.99).save()',
                '',
                'print("Users:", User.all())',
                'print("Products:", Product.all())',
                'print("Alice:", User.find_by_id(u1._id))',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'Event-driven data pipeline',
              prose:
                '`EventBus` lets functions register for named events. ' +
                '`DataPipeline` emits events at each step (`loaded`, `transformed`, `filtered`, `completed`). ' +
                'Listeners log what happened — but they are completely decoupled from the pipeline logic. ' +
                'Method chaining (each step returns `self`) produces a readable fluent API.',
              code: [
                'class EventBus:',
                '    def __init__(self):',
                '        self._listeners = {}',
                '',
                '    def on(self, event_name):',
                '        """Decorator to register a listener for an event."""',
                '        def decorator(func):',
                '            if event_name not in self._listeners:',
                '                self._listeners[event_name] = []',
                '            self._listeners[event_name].append(func)',
                '            return func',
                '        return decorator',
                '',
                '    def emit(self, event_name, *args, **kwargs):',
                '        for listener in self._listeners.get(event_name, []):',
                '            listener(*args, **kwargs)',
                '',
                '',
                'class DataPipeline:',
                '    def __init__(self, name: str, bus: EventBus):',
                '        self.name = name',
                '        self.bus = bus',
                '        self.data = []',
                '',
                '    def load(self, data: list):',
                '        self.data = list(data)',
                '        self.bus.emit("pipeline.loaded", self.name, len(self.data))',
                '        return self',
                '',
                '    def transform(self, func):',
                '        self.data = [func(item) for item in self.data]',
                '        self.bus.emit("pipeline.transformed", self.name, len(self.data))',
                '        return self',
                '',
                '    def filter(self, predicate):',
                '        before = len(self.data)',
                '        self.data = [x for x in self.data if predicate(x)]',
                '        self.bus.emit("pipeline.filtered", self.name, before - len(self.data))',
                '        return self',
                '',
                '    def output(self):',
                '        self.bus.emit("pipeline.completed", self.name, self.data)',
                '        return self.data',
                '',
                '',
                'bus = EventBus()',
                '',
                '@bus.on("pipeline.loaded")',
                'def on_loaded(name, count):',
                '    print(f"[{name}] Loaded {count} items")',
                '',
                '@bus.on("pipeline.transformed")',
                'def on_transformed(name, count):',
                '    print(f"[{name}] Transformed {count} items")',
                '',
                '@bus.on("pipeline.filtered")',
                'def on_filtered(name, removed):',
                '    print(f"[{name}] Filtered out {removed} items")',
                '',
                '@bus.on("pipeline.completed")',
                'def on_completed(name, data):',
                '    print(f"[{name}] Done — {len(data)} items remain")',
                '',
                '',
                'result = (',
                '    DataPipeline("squares", bus)',
                '    .load(range(1, 11))',
                '    .transform(lambda x: x ** 2)',
                '    .filter(lambda x: x > 25)',
                '    .output()',
                ')',
                '',
                'print(f"Result: {result}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: 'In the mini-ORM, what role does `ModelMeta.__new__` play?',
      options: [
        'It validates field values when you write `user.name = "Alice"`',
        'It scans the class body at definition time and collects all Field instances into `_fields`',
        'It generates SQL queries for saving to a real database',
      ],
      correct: 1,
    },
    {
      id: 'q2',
      type: 'choice',
      text: 'In the ORM, when you write `user.name = "Alice"`, which object\'s `__set__` is called?',
      options: [
        '`Model.__set__`',
        '`Field.__set__`',
        '`ModelMeta.__set__`',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'What pattern does `DataPipeline.load().transform().filter().output()` use?',
      options: [
        'Observer pattern',
        'Method chaining — each step returns `self`',
        'Strategy pattern',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'Why is the event listener code completely decoupled from `DataPipeline`?',
      options: [
        'The pipeline inherits from EventBus, so listeners use inheritance',
        'The pipeline emits events through the bus — it doesn\'t know or care who is listening',
        'Listeners are hard-coded inside each pipeline method',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    'The mini-ORM combines three patterns: Field (descriptor), ModelMeta (metaclass), Model (base class with query methods).',
    'Metaclass collects descriptors at class-definition time — this is how Django models work.',
    'Field.__set__ validates on every assignment — including inside __init__.',
    'EventBus (Observer): emit events without knowing who is listening.',
    'DataPipeline uses method chaining — each step returns self — for a fluent API.',
    'These are production-grade patterns used in Django, SQLAlchemy, and pandas.',
  ],

  checkpoints: ['read-intuition'],
}
