export default {
  id: 'py-4-9-design-patterns',
  slug: 'oop-design-patterns',
  chapter: 4.1,
  order: 9,
  title: 'Design Patterns',
  subtitle: 'Proven blueprints for common software design problems',
  tags: ['factory', 'abstract factory', 'decorator pattern', 'observer', 'strategy', 'design patterns', 'creational', 'behavioural'],

  hook: {
    question: 'When you face a recurring design problem — how do you create objects flexibly, add behaviour without subclassing, or decouple components that need to communicate?',
    realWorldContext:
      'Design patterns are **named, proven solutions** to problems that appear over and over in software. ' +
      'They were catalogued by the "Gang of Four" in 1994 and remain the common vocabulary of software design. ' +
      'In Python, patterns often look simpler than in Java/C++ because of first-class functions and duck typing — ' +
      'but the underlying ideas are identical. ' +
      'The **Factory** centralises object creation. The **Decorator** wraps objects to add behaviour at runtime. ' +
      'The **Observer** decouples producers from consumers. The **Strategy** makes algorithms swappable at runtime. ' +
      'Recognising these patterns in code you read is just as valuable as knowing how to write them.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      'The **Factory Method** pattern centralises the decision of which class to instantiate. ' +
      'Callers ask for "a Dog" without caring which concrete `Dog` subclass they get. ' +
      'The factory holds the registry and does the lookup. Adding a new type means registering it — not editing call sites.',

      'The **Decorator pattern** (different from Python\'s `@decorator` syntax) wraps an object in another object that adds behaviour. ' +
      'Each wrapper delegates to the inner object and adds something extra. ' +
      'You can stack as many decorators as you want: `VanillaShot(Sugar(Milk(Coffee())))`. ' +
      'This is composition, not inheritance — no subclass explosion.',

      'The **Observer pattern** defines a one-to-many relationship: when one object changes state, ' +
      'all registered observers are notified automatically. ' +
      'The publisher (subject) knows nothing about its subscribers — it just fires events. ' +
      'This is the foundation of event-driven systems, React\'s state model, and GUI frameworks.',

      'The **Strategy pattern** defines a family of algorithms, encapsulates each one in a class, ' +
      'and makes them interchangeable. The context class holds a reference to a strategy and delegates to it. ' +
      'Swapping the strategy at runtime changes behaviour without touching the context.',
    ],
    callouts: [
      {
        type: 'insight',
        title: 'The Decorator pattern vs Python decorator syntax',
        body: 'Python\'s `@decorator` syntax wraps functions, not objects. The Gang of Four Decorator pattern wraps objects via composition to add behaviour at runtime. Both use the word "decorator" but solve different problems. The pattern shown here (wrapping Coffee objects) is the GoF structural pattern.',
      },
      {
        type: 'sequencing',
        title: 'Creational → Structural → Behavioural',
        body: 'Design patterns split into three families. Creational (Factory, Singleton, Builder) control how objects are made. Structural (Decorator, Adapter, Proxy) control how objects are composed. Behavioural (Observer, Strategy, Command, Iterator) control how objects communicate.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.9 — Design Patterns',
        mathBridge: 'For each pattern, identify: what problem it solves, and what the alternative would look like without it.',
        caption: 'Implement Factory, Abstract Factory, Decorator, Observer, and Strategy patterns in Python.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Factory Method — centralised object creation',
              prose:
                '`AnimalFactory.create("dog")` returns a `Dog` instance without the caller knowing or caring about the class. ' +
                'The `_registry` dict maps string names to classes. ' +
                '`register()` lets you add new types without modifying the factory — the Open/Closed Principle in action.',
              code: [
                'class Animal:',
                '    def speak(self): raise NotImplementedError',
                '',
                'class Dog(Animal):',
                '    def speak(self): return "Woof!"',
                '',
                'class Cat(Animal):',
                '    def speak(self): return "Meow!"',
                '',
                'class Bird(Animal):',
                '    def speak(self): return "Tweet!"',
                '',
                '',
                'class AnimalFactory:',
                '    _registry = {"dog": Dog, "cat": Cat, "bird": Bird}',
                '',
                '    @classmethod',
                '    def create(cls, animal_type: str) -> Animal:',
                '        klass = cls._registry.get(animal_type.lower())',
                '        if klass is None:',
                '            raise ValueError(f"Unknown animal: {animal_type}")',
                '        return klass()',
                '',
                '    @classmethod',
                '    def register(cls, name: str, klass):',
                '        """Add a new type without modifying existing code."""',
                '        cls._registry[name.lower()] = klass',
                '',
                '',
                'for animal_type in ["dog", "cat", "bird"]:',
                '    animal = AnimalFactory.create(animal_type)',
                '    print(f"{animal.__class__.__name__}: {animal.speak()}")',
                '',
                '# Extend without modifying the factory',
                'class Parrot(Animal):',
                '    def speak(self): return "Polly wants a cracker!"',
                '',
                'AnimalFactory.register("parrot", Parrot)',
                'print(AnimalFactory.create("parrot").speak())',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'Abstract Factory — families of related objects',
              prose:
                'The Abstract Factory creates **families** of related objects without specifying their concrete classes. ' +
                '`WindowsFactory` creates Windows-styled UI components. `MacFactory` creates Mac-styled ones. ' +
                '`build_ui()` works with any factory — it never references `Windows` or `Mac` directly. ' +
                'Swap the factory and you swap the entire family of objects.',
              code: [
                'from abc import ABC, abstractmethod',
                '',
                '',
                'class Button(ABC):',
                '    @abstractmethod',
                '    def render(self): pass',
                '    @abstractmethod',
                '    def on_click(self): pass',
                '',
                'class WindowsButton(Button):',
                '    def render(self): return "[ Windows Button ]"',
                '    def on_click(self): return "Windows click: beep"',
                '',
                'class MacButton(Button):',
                '    def render(self): return "◉ Mac Button ◉"',
                '    def on_click(self): return "Mac click: pop"',
                '',
                '',
                'class Checkbox(ABC):',
                '    @abstractmethod',
                '    def render(self): pass',
                '',
                'class WindowsCheckbox(Checkbox):',
                '    def render(self): return "[✓] Windows Checkbox"',
                '',
                'class MacCheckbox(Checkbox):',
                '    def render(self): return "☑ Mac Checkbox"',
                '',
                '',
                'class GUIFactory(ABC):',
                '    @abstractmethod',
                '    def create_button(self) -> Button: pass',
                '    @abstractmethod',
                '    def create_checkbox(self) -> Checkbox: pass',
                '',
                'class WindowsFactory(GUIFactory):',
                '    def create_button(self): return WindowsButton()',
                '    def create_checkbox(self): return WindowsCheckbox()',
                '',
                'class MacFactory(GUIFactory):',
                '    def create_button(self): return MacButton()',
                '    def create_checkbox(self): return MacCheckbox()',
                '',
                '',
                'def build_ui(factory: GUIFactory):',
                '    btn = factory.create_button()',
                '    chk = factory.create_checkbox()',
                '    print(btn.render())',
                '    print(chk.render())',
                '    print(btn.on_click())',
                '',
                'print("=== Windows UI ===")',
                'build_ui(WindowsFactory())',
                'print("\\n=== Mac UI ===")',
                'build_ui(MacFactory())',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'Decorator pattern — stack behaviour at runtime',
              prose:
                '`CoffeeDecorator` wraps a `Coffee` object and delegates to it. ' +
                'Each concrete decorator (`Milk`, `Sugar`, `VanillaShot`) overrides `description()` and `cost()` ' +
                'to add its own contribution before delegating to the wrapped object. ' +
                'You can stack any combination in any order — no subclass for every possible combination.',
              code: [
                'class Coffee:',
                '    def description(self): return "Basic coffee"',
                '    def cost(self): return 1.00',
                '',
                '',
                'class CoffeeDecorator(Coffee):',
                '    """Base decorator — wraps any Coffee object."""',
                '    def __init__(self, coffee: Coffee):',
                '        self._coffee = coffee',
                '    def description(self): return self._coffee.description()',
                '    def cost(self): return self._coffee.cost()',
                '',
                '',
                'class Milk(CoffeeDecorator):',
                '    def description(self): return self._coffee.description() + ", milk"',
                '    def cost(self): return self._coffee.cost() + 0.25',
                '',
                'class Sugar(CoffeeDecorator):',
                '    def description(self): return self._coffee.description() + ", sugar"',
                '    def cost(self): return self._coffee.cost() + 0.10',
                '',
                'class VanillaShot(CoffeeDecorator):',
                '    def description(self): return self._coffee.description() + ", vanilla"',
                '    def cost(self): return self._coffee.cost() + 0.75',
                '',
                '',
                '# Stack decorators — order does not matter for the totals',
                'order = VanillaShot(Sugar(Milk(Coffee())))',
                'print(order.description())',
                'print(f"${order.cost():.2f}")',
                '',
                '# A different combination',
                'plain_milk = Milk(Milk(Coffee()))  # double milk',
                'print(plain_milk.description())',
                'print(f"${plain_milk.cost():.2f}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 4,
              cellTitle: 'Observer pattern — event-driven communication',
              prose:
                '`Event` is a simple subscription list. Any function can subscribe. ' +
                '`StockMarket` fires events when price changes — `price_changed` always, ' +
                '`price_crashed` or `price_surged` when thresholds are hit. ' +
                'The stock knows nothing about who is listening — full decoupling between publisher and subscriber.',
              code: [
                'class Event:',
                '    """A subscribable event — call fire() to notify all subscribers."""',
                '',
                '    def __init__(self):',
                '        self._subscribers = []',
                '',
                '    def subscribe(self, callback):',
                '        self._subscribers.append(callback)',
                '        return callback  # lets it be used as a decorator',
                '',
                '    def fire(self, *args, **kwargs):',
                '        for sub in self._subscribers:',
                '            sub(*args, **kwargs)',
                '',
                '',
                'class StockMarket:',
                '    def __init__(self, symbol, price):',
                '        self.symbol = symbol',
                '        self._price = price',
                '        self.price_changed = Event()',
                '        self.price_crashed = Event()',
                '        self.price_surged  = Event()',
                '',
                '    @property',
                '    def price(self): return self._price',
                '',
                '    @price.setter',
                '    def price(self, new_price):',
                '        old = self._price',
                '        self._price = new_price',
                '        pct = (new_price - old) / old * 100',
                '        self.price_changed.fire(self.symbol, old, new_price, pct)',
                '        if pct <= -10: self.price_crashed.fire(self.symbol, pct)',
                '        elif pct >= 10: self.price_surged.fire(self.symbol, pct)',
                '',
                '',
                'apple = StockMarket("AAPL", 150.00)',
                '',
                '@apple.price_changed.subscribe',
                'def log_change(symbol, old, new, pct):',
                '    print(f"[LOG] {symbol}: ${old:.2f} → ${new:.2f} ({pct:+.1f}%)")',
                '',
                '@apple.price_crashed.subscribe',
                'def alert_crash(symbol, pct):',
                '    print(f"CRASH ALERT: {symbol} dropped {pct:.1f}%!")',
                '',
                '@apple.price_surged.subscribe',
                'def alert_surge(symbol, pct):',
                '    print(f"SURGE ALERT: {symbol} jumped {pct:.1f}%!")',
                '',
                'apple.price = 155.00   # small rise',
                'apple.price = 170.00   # +9.7% surge',
                'apple.price = 153.00   # -10% crash',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 5,
              cellTitle: 'Strategy pattern — swappable algorithms',
              prose:
                '`SortStrategy` is an ABC defining the interface. `BubbleSort`, `QuickSort`, and `PythonBuiltinSort` ' +
                'are concrete strategies. `Sorter` is the context — it holds a strategy and delegates to it. ' +
                'Changing `sorter.strategy` at runtime swaps the entire algorithm with no other changes.',
              code: [
                'from abc import ABC, abstractmethod',
                '',
                '',
                'class SortStrategy(ABC):',
                '    @abstractmethod',
                '    def sort(self, data: list) -> list: pass',
                '',
                '',
                'class BubbleSort(SortStrategy):',
                '    def sort(self, data):',
                '        data = data.copy()',
                '        n = len(data)',
                '        for i in range(n):',
                '            for j in range(n - i - 1):',
                '                if data[j] > data[j+1]:',
                '                    data[j], data[j+1] = data[j+1], data[j]',
                '        return data',
                '',
                '',
                'class QuickSort(SortStrategy):',
                '    def sort(self, data):',
                '        if len(data) <= 1: return data',
                '        pivot = data[len(data) // 2]',
                '        left   = [x for x in data if x < pivot]',
                '        middle = [x for x in data if x == pivot]',
                '        right  = [x for x in data if x > pivot]',
                '        return self.sort(left) + middle + self.sort(right)',
                '',
                '',
                'class PythonBuiltinSort(SortStrategy):',
                '    def sort(self, data): return sorted(data)',
                '',
                '',
                'class Sorter:',
                '    """Context — delegates sorting to whatever strategy is set."""',
                '    def __init__(self, strategy: SortStrategy):',
                '        self._strategy = strategy',
                '',
                '    @property',
                '    def strategy(self): return self._strategy',
                '',
                '    @strategy.setter',
                '    def strategy(self, s): self._strategy = s',
                '',
                '    def sort(self, data): return self._strategy.sort(data)',
                '',
                '',
                'data = [64, 34, 25, 12, 22, 11, 90]',
                '',
                'sorter = Sorter(BubbleSort())',
                'print("Bubble:", sorter.sort(data))',
                '',
                'sorter.strategy = QuickSort()       # swap at runtime',
                'print("Quick: ", sorter.sort(data))',
                '',
                'sorter.strategy = PythonBuiltinSort()',
                'print("Python:", sorter.sort(data))',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: 'The Factory pattern\'s main benefit is:',
      options: [
        'Making classes faster by caching instances',
        'Centralising object creation so callers don\'t depend on concrete class names',
        'Ensuring only one instance of a class exists',
      ],
      correct: 1,
    },
    {
      id: 'q2',
      type: 'choice',
      text: 'The GoF Decorator pattern adds behaviour by:',
      options: [
        'Subclassing the original class and overriding methods',
        'Wrapping an object in another object of the same interface via composition',
        'Using Python\'s `@decorator` syntax to modify a function',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'In the Observer pattern, what does the publisher (subject) know about its subscribers?',
      options: [
        'It knows their exact class types so it can call them directly',
        'Nothing — it only knows they have a callable interface. Full decoupling.',
        'It stores a strong reference to each subscriber class',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'The Strategy pattern makes algorithms interchangeable by:',
      options: [
        'Storing all algorithms as methods on one large class',
        'Encapsulating each algorithm in a class behind a shared interface, injected into a context',
        'Using if/elif chains to select the algorithm at runtime',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    'Factory: centralise object creation — callers ask for a type by name, not by class.',
    'Abstract Factory: create families of related objects through a shared factory interface.',
    'Decorator (GoF): wrap an object in another of the same interface — stack behaviour via composition.',
    'Observer: publisher fires events; subscribers register callbacks — complete decoupling.',
    'Strategy: encapsulate an algorithm in a class; swap it in the context at runtime.',
    'Patterns are a vocabulary — recognise them in code you read, not just write.',
  ],

  checkpoints: ['read-intuition'],
}
