export default {
  id: 'py-4-5-polymorphism-magic-methods',
  slug: 'oop-polymorphism',
  chapter: 4.5,
  order: 5,
  title: 'Polymorphism, Magic Methods, and Protocols',
  subtitle: 'One interface, many forms — and making your classes feel like built-ins',
  tags: ['polymorphism', 'duck typing', 'ABC', 'abstractmethod', 'magic methods', 'dunder', 'context manager', '__call__'],

  hook: {
    question: 'How do Python\'s built-in operators like `+`, `len()`, and `with` work on your own classes?',
    realWorldContext:
      'Polymorphism is the OOP principle that lets one function work on many types. ' +
      'In Python, it comes in two flavours: **inheritance-based** (subclasses override a shared method) ' +
      'and **duck typing** (any object with the right methods works, regardless of lineage). ' +
      'Magic methods (called "dunder methods" for their double underscores) are the hooks that ' +
      'let Python\'s operators and built-ins call into your classes. ' +
      'Define `__add__` and the `+` operator works. Define `__enter__` and `__exit__` and `with` works. ' +
      'Define `__len__` and `len()` works. This is how the entire Python data model is built — ' +
      'and how your classes can participate in it fully.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      '**Polymorphism through overriding** means different subclasses implement the same method name differently. ' +
      'A function that calls `shape.area()` works equally well on `Circle`, `Rectangle`, and `Triangle` — ' +
      'each one delivers its own version. The caller never needs to inspect the type.',

      '**Duck typing** takes this further: Python does not require shared inheritance. ' +
      'If an object has a `speak()` method, any function that calls `obj.speak()` will work — ' +
      'whether `obj` is a `Duck`, a `Person`, or a `Robot`. ' +
      '"If it walks like a duck and quacks like a duck, it\'s a duck."',

      '**Abstract Base Classes** (from the `abc` module) let you formalise the contract. ' +
      'Marking methods with `@abstractmethod` means Python will raise `TypeError` if a subclass ' +
      'fails to implement them. You get the documentation and enforcement of an interface ' +
      'without a separate `interface` keyword.',

      '**Magic methods** are how Python objects participate in the language\'s syntax. ' +
      '`__add__` powers `+`, `__len__` powers `len()`, `__eq__` powers `==`, ' +
      '`__enter__`/`__exit__` power `with`, and `__call__` makes any object callable like a function. ' +
      'Defining these methods is how you make your class feel like a first-class citizen of Python.',
    ],
    callouts: [
      {
        type: 'insight',
        title: 'Prefer duck typing over isinstance checks',
        body: 'Writing `if isinstance(obj, Dog)` is a code smell in polymorphic code. If the object has the method you need, just call it. Let the AttributeError tell you when something is missing. This makes your code more general and easier to extend.',
      },
      {
        type: 'warning',
        title: 'If you define __eq__, you must also define __hash__',
        body: 'Python automatically removes `__hash__` from any class where you define `__eq__`, making instances unhashable (they can\'t go in sets or be dict keys). Restore it with `__hash__ = None` to make the unhashability explicit, or define a real `__hash__` if your objects should be hashable.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.5 — Polymorphism, Magic Methods, and Protocols',
        mathBridge: 'Predict each output before running. Focus on which method Python is invoking for each operation.',
        caption: 'Build a shape hierarchy, explore duck typing, use ABCs, and write a full Vector class with dunder methods.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Polymorphism through method overriding — Shape hierarchy',
              prose:
                'Each subclass overrides `area()` and `perimeter()` with its own formula. ' +
                'The `describe()` method on the base class calls `self.area()` — which version runs depends ' +
                'on the actual type of the object at runtime. This is **runtime polymorphism**: ' +
                'the same line of code does different things depending on the concrete class.',
              code: [
                'import math',
                '',
                'class Shape:',
                '    def __init__(self, color="white"):',
                '        self.color = color',
                '',
                '    def area(self):',
                '        raise NotImplementedError("Subclasses must implement area()")',
                '',
                '    def perimeter(self):',
                '        raise NotImplementedError("Subclasses must implement perimeter()")',
                '',
                '    def describe(self):',
                '        print(f"{self.__class__.__name__} ({self.color}):")',
                '        print(f"  Area:      {self.area():.4f}")',
                '        print(f"  Perimeter: {self.perimeter():.4f}")',
                '',
                '',
                'class Circle(Shape):',
                '    def __init__(self, radius, color="white"):',
                '        super().__init__(color)',
                '        self.radius = radius',
                '',
                '    def area(self):',
                '        return math.pi * self.radius ** 2',
                '',
                '    def perimeter(self):',
                '        return 2 * math.pi * self.radius',
                '',
                '',
                'class Rectangle(Shape):',
                '    def __init__(self, width, height, color="white"):',
                '        super().__init__(color)',
                '        self.width = width',
                '        self.height = height',
                '',
                '    def area(self):',
                '        return self.width * self.height',
                '',
                '    def perimeter(self):',
                '        return 2 * (self.width + self.height)',
                '',
                '',
                'class Triangle(Shape):',
                '    def __init__(self, a, b, c, color="white"):',
                '        super().__init__(color)',
                '        self.a, self.b, self.c = a, b, c',
                '',
                '    def area(self):',
                '        s = self.perimeter() / 2',
                '        return (s * (s-self.a) * (s-self.b) * (s-self.c)) ** 0.5',
                '',
                '    def perimeter(self):',
                '        return self.a + self.b + self.c',
                '',
                '',
                'shapes = [Circle(5, "red"), Rectangle(4, 6, "blue"), Triangle(3, 4, 5, "green")]',
                '',
                'for shape in shapes:',
                '    shape.describe()  # same call, different output per type',
                '    print()',
                '',
                'total = sum(s.area() for s in shapes)',
                'print(f"Total area: {total:.2f}")',
                'largest = max(shapes, key=lambda s: s.area())',
                'print(f"Largest: {largest.__class__.__name__}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'Duck typing — no inheritance required',
              prose:
                '`make_walk_and_speak()` calls `entity.walk()` and `entity.speak()`. ' +
                '`Duck`, `Person`, and `Robot` share no common parent — they are completely unrelated classes. ' +
                'Python does not care. If the object has the methods, the call succeeds. ' +
                'This is duck typing: the interface is implicit, not declared.',
              code: [
                'class Duck:',
                '    def speak(self): return "Quack!"',
                '    def walk(self):  return "Waddle waddle"',
                '',
                '',
                'class Person:',
                '    def speak(self): return "Hello!"',
                '    def walk(self):  return "Step step"',
                '',
                '',
                'class Robot:',
                '    def speak(self): return "BEEP BOOP"',
                '    def walk(self):  return "Clank clank"',
                '',
                '',
                'def make_walk_and_speak(entity):',
                '    """Works on any object with speak() and walk() — no isinstance check needed."""',
                '    print(f"{entity.__class__.__name__}: {entity.walk()} — {entity.speak()}")',
                '',
                '',
                'for thing in [Duck(), Person(), Robot()]:',
                '    make_walk_and_speak(thing)',
                '',
                '# Operator polymorphism is duck typing too:',
                '# + calls __add__ — each type implements it differently',
                'print(1 + 2)               # 3        — int.__add__',
                'print("hello" + " world")  # hello world — str.__add__',
                'print([1, 2] + [3, 4])     # [1, 2, 3, 4] — list.__add__',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'Abstract Base Classes — formalising the contract',
              prose:
                'Import `ABC` and `abstractmethod` from the `abc` module. ' +
                'Inheriting from `ABC` and marking methods with `@abstractmethod` means Python will refuse ' +
                'to instantiate any class that does not implement every abstract method. ' +
                '`Animal` here cannot be created directly — it is a template that enforces a contract. ' +
                'Concrete subclasses (`Dog`, `Bird`, `Fish`) satisfy the contract and can be instantiated.',
              code: [
                'from abc import ABC, abstractmethod',
                '',
                '',
                'class Animal(ABC):',
                '    def __init__(self, name, age):',
                '        self.name = name',
                '        self.age = age',
                '',
                '    @abstractmethod',
                '    def speak(self):',
                '        """All animals must implement speak()."""',
                '        pass',
                '',
                '    @abstractmethod',
                '    def move(self):',
                '        """All animals must implement move()."""',
                '        pass',
                '',
                '    def breathe(self):',
                '        print(f"{self.name} breathes.")',
                '',
                '    def describe(self):',
                '        print(f"I am {self.name}, I say \'{self.speak()}\' and I move by: {self.move()}")',
                '',
                '',
                'try:',
                '    a = Animal("Generic", 5)',
                'except TypeError as e:',
                '    print(f"Cannot instantiate: {e}")',
                '',
                '',
                'class Dog(Animal):',
                '    def speak(self): return "Woof!"',
                '    def move(self):  return "running on four legs"',
                '',
                '',
                'class Bird(Animal):',
                '    def speak(self): return "Tweet!"',
                '    def move(self):  return "flying with wings"',
                '',
                '',
                'class Fish(Animal):',
                '    def speak(self): return "..."',
                '    def move(self):  return "swimming with fins"',
                '',
                '',
                'for animal in [Dog("Rex", 3), Bird("Tweety", 1), Fish("Nemo", 2)]:',
                '    animal.describe()',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 4,
              cellTitle: 'Magic methods — the Vector class (arithmetic and comparison)',
              prose:
                'Magic methods map directly to Python operators. `__add__` handles `v1 + v2`. ' +
                '`__mul__` handles `v * 3` and `__rmul__` handles `3 * v` (when the left operand doesn\'t know how). ' +
                '`__abs__` handles `abs(v)` (the magnitude). `__eq__` handles `==`. ' +
                'Returning `NotImplemented` (not raising it) tells Python to try the reflected operation on the other operand.',
              code: [
                'class Vector:',
                '    def __init__(self, x, y):',
                '        self.x = x',
                '        self.y = y',
                '',
                '    def __repr__(self):',
                '        return f"Vector({self.x!r}, {self.y!r})"',
                '',
                '    def __str__(self):',
                '        return f"<{self.x}, {self.y}>"',
                '',
                '    def __add__(self, other):',
                '        if isinstance(other, Vector):',
                '            return Vector(self.x + other.x, self.y + other.y)',
                '        return NotImplemented',
                '',
                '    def __sub__(self, other):',
                '        if isinstance(other, Vector):',
                '            return Vector(self.x - other.x, self.y - other.y)',
                '        return NotImplemented',
                '',
                '    def __mul__(self, scalar):',
                '        if isinstance(scalar, (int, float)):',
                '            return Vector(self.x * scalar, self.y * scalar)',
                '        return NotImplemented',
                '',
                '    def __rmul__(self, scalar):',
                '        return self.__mul__(scalar)  # commutative',
                '',
                '    def __neg__(self):',
                '        return Vector(-self.x, -self.y)',
                '',
                '    def __abs__(self):',
                '        return (self.x**2 + self.y**2) ** 0.5',
                '',
                '    def __eq__(self, other):',
                '        if isinstance(other, Vector):',
                '            return self.x == other.x and self.y == other.y',
                '        return NotImplemented',
                '',
                '    def __hash__(self):',
                '        return hash((self.x, self.y))',
                '',
                '',
                'v1 = Vector(2, 3)',
                'v2 = Vector(1, -1)',
                '',
                'print(v1)           # <2, 3>',
                'print(repr(v1))     # Vector(2, 3)',
                'print(v1 + v2)      # <3, 2>',
                'print(v1 - v2)      # <1, 4>',
                'print(v1 * 3)       # <6, 9>',
                'print(3 * v1)       # <6, 9>  — __rmul__',
                'print(-v1)          # <-2, -3>',
                'print(abs(v1))      # 3.605...',
                'print(v1 == Vector(2, 3))  # True',
                '',
                '# Hashable — usable in sets and dicts',
                'vs = {Vector(1, 2), Vector(3, 4), Vector(1, 2)}',
                'print(len(vs))      # 2 — duplicate removed',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 5,
              cellTitle: 'Context managers — __enter__ and __exit__',
              prose:
                'The `with` statement calls `__enter__` on entry and `__exit__` on exit — even if an exception occurs. ' +
                '`__enter__` should return the resource to bind to the `as` variable. ' +
                '`__exit__` receives exception info (`exc_type`, `exc_val`, `exc_tb`) — return `True` to suppress the exception, ' +
                '`False` or `None` to propagate it. Context managers guarantee cleanup no matter what happens in the `with` block.',
              code: [
                'class DatabaseConnection:',
                '    def __init__(self, host, port=5432):',
                '        self.host = host',
                '        self.port = port',
                '        self.is_connected = False',
                '',
                '    def __enter__(self):',
                '        """Called on entering \'with\' block. Return the resource."""',
                '        print(f"Connecting to {self.host}:{self.port}...")',
                '        self.is_connected = True',
                '        print("Connection established.")',
                '        return self  # bound to \'as db\' variable',
                '',
                '    def __exit__(self, exc_type, exc_val, exc_tb):',
                '        """Called on leaving \'with\' block — even if exception occurred."""',
                '        if exc_type is not None:',
                '            print(f"An error occurred: {exc_val}")',
                '        print("Closing connection...")',
                '        self.is_connected = False',
                '        print("Connection closed.")',
                '        return False  # do not suppress exceptions',
                '',
                '    def query(self, sql):',
                '        if not self.is_connected:',
                '            raise RuntimeError("Not connected!")',
                '        print(f"Executing: {sql}")',
                '        return [{"id": 1, "name": "Alice"}]',
                '',
                '',
                'with DatabaseConnection("localhost") as db:',
                '    results = db.query("SELECT * FROM users")',
                '    print(f"Got {len(results)} results")',
                '# __exit__ called here automatically',
                '',
                'print(f"After with: connected = {db.is_connected}")  # False',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 6,
              cellTitle: '__call__ — making objects callable like functions',
              prose:
                '`__call__` is invoked when you use parentheses on an object: `obj(args)`. ' +
                'This makes objects behave like functions while still carrying state between calls. ' +
                '`Multiplier(2)` creates an object; calling it with `double(5)` invokes `__call__`. ' +
                '`Accumulator` is a callable that keeps a running total — something a plain function cannot do ' +
                'without global variables or closures.',
              code: [
                'class Multiplier:',
                '    """A callable that multiplies its argument by a fixed factor."""',
                '',
                '    def __init__(self, factor):',
                '        self.factor = factor',
                '',
                '    def __call__(self, value):',
                '        return value * self.factor',
                '',
                '',
                'double = Multiplier(2)',
                'triple = Multiplier(3)',
                '',
                'print(double(5))      # 10 — calls double.__call__(5)',
                'print(triple(5))      # 15',
                'print(callable(double))  # True',
                '',
                '',
                'class Accumulator:',
                '    """Callable that keeps a running total."""',
                '',
                '    def __init__(self):',
                '        self.total = 0',
                '        self.calls = 0',
                '',
                '    def __call__(self, value):',
                '        self.total += value',
                '        self.calls += 1',
                '        return self.total',
                '',
                '',
                'acc = Accumulator()',
                'print(acc(10))   # 10',
                'print(acc(20))   # 30',
                'print(acc(5))    # 35',
                'print(f"Called {acc.calls} times, total = {acc.total}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: 'A function calls `obj.fly()`. The object is not a `Bird` subclass — it is a completely unrelated class with a `fly()` method. What happens?',
      options: [
        'Python raises TypeError — the object must inherit from a common base to be used this way',
        'The call succeeds — Python uses duck typing and only cares that the method exists',
        'Python raises AttributeError — inheritance is required for method lookup',
      ],
      correct: 1,
    },
    {
      id: 'q2',
      type: 'choice',
      text: 'What happens if you try to instantiate an Abstract Base Class that has unimplemented `@abstractmethod` methods?',
      options: [
        'The class instantiates fine — abstract methods are just documentation',
        'Python raises TypeError at instantiation time',
        'Python raises AttributeError when the abstract method is called',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'You write `3 * v` where `v` is a Vector. Python first tries `int.__mul__(3, v)` which returns `NotImplemented`. What happens next?',
      options: [
        'Python raises TypeError immediately',
        'Python tries `v.__rmul__(3)` — the reflected operation on the right operand',
        'Python converts 3 to a Vector and retries',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'What is `__exit__` guaranteed to be called, regardless of whether an exception occurred?',
      options: [
        'Only when the `with` block completes without exceptions',
        'Always — whether the block completed normally or raised an exception',
        'Only when you explicitly call `exit()` inside the block',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    'Polymorphism: the same method call does different things depending on the runtime type of the object.',
    'Duck typing: if an object has the required methods, it can be used — no inheritance needed.',
    'Abstract Base Classes (`ABC` + `@abstractmethod`) enforce that subclasses implement required methods.',
    'Magic methods are hooks: `__add__` for `+`, `__len__` for `len()`, `__eq__` for `==`, `__str__` for `str()`.',
    '`__enter__`/`__exit__` implement the context manager protocol used by `with` statements.',
    '`__call__` makes any object callable like a function — great for stateful callables.',
  ],

  checkpoints: ['read-intuition'],
}
