export default {
  id: 'py-4-6-dataclasses-composition',
  slug: 'oop-dataclasses',
  chapter: 4.6,
  order: 6,
  title: 'Dataclasses and Composition',
  subtitle: 'Eliminating boilerplate with @dataclass and building objects that have rather than are',
  tags: ['dataclass', 'field', '__post_init__', 'frozen', 'composition', 'has-a', 'component pattern'],

  hook: {
    question: 'When should you use composition instead of inheritance — and how do you avoid writing the same `__init__`, `__repr__`, and `__eq__` over and over?',
    realWorldContext:
      'Every data class you write needs `__init__` to store fields, `__repr__` for debugging, and `__eq__` to compare instances. ' +
      'That is three methods of pure boilerplate before you write a single line of real logic. ' +
      'Python 3.7 introduced `@dataclass` to generate all of that automatically from type-annotated class attributes. ' +
      'Meanwhile, "favour composition over inheritance" is one of the most cited principles in software design: ' +
      'instead of a deep inheritance tree where a `GuideDog` is a `Dog` is an `Animal`, ' +
      'you build objects from **components** — a `GameCharacter` *has* a `HealthComponent`, an `InventoryComponent`, a `CombatComponent`. ' +
      'This makes your code more flexible, more testable, and far easier to change as requirements grow.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      'The `@dataclass` decorator reads the class body for annotated variables and auto-generates `__init__`, `__repr__`, and `__eq__`. ' +
      'Fields with default values must come after fields without. ' +
      'Mutable defaults (lists, dicts) must use `field(default_factory=list)` — a bare `= []` would share one list across all instances, ' +
      'the same class-variable bug from lesson 4.1.',

      '`__post_init__` is your escape hatch: it runs after the generated `__init__` completes. ' +
      'Use it for validation, computed fields, or any setup that needs all fields already in place. ' +
      '`frozen=True` makes the dataclass immutable — attributes are read-only after construction, and `__hash__` is generated so instances can live in sets and dict keys. ' +
      '`order=True` generates all six comparison operators from the field order.',

      'Composition follows the **has-a** relationship rather than **is-a**. ' +
      'A `GameCharacter` has a `HealthComponent`, has an `InventoryComponent`, has a `CombatComponent`. ' +
      'Each component is its own class responsible for exactly one domain. ' +
      'The character delegates to them rather than inheriting from a monolithic base. ' +
      'You can swap or extend any component independently without touching the others.',

      'The design rule of thumb: reach for inheritance when the relationship is truly IS-A and you want to share interface as well as implementation. ' +
      'Reach for composition when you are mixing capabilities from unrelated domains, ' +
      'or when the hierarchy would grow too deep to reason about. ' +
      'Most real-world code uses both, but beginners overuse inheritance and underuse composition.',
    ],
    callouts: [
      {
        type: 'warning',
        title: 'Never use a bare mutable default in a dataclass',
        body: '`tags: list = []` in a dataclass has the same bug as a class-variable list — every instance shares it. Always write `tags: list = field(default_factory=list)`. The decorator enforces this: using a bare mutable literal raises `ValueError` at class definition time.',
      },
      {
        type: 'insight',
        title: 'frozen=True gives you free hashability',
        body: 'Mutable objects cannot be safely used as dictionary keys or set members. A `frozen=True` dataclass generates `__hash__` automatically — making it a lightweight immutable record. Use it for value objects like `Point`, `Color`, or `DateRange`.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.6 — Dataclasses and Composition',
        mathBridge: 'Run each cell. After the dataclass cells, check what happens when you remove the `field()` wrapper and use a bare list.',
        caption: 'Use @dataclass to eliminate boilerplate, then build a game character through composition.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Basic @dataclass — Point',
              prose:
                'Annotate fields with type hints. `@dataclass` generates `__init__`, `__repr__`, and `__eq__` automatically. ' +
                'You still write any methods you want — the decorator only generates the boilerplate. ' +
                '`p1 == Point(1.0, 2.0)` compares by value (field by field), not by identity.',
              code: [
                'from dataclasses import dataclass',
                '',
                '',
                '@dataclass',
                'class Point:',
                '    """A 2D point. __init__, __repr__, __eq__ are auto-generated."""',
                '    x: float',
                '    y: float',
                '',
                '    def distance_to(self, other: \'Point\') -> float:',
                '        return ((self.x - other.x)**2 + (self.y - other.y)**2) ** 0.5',
                '',
                '',
                'p1 = Point(1.0, 2.0)',
                'p2 = Point(4.0, 6.0)',
                '',
                'print(p1)                     # Point(x=1.0, y=2.0) — auto __repr__',
                'print(p1 == Point(1.0, 2.0))  # True — auto __eq__ (value, not identity)',
                'print(p1 is Point(1.0, 2.0))  # False — still different objects',
                'print(p1.distance_to(p2))      # 5.0',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'frozen=True and order=True',
              prose:
                '`frozen=True` makes all attributes read-only after construction and generates `__hash__`. ' +
                '`order=True` generates `__lt__`, `__le__`, `__gt__`, `__ge__` so you can sort instances. ' +
                'Comparison is done field-by-field in declaration order: first `x`, then `y`. ' +
                'Frozen dataclasses can be used as dictionary keys and set members.',
              code: [
                'from dataclasses import dataclass',
                '',
                '',
                '@dataclass(order=True, frozen=True)',
                'class ImmutablePoint:',
                '    x: float',
                '    y: float',
                '',
                '',
                'p = ImmutablePoint(3.0, 4.0)',
                'print(p)  # ImmutablePoint(x=3.0, y=4.0)',
                '',
                'try:',
                '    p.x = 10.0  # Raises FrozenInstanceError!',
                'except Exception as e:',
                '    print(f"Error: {type(e).__name__}")',
                '',
                '# Sortable because order=True',
                'points = [ImmutablePoint(3, 4), ImmutablePoint(1, 2), ImmutablePoint(2, 3)]',
                'print(sorted(points))  # sorted by x, then y',
                '',
                '# Hashable because frozen=True — usable in sets and dicts',
                'seen = {ImmutablePoint(1, 2), ImmutablePoint(3, 4), ImmutablePoint(1, 2)}',
                'print(len(seen))  # 2 — duplicate removed',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'field() — fine-grained control',
              prose:
                '`field()` gives you per-field options: `default_factory` for mutable defaults, ' +
                '`init=False` to exclude from `__init__`, `repr=False` to exclude from the string representation, ' +
                '`compare=False` to exclude from equality checks. ' +
                '`__post_init__` runs after `__init__` — use it for validation and computed fields.',
              code: [
                'from dataclasses import dataclass, field',
                'from typing import ClassVar, List',
                '',
                '',
                '@dataclass',
                'class Inventory:',
                '    name: str',
                '    price: float',
                '    category: str = "General"',
                '',
                '    # CORRECT way for mutable defaults — never use bare = []',
                '    tags: List[str] = field(default_factory=list)',
                '',
                '    # init=False — not in __init__, set in __post_init__',
                '    stock_count: int = field(default=0, init=False)',
                '',
                '    # repr=False — hidden from __repr__ output',
                '    internal_id: str = field(default="", repr=False)',
                '',
                '    # ClassVar — not a dataclass field, shared across all instances',
                '    item_count: ClassVar[int] = 0',
                '',
                '    def __post_init__(self):',
                '        """Runs after generated __init__. Perfect for validation."""',
                '        if self.price < 0:',
                '            raise ValueError(f"Price cannot be negative: {self.price}")',
                '        import uuid',
                '        self.internal_id = str(uuid.uuid4())[:8]',
                '        Inventory.item_count += 1',
                '',
                '    def add_tag(self, tag: str):',
                '        self.tags.append(tag)',
                '',
                '',
                'laptop = Inventory("Laptop Pro", 999.99, "Electronics", tags=["tech"])',
                'phone = Inventory("Smartphone", 599.99, "Electronics")',
                'book = Inventory("Python Book", 49.99)',
                '',
                'phone.add_tag("mobile")',
                'print(laptop)',
                'print(phone)',
                'print(f"Total items created: {Inventory.item_count}")  # 3',
                '',
                'try:',
                '    bad = Inventory("Bad", -1)',
                'except ValueError as e:',
                '    print(f"Error: {e}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 4,
              cellTitle: 'Dataclass inheritance — Vehicle hierarchy',
              prose:
                'Dataclasses support inheritance. The child\'s `__init__` includes all parent fields first, ' +
                'then the child\'s own fields. You cannot have a field without a default in a child class ' +
                'if the parent class has any fields with defaults — that would produce an invalid signature. ' +
                '`asdict()` and `astuple()` convert any dataclass to a plain dict or tuple for serialisation.',
              code: [
                'from dataclasses import dataclass, asdict, astuple',
                '',
                '',
                '@dataclass',
                'class Vehicle:',
                '    make: str',
                '    model: str',
                '    year: int',
                '',
                '    def describe(self):',
                '        return f"{self.year} {self.make} {self.model}"',
                '',
                '',
                '@dataclass',
                'class ElectricVehicle(Vehicle):',
                '    battery_kwh: float',
                '    range_miles: int',
                '',
                '    def efficiency(self):',
                '        return self.battery_kwh / self.range_miles * 1000  # Wh per mile',
                '',
                '',
                '@dataclass',
                'class Car(Vehicle):',
                '    doors: int = 4',
                '    transmission: str = "automatic"',
                '',
                '',
                'ev = ElectricVehicle("Tesla", "Model 3", 2023, 75.0, 358)',
                'car = Car("Toyota", "Camry", 2022)',
                '',
                'print(ev)',
                'print(ev.describe())',
                'print(f"Efficiency: {ev.efficiency():.1f} Wh/mile")',
                'print(car)',
                '',
                '# Convert to plain dict or tuple for serialisation',
                'print(asdict(ev))',
                'print(astuple(ev))',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 5,
              cellTitle: 'Composition — GameCharacter built from components',
              prose:
                'Instead of inheriting from `HealthMixin`, `InventoryMixin`, `CombatMixin`, ' +
                'the character *contains* three separate component objects. ' +
                'Each component owns its own domain completely. ' +
                'The character delegates to them: `self.health.take_damage(...)`, `self.inventory.add_item(...)`. ' +
                'You can change `HealthComponent` independently — nothing in `CombatComponent` breaks.',
              code: [
                'class HealthComponent:',
                '    def __init__(self, max_health):',
                '        self.max_health = max_health',
                '        self.current = max_health',
                '',
                '    def take_damage(self, amount):',
                '        self.current = max(0, self.current - amount)',
                '',
                '    def heal(self, amount):',
                '        self.current = min(self.max_health, self.current + amount)',
                '',
                '    @property',
                '    def is_alive(self): return self.current > 0',
                '',
                '    @property',
                '    def percent(self): return (self.current / self.max_health) * 100',
                '',
                '',
                'class InventoryComponent:',
                '    def __init__(self, max_size=10):',
                '        self.items = []',
                '        self.max_size = max_size',
                '',
                '    def add(self, item):',
                '        if len(self.items) >= self.max_size:',
                '            raise RuntimeError("Inventory full")',
                '        self.items.append(item)',
                '',
                '    def has(self, item): return item in self.items',
                '',
                '',
                'class CombatComponent:',
                '    def __init__(self, attack, defense):',
                '        self.attack = attack',
                '        self.defense = defense',
                '        self.level = 1',
                '',
                '    def deal_damage(self):',
                '        import random',
                '        return int(self.attack * self.level * random.uniform(0.8, 1.2))',
                '',
                '    def reduce_damage(self, raw):',
                '        return max(1, raw - self.defense)',
                '',
                '',
                'class GameCharacter:',
                '    """Built entirely through composition — no mixin or deep inheritance."""',
                '',
                '    def __init__(self, name, max_health, attack, defense):',
                '        self.name = name',
                '        self.health = HealthComponent(max_health)',
                '        self.inventory = InventoryComponent()',
                '        self.combat = CombatComponent(attack, defense)',
                '',
                '    def attack_target(self, target):',
                '        if not self.health.is_alive:',
                '            print(f"{self.name} is defeated — cannot attack!")',
                '            return',
                '        raw = self.combat.deal_damage()',
                '        actual = target.combat.reduce_damage(raw)',
                '        target.health.take_damage(actual)',
                '        print(f"{self.name} hits {target.name} for {actual} dmg! ({target.health.current}/{target.health.max_health} HP)")',
                '        if not target.health.is_alive:',
                '            print(f"{target.name} defeated!")',
                '',
                '    def pick_up(self, item):',
                '        self.inventory.add(item)',
                '        print(f"{self.name} picked up {item}.")',
                '',
                '    def status(self):',
                '        print(f"{self.name}: {self.health.current}/{self.health.max_health} HP ({self.health.percent:.0f}%) | Items: {self.inventory.items}")',
                '',
                '',
                'hero = GameCharacter("Arthur", max_health=100, attack=20, defense=5)',
                'villain = GameCharacter("Mordred", max_health=80, attack=25, defense=3)',
                '',
                'hero.pick_up("Magic Sword")',
                'hero.pick_up("Health Potion")',
                '',
                'hero.status()',
                'villain.status()',
                'print()',
                'hero.attack_target(villain)',
                'villain.attack_target(hero)',
                'hero.attack_target(villain)',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 6,
              cellTitle: 'Composition vs inheritance — when to use each',
              prose:
                'Use **inheritance** when the relationship is truly IS-A and the subclass should honour the full parent contract. ' +
                'Use **composition** when you are mixing independent capabilities, when the hierarchy would grow too deep, ' +
                'or when you want to swap implementations at runtime. ' +
                'The animal example shows both approaches side by side: the inheritance version hits a dead end ' +
                'when a duck needs to both walk and swim, while the composition version handles any combination trivially.',
              code: [
                '# INHERITANCE approach — gets awkward with multiple capabilities',
                'class Animal:',
                '    def __init__(self, name): self.name = name',
                '',
                'class LandAnimal(Animal):',
                '    def walk(self): print(f"{self.name} walks")',
                '',
                'class WaterAnimal(Animal):',
                '    def swim(self): print(f"{self.name} swims")',
                '',
                '# Duck needs BOTH — forces multiple inheritance',
                'class Duck(LandAnimal, WaterAnimal):',
                '    def quack(self): print(f"{self.name} quacks")',
                '',
                '',
                '# COMPOSITION approach — trivially extensible',
                'class WalkAbility:',
                '    def walk(self, name): print(f"{name} walks on land.")',
                '',
                'class SwimAbility:',
                '    def swim(self, name): print(f"{name} swims.")',
                '',
                'class FlyAbility:',
                '    def fly(self, name): print(f"{name} soars!")',
                '',
                '',
                'class Animal:',
                '    def __init__(self, name, *abilities):',
                '        self.name = name',
                '        self._abilities = {type(a).__name__: a for a in abilities}',
                '',
                '    def walk(self):',
                '        ab = self._abilities.get("WalkAbility")',
                '        ab.walk(self.name) if ab else print(f"{self.name} cannot walk")',
                '',
                '    def swim(self):',
                '        ab = self._abilities.get("SwimAbility")',
                '        ab.swim(self.name) if ab else print(f"{self.name} cannot swim")',
                '',
                '    def fly(self):',
                '        ab = self._abilities.get("FlyAbility")',
                '        ab.fly(self.name) if ab else print(f"{self.name} cannot fly")',
                '',
                '',
                '# Mix any combination — no hierarchy changes needed',
                'duck  = Animal("Donald", WalkAbility(), SwimAbility(), FlyAbility())',
                'dog   = Animal("Rex", WalkAbility())',
                'fish  = Animal("Nemo", SwimAbility())',
                '',
                'duck.walk(); duck.swim(); duck.fly()',
                'dog.swim()   # cannot swim — graceful',
                'fish.fly()   # cannot fly — graceful',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: 'What three methods does `@dataclass` generate automatically?',
      options: [
        '`__init__`, `__repr__`, and `__eq__`',
        '`__init__`, `__str__`, and `__hash__`',
        '`__new__`, `__init__`, and `__del__`',
      ],
      correct: 0,
    },
    {
      id: 'q2',
      type: 'choice',
      text: 'You want a mutable list field in a dataclass. Which is correct?',
      options: [
        '`tags: list = []` — a default list literal works fine',
        '`tags: list = field(default_factory=list)` — required for mutable defaults',
        '`tags: list = field(default=[])` — pass the list to field\'s default parameter',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'What does `frozen=True` do to a dataclass?',
      options: [
        'It prevents the class from being subclassed',
        'It makes attributes read-only after construction and generates `__hash__`',
        'It freezes the class variable count — no more instances can be created',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'A `GameCharacter` *contains* a `HealthComponent`. Which design principle does this represent?',
      options: [
        'Inheritance — GameCharacter IS-A HealthComponent',
        'Composition — GameCharacter HAS-A HealthComponent',
        'Polymorphism — HealthComponent overrides GameCharacter methods',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    '`@dataclass` auto-generates `__init__`, `__repr__`, and `__eq__` from annotated class attributes.',
    'Use `field(default_factory=list)` for mutable defaults — never a bare `= []`.',
    '`__post_init__` runs after the generated `__init__` — use it for validation and computed attributes.',
    '`frozen=True` makes a dataclass immutable and hashable; `order=True` adds comparison operators.',
    'Composition (HAS-A) is more flexible than inheritance (IS-A) when mixing independent capabilities.',
    'Each component is fully responsible for its own domain — swapping or extending one does not break others.',
  ],

  checkpoints: ['read-intuition'],
}
