export default {
  id: 'py-4-7-mixins-descriptors',
  slug: 'oop-mixins-descriptors',
  chapter: 4.1,
  order: 7,
  title: 'Mixins and Descriptors',
  subtitle: 'Reusable behaviour slices and the engine behind @property',
  tags: ['mixin', 'descriptor', '__get__', '__set__', '__set_name__', 'lazy property', 'multiple inheritance'],

  hook: {
    question: 'How do you add JSON serialization, logging, or validation to any class without rewriting the same code — and without a messy inheritance tree?',
    realWorldContext:
      'Mixins are small, focused classes designed to be "mixed in" to other classes via multiple inheritance. ' +
      'They provide one capability each — serialization, logging, validation, comparison — and the consuming class ' +
      'simply lists them as parents. Django\'s class-based views are built almost entirely from mixins. ' +
      'Descriptors go one level deeper: they are the mechanism that Python itself uses to implement `@property`, ' +
      '`@classmethod`, and `@staticmethod`. Any class that implements `__get__`, `__set__`, or `__delete__` ' +
      'becomes a descriptor — and can be reused as a class-level attribute to add automatic validation or ' +
      'lazy computation to every instance of any class that uses it.',
    previewVisualizationId: 'PythonNotebook',
  },

  intuition: {
    prose: [
      'A **mixin** is a class that: (1) provides one specific capability, (2) is not meant to be instantiated alone, ' +
      '(3) has no `__init__` or a very minimal one, and (4) is named with a `Mixin` suffix by convention. ' +
      'You combine mixins with multiple inheritance: `class Product(JSONSerializableMixin, LoggableMixin, ReprMixin)`. ' +
      'The business logic stays in `Product`; the mixins bolt on capabilities from the outside.',

      'A **descriptor** is any object that implements the **descriptor protocol**: ' +
      '`__get__(self, obj, objtype)` is called on attribute read, `__set__(self, obj, value)` on write, ' +
      '`__delete__(self, obj)` on deletion. ' +
      'When you write `name = TypedAttribute(str)` at the class level, every `instance.name = value` call ' +
      'automatically routes through `TypedAttribute.__set__` — giving you class-wide validation with zero boilerplate per instance.',

      '`__set_name__(self, owner, name)` is called automatically when the descriptor is assigned to a class body. ' +
      'It tells the descriptor its own attribute name, so it can use `_name` as an internal storage key ' +
      'without you having to pass the name manually.',

      'A **lazy property** is a non-data descriptor (only `__get__`, no `__set__`). ' +
      'On first access it computes the value, then stores it directly in the instance\'s `__dict__`. ' +
      'On subsequent accesses, the instance dict entry shadows the descriptor — the computation never runs again. ' +
      'This is the pattern behind `functools.cached_property`.',
    ],
    callouts: [
      {
        type: 'insight',
        title: 'Mixins solve the capability-combination problem',
        body: 'Inheritance says "this IS-A that." Mixins say "this has THIS CAPABILITY." You can combine any set of mixin capabilities without creating an exponential number of subclasses. A Product can be serializable AND loggable AND validatable by listing three mixins — no new classes needed.',
      },
      {
        type: 'warning',
        title: 'Data descriptors take priority over instance __dict__',
        body: 'A data descriptor (implements both `__get__` and `__set__`) always wins over an instance attribute with the same name. A non-data descriptor (only `__get__`) can be shadowed by an instance attribute — that\'s exactly how the lazy property pattern works.',
      },
    ],
    visualizations: [
      {
        id: 'PythonNotebook',
        title: 'OOP 4.7 — Mixins and Descriptors',
        mathBridge: 'Run each cell. For descriptors, watch which method intercepts each operation.',
        caption: 'Build reusable mixin classes and implement custom descriptors that power automatic validation.',
        props: {
          initialCells: [
            {
              id: 1,
              cellTitle: 'Utility mixins — JSONSerializable, Repr, Comparable',
              prose:
                '`JSONSerializableMixin` adds `to_json()` and `from_json()` to any class. ' +
                '`ReprMixin` auto-generates `__repr__` from instance variables. ' +
                '`ComparableMixin` generates all six comparison operators from just `__lt__` and `__eq__`. ' +
                'None of these mixins have meaningful `__init__` — they contribute pure behaviour.',
              code: [
                'import json',
                '',
                '',
                'class JSONSerializableMixin:',
                '    def to_json(self, pretty=False):',
                '        indent = 2 if pretty else None',
                '        return json.dumps(self.__dict__, indent=indent, default=str)',
                '',
                '    @classmethod',
                '    def from_json(cls, json_string):',
                '        data = json.loads(json_string)',
                '        obj = cls.__new__(cls)   # create without calling __init__',
                '        obj.__dict__.update(data)',
                '        return obj',
                '',
                '',
                'class ReprMixin:',
                '    def __repr__(self):',
                '        attrs = ", ".join(',
                '            f"{k}={v!r}"',
                '            for k, v in self.__dict__.items()',
                '            if not k.startswith("_")',
                '        )',
                '        return f"{self.__class__.__name__}({attrs})"',
                '',
                '',
                'class ComparableMixin:',
                '    """Generates __le__, __gt__, __ge__ from __lt__ and __eq__."""',
                '    def __le__(self, other): return self < other or self == other',
                '    def __gt__(self, other): return not (self < other or self == other)',
                '    def __ge__(self, other): return not (self < other)',
                '',
                '',
                'class Employee(JSONSerializableMixin, ComparableMixin, ReprMixin):',
                '    def __init__(self, name, salary, department):',
                '        self.name = name',
                '        self.salary = salary',
                '        self.department = department',
                '',
                '    def __lt__(self, other): return self.salary < other.salary',
                '    def __eq__(self, other): return self.name == other.name',
                '    def __hash__(self): return hash(self.name)',
                '',
                '',
                'e1 = Employee("Alice", 80000, "Engineering")',
                'e2 = Employee("Bob", 95000, "Marketing")',
                'e3 = Employee("Charlie", 70000, "Design")',
                '',
                'print(repr(e1))              # ReprMixin',
                'print(e1.to_json(pretty=True))  # JSONSerializableMixin',
                '',
                'employees = [e2, e1, e3]',
                'employees.sort()             # ComparableMixin enables sorting',
                'for e in employees:',
                '    print(f"{e.name}: ${e.salary:,}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 2,
              cellTitle: 'LoggableMixin and ValidatableMixin combined with business logic',
              prose:
                '`LoggableMixin` stores timestamped log entries. ' +
                '`ValidatableMixin` runs a list of `(field, validator_fn, error_msg)` tuples defined on the class. ' +
                'The `Product` class mixes in four behaviours. Its own `__init__` initialises `LoggableMixin` ' +
                'and adds the first log entry. Notice how `Product` itself stays clean — just business logic.',
              code: [
                'from datetime import datetime',
                '',
                '',
                'class LoggableMixin:',
                '    def __init__(self):',
                '        self._log = []',
                '',
                '    def log(self, message):',
                '        self._log.append({',
                '            "time": datetime.now().isoformat(),',
                '            "class": self.__class__.__name__,',
                '            "message": message',
                '        })',
                '',
                '    def print_log(self):',
                '        print(f"=== Log for {self.__class__.__name__} ===")',
                '        for entry in self._log:',
                '            print(f"  [{entry[\'time\']}] {entry[\'message\']}")',
                '',
                '',
                'class ValidatableMixin:',
                '    def validate(self):',
                '        errors = []',
                '        for field, validator, msg in getattr(self, "_validations", []):',
                '            if not validator(getattr(self, field, None)):',
                '                errors.append(f"{field}: {msg}")',
                '        return errors',
                '',
                '    def is_valid(self):',
                '        return len(self.validate()) == 0',
                '',
                '',
                'class Product(LoggableMixin, ValidatableMixin):',
                '    _validations = [',
                '        ("name",  lambda x: isinstance(x, str) and len(x) > 0, "Name required"),',
                '        ("price", lambda x: isinstance(x, (int, float)) and x > 0, "Price must be positive"),',
                '        ("stock", lambda x: isinstance(x, int) and x >= 0, "Stock cannot be negative"),',
                '    ]',
                '',
                '    def __init__(self, name, price, stock):',
                '        LoggableMixin.__init__(self)',
                '        self.name = name',
                '        self.price = price',
                '        self.stock = stock',
                '        self.log(f"Created: {name}")',
                '',
                '    def sell(self, qty):',
                '        if qty > self.stock:',
                '            raise ValueError(f"Need {qty}, have {self.stock}")',
                '        self.stock -= qty',
                '        self.log(f"Sold {qty}. Stock: {self.stock}")',
                '        return self.price * qty',
                '',
                '',
                'laptop = Product("Laptop", 999.99, 50)',
                'print(laptop.is_valid())    # True',
                'revenue = laptop.sell(3)',
                'print(f"Revenue: ${revenue:.2f}")',
                'laptop.print_log()',
                '',
                'bad = Product("", -5, -1)',
                'print(bad.validate())       # 3 validation errors',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 3,
              cellTitle: 'Descriptor protocol — TypedAttribute and RangeAttribute',
              prose:
                '`TypedAttribute` enforces a type on every write. `RangeAttribute` enforces a numeric range. ' +
                'Both implement `__set_name__` (called automatically at class definition) to learn their own name, ' +
                'and store values under `_name` on the instance. ' +
                'When `Person` is defined, Python calls `TypedAttribute.__set_name__(Person, "name")` automatically.',
              code: [
                'class TypedAttribute:',
                '    """Descriptor that enforces a specific type."""',
                '',
                '    def __init__(self, expected_type, allow_none=False):',
                '        self.expected_type = expected_type',
                '        self.allow_none = allow_none',
                '',
                '    def __set_name__(self, owner, name):',
                '        """Called at class definition — learns the attribute name."""',
                '        self.attr_name = name',
                '        self.private_name = "_" + name   # internal storage key',
                '',
                '    def __get__(self, obj, objtype=None):',
                '        if obj is None: return self      # accessed from the class itself',
                '        return getattr(obj, self.private_name, None)',
                '',
                '    def __set__(self, obj, value):',
                '        if value is None:',
                '            if not self.allow_none:',
                '                raise ValueError(f"{self.attr_name} cannot be None")',
                '        elif not isinstance(value, self.expected_type):',
                '            raise TypeError(',
                '                f"{self.attr_name} must be {self.expected_type.__name__}, "',
                '                f"got {type(value).__name__}"',
                '            )',
                '        setattr(obj, self.private_name, value)',
                '',
                '',
                'class RangeAttribute:',
                '    """Descriptor that enforces a numeric range."""',
                '',
                '    def __init__(self, min_val, max_val):',
                '        self.min_val = min_val',
                '        self.max_val = max_val',
                '',
                '    def __set_name__(self, owner, name):',
                '        self.attr_name = name',
                '        self.private_name = "_" + name',
                '',
                '    def __get__(self, obj, objtype=None):',
                '        if obj is None: return self',
                '        return getattr(obj, self.private_name, None)',
                '',
                '    def __set__(self, obj, value):',
                '        if not (self.min_val <= value <= self.max_val):',
                '            raise ValueError(',
                '                f"{self.attr_name} must be {self.min_val}–{self.max_val}, got {value}"',
                '            )',
                '        setattr(obj, self.private_name, value)',
                '',
                '',
                'class Person:',
                '    # Descriptors as class variables — validation is automatic',
                '    name  = TypedAttribute(str)',
                '    age   = RangeAttribute(0, 150)',
                '    email = TypedAttribute(str, allow_none=True)',
                '',
                '    def __init__(self, name, age, email=None):',
                '        self.name = name    # calls TypedAttribute.__set__',
                '        self.age = age      # calls RangeAttribute.__set__',
                '        self.email = email',
                '',
                '    def __repr__(self):',
                '        return f"Person({self.name!r}, {self.age}, {self.email!r})"',
                '',
                '',
                'p = Person("Alice", 30, "alice@example.com")',
                'print(p)',
                '',
                'try: p.age = 200',
                'except ValueError as e: print(f"Range error: {e}")',
                '',
                'try: p.name = 42',
                'except TypeError as e: print(f"Type error: {e}")',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
            {
              id: 4,
              cellTitle: 'LazyProperty — non-data descriptor for cached computation',
              prose:
                'A non-data descriptor (only `__get__`, no `__set__`) can be shadowed by an instance dict entry. ' +
                '`LazyProperty` exploits this: on first access it computes the result and writes it directly into ' +
                '`obj.__dict__[attr_name]`. From then on, Python finds the instance dict entry first and never ' +
                'calls the descriptor again — the value is cached for free. ' +
                'This is exactly how `functools.cached_property` works.',
              code: [
                'class LazyProperty:',
                '    """Non-data descriptor: computes once, caches on the instance."""',
                '',
                '    def __init__(self, func):',
                '        self.func = func',
                '        self.attr_name = None',
                '',
                '    def __set_name__(self, owner, name):',
                '        self.attr_name = name',
                '',
                '    def __get__(self, obj, objtype=None):',
                '        if obj is None:',
                '            return self',
                '        if self.attr_name not in obj.__dict__:',
                '            print(f"Computing {self.attr_name} for the first time...")',
                '            obj.__dict__[self.attr_name] = self.func(obj)  # cache it',
                '        return obj.__dict__[self.attr_name]',
                '',
                '',
                'class Circle:',
                '    PI = 3.141592653589793',
                '',
                '    def __init__(self, radius):',
                '        self.radius = radius',
                '',
                '    @LazyProperty',
                '    def area(self):',
                '        import time; time.sleep(0.01)   # simulate expensive work',
                '        return Circle.PI * self.radius ** 2',
                '',
                '    @LazyProperty',
                '    def circumference(self):',
                '        return 2 * Circle.PI * self.radius',
                '',
                '',
                'c = Circle(10)',
                'print(c.area)           # "Computing..." then result',
                'print(c.area)           # Cached — no recomputation',
                'print(c.circumference)  # "Computing..." first time',
                'print(c.circumference)  # Cached',
                '',
                '# The cached values live directly in the instance dict',
                'print(c.__dict__)       # {\'radius\': 10, \'area\': ..., \'circumference\': ...}',
              ].join('\n'),
              output: '', status: 'idle', figureJson: null,
            },
          ],
        },
      },
    ],
  },

  quiz: [
    {
      id: 'q1',
      type: 'choice',
      text: 'A mixin class is designed to be used how?',
      options: [
        'As a standalone class that you instantiate directly',
        'As a parent class via multiple inheritance to add a specific capability to another class',
        'As a replacement for abstract base classes',
      ],
      correct: 1,
    },
    {
      id: 'q2',
      type: 'choice',
      text: 'When does Python call `__set_name__` on a descriptor?',
      options: [
        'Every time you write to the attribute on an instance',
        'Once, automatically, when the descriptor is assigned to a class variable',
        'Only when you explicitly call it',
      ],
      correct: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      text: 'Why does a LazyProperty (non-data descriptor) get bypassed after the first access?',
      options: [
        'Python caches the descriptor result internally',
        'It stores the computed value directly in the instance `__dict__`, which Python checks before non-data descriptors',
        'The `@LazyProperty` decorator disables itself after the first call',
      ],
      correct: 1,
    },
    {
      id: 'q4',
      type: 'choice',
      text: 'You define `age = RangeAttribute(0, 150)` at the class level. What happens when you write `person.age = 200`?',
      options: [
        'Python stores 200 in `person.__dict__["age"]` as normal',
        '`RangeAttribute.__set__` is called and raises `ValueError` since 200 > 150',
        'Python ignores the assignment silently',
      ],
      correct: 1,
    },
  ],

  mentalModel: [
    'Mixins add capabilities via multiple inheritance — each mixin owns one concern.',
    'Name mixins with a `Mixin` suffix; they should not be instantiated alone.',
    'The descriptor protocol: `__get__` on read, `__set__` on write, `__delete__` on deletion.',
    '`__set_name__` is called once at class definition — use it to learn the attribute name for storage.',
    'Data descriptors (have `__set__`) take priority over instance `__dict__`.',
    'Non-data descriptors (only `__get__`) can be shadowed — the lazy-property caching pattern relies on this.',
  ],

  checkpoints: ['read-intuition'],
}
