import { lazy } from 'react'

export const SCENE_REGISTRY = {
  // Lesson 0-1: Sets
  WelcomeScene:               lazy(() => import('./WelcomeScene.jsx')),
  SetVennDiagram:             lazy(() => import('./SetVennDiagram.jsx')),
  SetNotationScene:           lazy(() => import('./SetNotationScene.jsx')),
  SetMembership:              lazy(() => import('./SetMembership.jsx')),
  EmptySetScene:              lazy(() => import('./EmptySetScene.jsx')),
  SubsetScene:                lazy(() => import('./SubsetScene.jsx')),
  SetCardinality:             lazy(() => import('./SetCardinality.jsx')),
  NumberSets:                 lazy(() => import('./NumberSets.jsx')),
  // Lesson 0-2: Set Operations
  SetOperationsScene:         lazy(() => import('./SetOperationsScene.jsx')),
  IntersectionScene:          lazy(() => import('./IntersectionScene.jsx')),
  SetDifferenceScene:         lazy(() => import('./SetDifferenceScene.jsx')),
  ComplementScene:            lazy(() => import('./ComplementScene.jsx')),
  InclusionExclusionScene:    lazy(() => import('./InclusionExclusionScene.jsx')),
  QualityInspectionScene:     lazy(() => import('./QualityInspectionScene.jsx')),
  DeMorganScene:              lazy(() => import('./DeMorganScene.jsx')),
  // Lesson 0-3: Logic
  NegationScene:              lazy(() => import('./NegationScene.jsx')),
  ConjunctionScene:           lazy(() => import('./ConjunctionScene.jsx')),
  TruthTableScene:            lazy(() => import('./TruthTableScene.jsx')),
  ImplicationScene:           lazy(() => import('./ImplicationScene.jsx')),
  BiconditionalScene:         lazy(() => import('./BiconditionalScene.jsx')),
  LogicConnectivesScene:      lazy(() => import('./LogicConnectivesScene.jsx')),
  LogicalEquivalenceScene:    lazy(() => import('./LogicalEquivalenceScene.jsx')),
  TautologyScene:             lazy(() => import('./TautologyScene.jsx')),
  RegionTruthScene:           lazy(() => import('./RegionTruthScene.jsx')),
  CompleteTableScene:         lazy(() => import('./CompleteTableScene.jsx')),
  // Lesson 0-4: Ordered Pairs
  OrderLostScene:             lazy(() => import('./OrderLostScene.jsx')),
  OrderedPairScene:           lazy(() => import('./OrderedPairScene.jsx')),
  CartesianProductScene:      lazy(() => import('./CartesianProductScene.jsx')),
  DistanceFormulaScene:       lazy(() => import('./DistanceFormulaScene.jsx')),
  MidpointScene:              lazy(() => import('./MidpointScene.jsx')),
  CoordinatePlaneScene:       lazy(() => import('./CoordinatePlaneScene.jsx')),
  ThreeDScene:                lazy(() => import('./ThreeDScene.jsx')),
  // Lesson 0-5: Relations
  RelationExamplesScene:      lazy(() => import('./RelationExamplesScene.jsx')),
  RelationPropertiesScene:    lazy(() => import('./RelationPropertiesScene.jsx')),
  RelationDiagramScene:       lazy(() => import('./RelationDiagramScene.jsx')),
  QuotientSetScene:           lazy(() => import('./QuotientSetScene.jsx')),
  EquivalenceClassScene:      lazy(() => import('./EquivalenceClassScene.jsx')),
  EquivClassDetailScene:      lazy(() => import('./EquivClassDetailScene.jsx')),
  // Lesson 0-6: Functions
  FunctionProblemScene:       lazy(() => import('./FunctionProblemScene.jsx')),
  ValidFunctionScene:         lazy(() => import('./ValidFunctionScene.jsx')),
  FunctionMachineScene:       lazy(() => import('./FunctionMachineScene.jsx')),
  DomainCodomainScene:        lazy(() => import('./DomainCodomainScene.jsx')),
  FunctionPlotScene:          lazy(() => import('./FunctionPlotScene.jsx')),
  VerticalLineTestScene:      lazy(() => import('./VerticalLineTestScene.jsx')),
  // Lesson 0-7: Function Types
  InjectiveScene:             lazy(() => import('./InjectiveScene.jsx')),
  SurjectiveScene:            lazy(() => import('./SurjectiveScene.jsx')),
  FourCombScene:              lazy(() => import('./FourCombScene.jsx')),
  BijectiveScene:             lazy(() => import('./BijectiveScene.jsx')),
  FunctionTypesScene:         lazy(() => import('./FunctionTypesScene.jsx')),
  TypesOnRScene:              lazy(() => import('./TypesOnRScene.jsx')),
  CardinalityTypesScene:      lazy(() => import('./CardinalityTypesScene.jsx')),
  // Lesson 0-8: Composition & Inverse
  CompositionScene:           lazy(() => import('./CompositionScene.jsx')),
  NotCommutativeScene:        lazy(() => import('./NotCommutativeScene.jsx')),
  AssociativeScene:           lazy(() => import('./AssociativeScene.jsx')),
  InverseFunctionScene:       lazy(() => import('./InverseFunctionScene.jsx')),
  IdentityFunctionScene:      lazy(() => import('./IdentityFunctionScene.jsx')),
  InverseCompositionLawScene: lazy(() => import('./InverseCompositionLawScene.jsx')),
  // Lesson 0-9: Proof by Contradiction
  ContradictionScene:         lazy(() => import('./ContradictionScene.jsx')),
  Sqrt2Scene:                 lazy(() => import('./Sqrt2Scene.jsx')),
  LargestIntScene:            lazy(() => import('./LargestIntScene.jsx')),
  EvenLemmaScene:             lazy(() => import('./EvenLemmaScene.jsx')),
  InfinitePrimesScene:        lazy(() => import('./InfinitePrimesScene.jsx')),
  // Lesson 0-10: Proof by Induction
  InductionScene:             lazy(() => import('./InductionScene.jsx')),
  GaussSumScene:              lazy(() => import('./GaussSumScene.jsx')),
  CounterexampleScene:        lazy(() => import('./CounterexampleScene.jsx')),
  PowerOf2Scene:              lazy(() => import('./PowerOf2Scene.jsx')),
  DivisibilityScene:          lazy(() => import('./DivisibilityScene.jsx')),
  RecursionScene:             lazy(() => import('./RecursionScene.jsx')),
  // Lesson 0-11: Mathematical Writing
  WritingMathScene:           lazy(() => import('./WritingMathScene.jsx')),
  NotationMistakesScene:      lazy(() => import('./NotationMistakesScene.jsx')),
  ReadingProofScene:          lazy(() => import('./ReadingProofScene.jsx')),
  NotationScene:              lazy(() => import('./NotationScene.jsx')),
  // Lesson 0-12: Capstone
  BridgeScene:                lazy(() => import('./BridgeScene.jsx')),
}

export const SCENE_META = {
  WelcomeScene:               { label: 'Introduction',          desc: 'Welcome. Scroll through the lesson to explore.' },
  SetVennDiagram:             { label: 'Venn Diagram',          desc: 'Visualise set membership, intersection, and union.' },
  SetNotationScene:           { label: 'Set Notation',          desc: 'Roster and set-builder notation compared.' },
  SetMembership:              { label: 'Membership ∈',          desc: 'Test whether elements belong to a set.' },
  EmptySetScene:              { label: 'Empty Set ∅',           desc: 'The empty set — nothing can belong to it.' },
  SubsetScene:                { label: 'Subsets ⊆',             desc: 'B ⊆ A: every element of B is also in A.' },
  SetCardinality:             { label: 'Cardinality |A|',       desc: 'Count the number of elements in a set.' },
  NumberSets:                 { label: 'Number Sets',           desc: 'ℕ ⊊ ℤ ⊊ ℚ ⊊ ℝ ⊊ ℂ nested hierarchy.' },
  SetOperationsScene:         { label: 'Set Operations',        desc: 'Union, intersection, difference, and complement cycling.' },
  IntersectionScene:          { label: 'Intersection A∩B',      desc: 'Gold pulsing intersection region with elements.' },
  SetDifferenceScene:         { label: 'Set Difference A\\B',   desc: 'Cycles A\\B and B\\A, erasing the intersection.' },
  ComplementScene:            { label: 'Complement Aᶜ',         desc: 'Universe glows gold outside A; elements animate in.' },
  InclusionExclusionScene:    { label: 'Inclusion–Exclusion',   desc: '|A∪B| = |A| + |B| − |A∩B| built phase by phase.' },
  QualityInspectionScene:     { label: 'Quality Inspection',    desc: 'Manufacturing example: Diameter OK ∩ Weight OK.' },
  DeMorganScene:              { label: "De Morgan's Laws",      desc: 'Both De Morgan laws visualised with Venn diagrams.' },
  NegationScene:              { label: 'Negation ¬P',           desc: 'P and ¬P cards flip every 1.8 s.' },
  ConjunctionScene:           { label: 'Conjunction P∧Q',       desc: 'AND gate cycling truth table rows; output light glows.' },
  TruthTableScene:            { label: 'Truth Table',           desc: 'Animated truth table for P, Q, and connectives.' },
  ImplicationScene:           { label: 'Implication P→Q',       desc: 'Arrow breaks (red dashed) only for T→F case.' },
  BiconditionalScene:         { label: 'Biconditional P⟺Q',    desc: 'Forward + backward arrows; gold when both match.' },
  LogicConnectivesScene:      { label: 'Logic Connectives',     desc: 'NOT, AND, OR, and implication truth tables.' },
  LogicalEquivalenceScene:    { label: 'Logical Equivalence',   desc: '¬(P∧Q) vs (¬P∨¬Q): column-by-column match.' },
  TautologyScene:             { label: 'Tautology & Contra.',   desc: 'P∨¬P (always green) vs P∧¬P (always red).' },
  RegionTruthScene:           { label: 'Region Truth',          desc: 'Venn diagram cycling P∧Q, P∨Q, P only, ¬P.' },
  CompleteTableScene:         { label: 'Complete Truth Table',  desc: '7-column table animated row by row.' },
  OrderLostScene:             { label: 'Order Matters',         desc: '{a,b}={b,a} but (a,b)≠(b,a) swapped with arcs.' },
  OrderedPairScene:           { label: 'Ordered Pairs',         desc: '4 example pairs cycling with 1st/2nd component labels.' },
  CartesianProductScene:      { label: 'A × B',                 desc: 'Cartesian product as a grid of ordered pairs.' },
  DistanceFormulaScene:       { label: 'Distance Formula',      desc: 'Right triangle legs animate; formula derived step by step.' },
  MidpointScene:              { label: 'Midpoint Formula',      desc: 'M animates to midpoint; formula derivation panel.' },
  CoordinatePlaneScene:       { label: 'Coordinate Plane',      desc: 'ℝ² with points plotted one by one.' },
  ThreeDScene:                { label: '3D Coordinates',        desc: 'Rotating 3D axes; 3 example points with projection lines.' },
  RelationExamplesScene:      { label: 'Relation Examples',     desc: '3 relation types cycling: ≤, divides, same parity.' },
  RelationPropertiesScene:    { label: 'Relation Properties',   desc: 'Reflexive (self-loops), Symmetric, Transitive mini-panels.' },
  RelationDiagramScene:       { label: 'Relation Diagram',      desc: 'Arrow diagram mapping elements of A to B.' },
  QuotientSetScene:           { label: 'Quotient Set A/~',      desc: 'Dashed arrows from elements into class blocks.' },
  EquivalenceClassScene:      { label: 'Equivalence Classes',   desc: 'Partition of A into equivalence classes mod 3.' },
  EquivClassDetailScene:      { label: 'Class Detail ℤ₉/3',    desc: '3 class containers; elements pulse; partition listed.' },
  FunctionProblemScene:       { label: 'Function Problems',     desc: 'Phase 0: invalid mapping; Phase 1: proper function.' },
  ValidFunctionScene:         { label: 'Valid Functions',       desc: '4 cases cycling: valid and invalid mappings.' },
  FunctionMachineScene:       { label: 'Function Machine',      desc: 'Input → f → output: values flow through f(x)=2x+1.' },
  DomainCodomainScene:        { label: 'Domain & Codomain',     desc: 'f: {1,2,3}→{a,b,c,d}; image highlighted in gold.' },
  FunctionPlotScene:          { label: 'Function Graph',        desc: 'f(x) = x² − 2 drawn progressively.' },
  VerticalLineTestScene:      { label: 'Vertical Line Test',    desc: 'Sweeping line: parabola ✓ vs circle ✗.' },
  InjectiveScene:             { label: 'Injective (1-to-1)',    desc: 'Injective vs not injective alternating phases.' },
  SurjectiveScene:            { label: 'Surjective (onto)',     desc: 'All B elements hit vs one never reached.' },
  FourCombScene:              { label: '4 Combinations',        desc: 'Injective only, Surjective only, Bijective, Neither.' },
  BijectiveScene:             { label: 'Bijection & Inverse',   desc: '4-element perfect match; f⁻¹ arrows appear.' },
  FunctionTypesScene:         { label: 'Function Types',        desc: 'Injective, surjective, and bijective compared.' },
  TypesOnRScene:              { label: 'Types on ℝ',            desc: 'f=2x (bij.), f=x² (neither), f=eˣ (inj.) graphs.' },
  CardinalityTypesScene:      { label: 'Cardinality & Types',   desc: '|A|<|B|, |A|=|B|, |A|>|B| vs INJ/SUR/BIJ badges.' },
  CompositionScene:           { label: 'Composition f∘g',       desc: 'Two function machines in a pipeline.' },
  NotCommutativeScene:        { label: 'Not Commutative',       desc: 'f∘g(x)=(x+1)² ≠ g∘f(x)=x²+1 for cycling x.' },
  AssociativeScene:           { label: 'Associative',           desc: '(h∘g)∘f vs h∘(g∘f): same result, bracket alternates.' },
  InverseFunctionScene:       { label: 'Inverse Functions',     desc: 'f and f⁻¹ reflected across y = x.' },
  IdentityFunctionScene:      { label: 'Identity Function',     desc: 'f∘id = id∘f = f demonstrated with pipeline rows.' },
  InverseCompositionLawScene: { label: '(f∘g)⁻¹ = g⁻¹∘f⁻¹',  desc: 'Forward composition then reverse; law verified.' },
  ContradictionScene:         { label: 'Contradiction',         desc: 'Proof flow: assume ¬P → derive P → contradiction.' },
  Sqrt2Scene:                 { label: '√2 is Irrational',      desc: 'Step-by-step cards for the irrationality proof.' },
  LargestIntScene:            { label: 'No Largest Integer',    desc: 'Assume N largest; N+1 > N → contradiction.' },
  EvenLemmaScene:             { label: 'Even Lemma',            desc: 'Contrapositive proof: n odd ⟹ n² odd.' },
  InfinitePrimesScene:        { label: 'Infinite Primes',       desc: "Euclid's proof: form N=p₁…pₙ+1, new prime found." },
  InductionScene:             { label: 'Induction',             desc: 'Dominos falling: P(k)→P(k+1) chain reaction.' },
  GaussSumScene:              { label: 'Gauss Sum',             desc: 'Staircase blocks paired to form n(n+1)/2.' },
  CounterexampleScene:        { label: 'Counterexample',        desc: '3 wrong claims each killed by one counterexample.' },
  PowerOf2Scene:              { label: '2ⁿ > n (Induction)',    desc: 'Bar chart + base/step proof build up together.' },
  DivisibilityScene:          { label: '2 | n(n+1)',            desc: 'Cycling n shows one of n, n+1 is always even.' },
  RecursionScene:             { label: 'Recursive Definition',  desc: 'T(n)=T(n-1)+n unrolled level by level to T(1)=1.' },
  WritingMathScene:           { label: 'Writing Mathematics',   desc: 'Bad vs Good examples cycling: punctuation, quantifiers.' },
  NotationMistakesScene:      { label: 'Notation Mistakes',     desc: '4 common symbol errors with correct alternatives.' },
  ReadingProofScene:          { label: 'Reading a Proof',       desc: '√2 irrationality proof annotated step by step.' },
  NotationScene:              { label: 'Notation Reference',    desc: 'Scrolling flashcards: symbol, name, and example.' },
  BridgeScene:                { label: 'Bridge to Stage 1',     desc: 'Stage 0 foundations flowing into Stage 1 topics.' },
}
