export const COURSES = [
  {
    key: "precalc",
    label: "Pre-Calc",
    path: "/course/precalc",
    desc: "Functions & Graphs",
    color: "indigo",
  },
  {
    key: "geometry",
    label: "Geometry",
    path: "/course/geometry",
    desc: "Proofs & Shapes",
    color: "blue",
  },
  {
    key: "calc",
    label: "Calculus",
    path: "/course/calc",
    desc: "Change & Infinity",
    color: "emerald",
  },
  {
    key: "physics-1",
    label: "Physics",
    path: "/course/physics-1",
    desc: "Mechanics & Waves",
    color: "red",
  },
  {
    key: "discrete",
    label: "Discrete",
    path: "/course/discrete",
    desc: "Logic & Puzzles",
    color: "purple",
  },
  {
    key: "web-1",
    label: "Web Systems",
    path: "/course/web-1",
    desc: "DOM, Reactivity & APIs",
    color: "orange",
  },
  {
    key: "linear-algebra",
    label: "Linear Algebra",
    path: "/course/linear-algebra",
    desc: "Vectors & Matrices",
    color: "teal",
  },
  {
    key: "python-1",
    label: "Python Programming",
    path: "/course/python-1",
    desc: "Core Language & Logic",
    color: "amber",
  },
  {
    key: "data-science-1",
    label: "Data Science",
    path: "/course/data-science-1",
    desc: "NumPy, Pandas & ML Foundations",
    color: "sky",
  },
  {
    key: "javascript-core",
    label: "JavaScript Core",
    path: "/course/javascript-core",
    desc: "Language & Runtime Fundamentals",
    color: "cyan",
  },
  {
    key: "tetris",
    label: "Build Tetris",
    path: "/course/tetris",
    desc: "Build a Full Game from Scratch",
    color: "rose",
  },
  {
    key: "cs-1",
    label: "Computer Science",
    path: "/course/cs-1",
    desc: "Logic, Circuits & Algorithms",
    color: "violet",
  },
  {
    key: "chemistry-1",
    label: "Chemistry",
    path: "/course/chemistry-1",
    desc: "Elements, Reactions & Structure",
    color: "lime",
  },
  {
    key: "digital-fundamentals",
    label: "Digital Fundamentals",
    path: "/course/digital-fundamentals",
    desc: "Signals, Binary & Logic",
    color: "sky",
  },
  {
    key: "cnc-logic",
    label: "CNC Macro Systems",
    path: "/course/cnc-logic",
    desc: "G-Code, Kinematics & Logic",
    color: "slate",
  },
  {
    key: "git-0",
    label: "Git",
    path: "/course/git-0",
    desc: "Version Control, Commits, Branches & Collaboration",
    color: "emerald",
  },
  {
    key: "dsa-1",
    label: "Data Structures & Algorithms",
    path: "/course/dsa-1",
    desc: "Memory, Structures & Algorithmic Thinking",
    color: "violet",
  },
  {
    key: "dp-1",
    label: "Dynamic Programming",
    path: "/course/dp-1",
    desc: "Overlapping Subproblems, Optimal Substructure & Classic Patterns",
    color: "fuchsia",
  },
  {
    key: "design-1",
    label: "Interface Design",
    path: "/course/design-1",
    desc: "Visual Hierarchy, Spacing & Design Systems",
    color: "pink",
  },
  {
    key: "three-js-1",
    label: "3D Graphics & Three.js",
    path: "/course/three-js-1",
    desc: "GPU Pipeline, WebGL & Three.js Mastery",
    color: "violet",
  },
  {
    key: "ai-engineering",
    label: "AI Engineering",
    path: "/course/ai-engineering",
    desc: "LLMs, Agents & Production AI Systems",
    color: "rose",
  },
  {
    key: "three-js-2",
    label: "ThreeJS P2",
    path: "/course/three-js-2",
    desc: "Learn ThreeJS from first principles",
    color: "rose",
  },
  {
    key: "canvas-1",
    label: "HTML Canvas",
    path: "/course/canvas-1",
    desc: "2D Graphics, Animation & CAD Foundations",
    color: "orange",
  },
  {
    key: "gcode-parser-1",
    label: "G-Code Interpreter",
    path: "/course/gcode-parser-1",
    desc: "Build a G-Code Parser from First Principles",
    color: "teal",
  },
  {
    key: "sql-0",
    label: "SQL Fundamentals",
    path: "/course/sql-0",
    desc: "Pure SQL — no Python required",
    color: "cyan",
  },
  {
    key: "sql-1",
    label: "Python + SQL",
    path: "/course/sql-1",
    desc: "Relational Model, Queries & Performance with Python",
    color: "blue",
  },
  {
    key: "nosql-1",
    label: "NoSQL Databases",
    path: "/course/nosql-1",
    desc: "Document Stores, CAP Theorem & Scale",
    color: "green",
  },
  {
    key: "applied-statistics",
    label: "Applied Statistics",
    path: "/course/applied-statistics",
    desc: "Data, Inference & Statistical Modeling",
    color: "violet",
  },
  {
    key: "cli-0",
    label: "Command Line",
    path: "/course/cli-0",
    desc: "Terminal, Filesystem & Shell Mastery",
    color: "slate",
  },
  {
    key: "cpp-0",
    label: "C++ Programming",
    path: "/course/cpp-0",
    desc: "Write, Compile & Run — C++ from First Principles",
    color: "blue",
  },
  {
    key: "cpp-1",
    label: "C++ Intermediate",
    path: "/course/cpp-1",
    desc: "Classes, RAII, Templates, Smart Pointers & Modern C++",
    color: "blue",
  },
];
