export const LEARNING_PATHS = [
  {
    id: 'path-assignment-first',
    title: 'Assignment-First (Fast Track)',
    audience: 'Students with upcoming homework, quizzes, or exams',
    promise: 'Get problem-classification, worked examples, and challenge reps first; fill conceptual gaps as needed.',
    lessons: [
      'assignment-playbook',
      'introduction',
      'limit-laws',
      'differentiation-rules',
      'chain-rule',
      'reading-derivatives',
      'optimization',
      'u-substitution',
      'fundamental-theorem',
      'applications',
    ],
  },
  {
    id: 'path-intuition-first',
    title: 'Why-First (Concept Track)',
    audience: 'Learners who want intuition before procedures',
    promise: 'Build deep mental models with visuals and real-world context before heavy symbol work.',
    lessons: [
      'real-numbers',
      'functions',
      'introduction',
      'continuity',
      'tangent-problem',
      'reading-derivatives',
      'area-accumulation',
      'definite-integral',
      'fundamental-theorem',
      'applications',
    ],
  },
  {
    id: 'path-proof-first',
    title: 'Proof-First (Rigor Track)',
    audience: 'Math majors and proof-oriented learners',
    promise: 'Follow theorem logic and proof structure from foundations through core calculus results.',
    lessons: [
      'sets-and-logic',
      'epsilon-delta',
      'visual-epsilon-delta',
      'squeeze-theorem',
      'mean-value-theorem',
      'rolles-theorem',
      'fundamental-theorem',
      'improper-integrals',
      'convergence-tests',
      'taylor-maclaurin',
    ],
  },
  {
    id: 'path-calc2-bridge',
    title: 'Calc 2 Bridge (Hard Course Prep)',
    audience: 'Learners preparing for difficult Calc 2',
    promise: 'Strengthen prerequisite algebra/geometry and push through integration techniques, series, and polar/parametric tools.',
    lessons: [
      'algebra-geometry-master-review',
      'partial-fractions-intro',
      'trig-review',
      'u-substitution',
      'integration-by-parts',
      'trig-integrals',
      'trig-substitution',
      'partial-fractions-integration',
      'sequences',
      'series-intro',
      'convergence-tests',
      'power-series',
      'taylor-maclaurin',
      'series-applications',
      'parametric-equations',
      'polar-coordinates',
      'polar-area-length',
    ],
  },
  {
    id: 'path-careers',
    title: 'Career Applications (CS, Bio, Econ, Eng)',
    audience: 'Learners asking where calculus shows up in real fields',
    promise: 'Jump to field-relevant lessons and return to theory only when needed.',
    lessons: [
      'exponentials',
      'reading-derivatives',
      'optimization',
      'related-rates',
      'applications',
      'numerical-integration',
      'sequences',
      'series-applications',
      'parametric-equations',
      'vector-calculus-preview',
    ],
  },
]
