export const LABS = [
  {
    key: 'music-lab',
    label: 'Music Lab',
    emoji: '🎵',
    color: 'violet',
    desc: 'Beat machine meets DAW — lay down drum patterns on a step sequencer, add synth and bass tracks, dial in reverb and delay with the FX chain, mix levels with the mixer, and draw melodies in the piano roll. Powered by Tone.js.',
    path: '/music-lab',
    tags: ['Music', 'Audio', 'Creative', 'Interactive'],
    cover: { grad: 'from-violet-600 via-purple-700 to-indigo-950', mark: '♩♫', sub: 'Sequencer · Synth · Piano Roll' },
  },
  {
    key: 'html-lab',
    label: 'HTML Lab',
    emoji: '🏗️',
    color: 'orange',
    desc: 'Drag, drop, and style real HTML elements on a live canvas — div, p, h1, button, span, and more. Edit inline CSS through a properties panel, watch the code panel sync both ways, and see the box model visualized live.',
    path: '/html-lab',
    tags: ['HTML', 'CSS', 'Web', 'Interactive'],
    cover: { grad: 'from-orange-600 via-amber-700 to-yellow-950', mark: '</>', sub: 'Elements · Box Model · CSS' },
  },
  {
    key: 'css-mastery',
    label: 'CSS 0 to Mastery',
    emoji: '🎨',
    color: 'fuchsia',
    desc: "Deep-dive into the browser's layout engine. Learn the Box Model, Centering, Flexbox, Grid, Stacking Contexts, and more through interactive multi-tab challenges.",
    path: '/web-learn/css-mastery',
    tags: ['CSS', 'Web', 'Interactive'],
    cover: { grad: 'from-fuchsia-600 via-pink-700 to-rose-950', mark: 'CSS', sub: 'Flex · Grid · Layout' },
  },
  {
    key: 'react-mastery',
    label: 'React 0 to Mastery',
    emoji: '⚛️',
    color: 'cyan',
    desc: 'Build from raw React elements to advanced patterns — 27 narrated lessons covering JSX, components, hooks, state, context, reducers, memoization, and Suspense with live interactive sandboxes.',
    path: '/web-learn/react-mastery',
    tags: ['React', 'Web', 'Interactive'],
    cover: { grad: 'from-cyan-500 via-blue-600 to-indigo-900', mark: 'React', sub: 'Components · Hooks · State' },
  },
  {
    key: 'sim-lab',
    label: 'Sim Lab',
    emoji: '🔭',
    color: 'sky',
    desc: 'Build your own physics simulations from scratch — projectile motion, orbital mechanics, spring systems, particle effects, and more. Monaco editor + live 3D Three.js sandbox.',
    path: '/sim-lab',
    tags: ['Physics', 'Three.js', 'Simulation'],
    cover: { grad: 'from-sky-700 via-blue-800 to-indigo-950', mark: '∫dt', sub: 'Physics · Three.js · Code' },
  },
  {
    key: 'drone-lab',
    label: 'Drone Lab',
    emoji: '🚁',
    color: 'sky',
    desc: 'Program a self-flying drone — 10 missions teaching displacement vectors, dot/cross products, rotation matrices, projections, Bézier paths, and PID control. JS, Python, and MATLAB.',
    path: '/drone-lab',
    tags: ['Robotics', 'Python', 'MATLAB'],
    cover: { grad: 'from-sky-600 via-cyan-800 to-blue-950', mark: '🚁', sub: 'Vectors · Matrices · PID' },
  },
  {
    key: 'robot-arm-sim',
    label: 'Robot Arm Simulator',
    emoji: '🦾',
    color: 'teal',
    desc: 'Learn robot programming from zero — trig, FK, IK, 4×4 transforms, obstacle avoidance, Fanuc TP. 19 missions, 2D + 6-DOF 3D arm, real Python & MATLAB.',
    path: '/robot-arm-lab',
    tags: ['Robotics', 'Python', 'MATLAB'],
    cover: { grad: 'from-teal-700 via-cyan-800 to-blue-950', mark: '🦾', sub: 'FK · IK · Fanuc TP' },
  },
  {
    key: 'matrix-lab',
    label: 'Matrix Lab',
    emoji: '⊡',
    color: 'violet',
    desc: 'Master linear algebra by coding it — row ops, Gaussian elimination, determinants, inverse, and Gram-Schmidt in JS, Python, and MATLAB.',
    path: '/matrix-lab',
    tags: ['Math', 'Python', 'MATLAB'],
    cover: { grad: 'from-violet-700 via-purple-800 to-indigo-950', mark: 'Ax=b', sub: 'Row Ops · RREF · QR' },
  },
  {
    key: 'odds-lab',
    label: 'Probability Casino Lab',
    emoji: '21',
    color: 'emerald',
    desc: 'Learn probability, statistics, expected value, conditional probability, and card counting with cards, dice, blackjack decisions, overlays, and simulations.',
    path: '/odds-lab',
    tags: ['Math', 'Statistics', 'Probability'],
    cover: { grad: 'from-emerald-700 via-cyan-800 to-slate-950', mark: 'P(A|B)', sub: 'Cards - Dice - EV' },
  },
  {
    key: 'cmm-lab',
    label: 'CMM Lab',
    emoji: '⊹',
    color: 'emerald',
    desc: 'Simulate a coordinate measuring machine — probe circles, planes, and cylinders, watch the normal equation solve live, and read a real GD&T report with diameter deviation, circularity, flatness, and cylindricity.',
    path: '/cmm-lab',
    tags: ['Engineering', 'Math', 'Metrology'],
    cover: { grad: 'from-emerald-700 via-teal-800 to-cyan-950', mark: 'AᵀAx=Aᵀb', sub: 'Circle · Plane · Cylinder' },
  },
  {
    key: 'decomp-lab',
    label: 'Decomp Lab',
    emoji: '⊗',
    color: 'violet',
    desc: 'See SVD and least squares in action — compress a real image by keeping only its dominant singular value layers, then fit polynomial curves to noisy data using the normal equation.',
    path: '/decomp-lab',
    tags: ['Math', 'Linear Algebra', 'Data Science'],
    cover: { grad: 'from-violet-700 via-purple-800 to-indigo-950', mark: 'UΣVᵀ', sub: 'SVD · Least Squares · Projection' },
  },
  {
    key: 'matrix-3d-lab',
    label: 'Matrix 3D Lab',
    emoji: '⊕',
    color: 'cyan',
    desc: 'See linear algebra live in a 3D world — manipulate a 3D object with translate/rotate/scale sliders and watch the 4×4 matrix update in real time. Covers vectors, dot product, determinant, RREF, eigenvalues, Cramer\'s rule, and subspaces.',
    path: '/matrix-3d-lab',
    tags: ['Math', 'Three.js', 'Linear Algebra'],
    cover: { grad: 'from-cyan-700 via-blue-800 to-indigo-950', mark: '4×4', sub: 'Transforms · Eigenvalues · 3D' },
  },
  {
    key: 'openmat',
    label: 'OpenMAT',
    emoji: '⚛️',
    color: 'indigo',
    desc: 'Full-featured math computation engine — symbolic algebra, 3D graphing, matrix tools.',
    path: '/openmat',
    tags: ['Math', 'Platform'],
    cover: { grad: 'from-indigo-800 via-violet-900 to-purple-950', mark: '∫∑∇', sub: 'Computation Engine' },
  },
  {
    key: 'cnc-sim',
    label: 'CNC Simulator',
    emoji: '🔧',
    color: 'amber',
    desc: 'Program and simulate CNC toolpaths with a live 3D backplot and fixture management.',
    path: '/cnc-sim',
    tags: ['Engineering', 'CAD'],
    cover: { grad: 'from-amber-700 via-orange-800 to-red-950', mark: 'G0', sub: 'CNC · CAM · Toolpaths' },
  },
  {
    key: 'plc-lab',
    label: 'PLC Ladder Logic Lab',
    emoji: '🏭',
    color: 'orange',
    desc: 'Hands-on PLC ladder logic simulator — 8 exercises from motor start/stop to full FSM state machines. Allen-Bradley naming: XIC, XIO, OTE, OTL, OTU, TON, CTU, comparison, math.',
    path: '/plc-lab',
    tags: ['PLC', 'Industrial', 'Automation'],
    cover: { grad: 'from-orange-700 via-amber-800 to-yellow-950', mark: '⊣⊢', sub: 'XIC · TON · CTU · FSM' },
  },
  {
    key: 'logic-sim',
    label: 'Logic Suite',
    emoji: '⚡',
    color: 'violet',
    desc: 'Design and simulate digital logic circuits gate-by-gate with truth tables.',
    path: '/logic-sim',
    tags: ['CS', 'Engineering'],
    cover: { grad: 'from-violet-800 via-purple-900 to-indigo-950', mark: '⊕∧∨', sub: 'Gates · Truth Tables' },
  },
  {
    key: 'chemistry',
    label: 'Chemistry Lab',
    emoji: '🧪',
    color: 'cyan',
    desc: 'Explore chemical reactions, periodic table data, and molecular structures interactively.',
    event: 'chemistry',
    tags: ['Chemistry', 'Lab'],
    cover: { grad: 'from-cyan-700 via-teal-800 to-blue-950', mark: '⚗', sub: 'Reactions · Molecules' },
  },
  {
    key: 'physics',
    label: 'Physics Engine',
    emoji: '🌌',
    color: 'fuchsia',
    desc: 'Simulate rigid body dynamics, forces, springs, pendulums, and wave mechanics.',
    event: 'physics',
    tags: ['Physics', 'Simulation'],
    cover: { grad: 'from-fuchsia-700 via-pink-800 to-rose-950', mark: 'F=ma', sub: 'Rigid Body Dynamics' },
  },
  {
    key: 'cad-pro',
    label: 'CAD Pro',
    emoji: '📐',
    color: 'slate',
    desc: 'Parametric 3D modelling with constraint-based design tools.',
    path: '/cad-pro',
    tags: ['Engineering', 'Design'],
    cover: { grad: 'from-slate-600 via-slate-700 to-slate-900', mark: '⊡⊢', sub: 'Parametric Design' },
  },
  {
    key: 'universal-calc',
    label: 'Universal Calc',
    emoji: '🧮',
    color: 'emerald',
    desc: 'One calculator for everything — unit conversion, constants, formulas & numerical methods.',
    path: '/universal-calc',
    tags: ['Math', 'Tools'],
    cover: { grad: 'from-emerald-700 via-teal-800 to-cyan-950', mark: 'π e', sub: 'Universal Constants' },
  },
  {
    key: 'sicp-js',
    label: 'SICP — JavaScript',
    emoji: '📖',
    color: 'cyan',
    desc: 'Structure and Interpretation of Computer Programs, condensed as an interactive lesson. Narrated checkpoints, live code challenges, and CodeLens deep-dives — Chapter 1 first.',
    path: '/learn/sicp/1-1',
    tags: ['JavaScript', 'CS Theory', 'Interactive'],
    cover: { grad: 'from-cyan-700 via-sky-800 to-indigo-950', mark: 'λ', sub: 'SICP · JS · Checkpoints' },
  },
  {
    key: 'dsa-patterns',
    label: 'DSA + Design Patterns',
    emoji: '🧩',
    color: 'violet',
    desc: 'Data structures and design patterns taught together — because you need patterns to build data structures properly. Arrays, linked lists, stacks, trees, and graphs alongside Factory, Iterator, Command, Composite, and Strategy. TypeScript throughout.',
    path: '/learn/dsa-patterns/01',
    tags: ['TypeScript', 'DSA', 'Design Patterns', 'Interactive'],
    cover: { grad: 'from-violet-700 via-purple-800 to-indigo-950', mark: '⬡', sub: 'DSA · Patterns · Checkpoints' },
  },
  {
    key: 'codelens',
    label: 'CodeLens',
    emoji: '🔬',
    color: 'indigo',
    desc: 'Paste any JavaScript and watch it execute — token stream, AST, live heap graph, call stack, scope chain, and plain-English explanations at every step.',
    path: '/codelens',
    tags: ['JavaScript', 'CS Theory', 'Visualizer'],
    cover: { grad: 'from-indigo-700 via-violet-800 to-purple-950', mark: '{ }', sub: 'AST · Heap · Execution' },
  },
  {
    key: 'five-axis',
    label: '5-Axis Kinematics',
    emoji: '⚙️',
    color: 'violet',
    desc: 'Visualize 5-axis CNC kinematics live — homogeneous transforms, surface normals, lead/lag angles, and swarf cutting on parametric shapes. Full matrix stack shown.',
    path: '/five-axis',
    tags: ['CNC', 'Linear Algebra', 'Kinematics'],
    cover: { grad: 'from-violet-700 via-purple-800 to-indigo-950', mark: 'M·v', sub: 'CNC · Transforms · 5-Axis' },
  },
  {
    key: 'notebook-lab',
    label: 'Notebook Lab',
    emoji: '📓',
    color: 'indigo',
    desc: 'Create and run Python notebooks in the browser — write code, see output, download as .ipynb, upload from Jupyter, or import from GitHub.',
    path: '/notebook-lab',
    tags: ['Python', 'Data Science', 'Interactive'],
    cover: { grad: 'from-indigo-700 via-violet-800 to-purple-950', mark: '📓', sub: 'Python · .ipynb · Jupyter' },
  },
  {
    key: 'lesson-builder',
    label: 'Lesson Builder',
    emoji: '🔨',
    color: 'amber',
    desc: 'Build and preview interactive lessons — drag in code cells, prose, visualizations, and checkpoints. Export to the course system.',
    path: '/lesson-builder',
    tags: ['Tools', 'Content', 'Creator'],
    cover: { grad: 'from-amber-700 via-orange-800 to-red-950', mark: '🔨', sub: 'Cells · Preview · Export' },
  },
  {
    key: 'viz-builder',
    label: 'Viz Builder',
    emoji: '🔭',
    color: 'sky',
    desc: 'Build custom data visualizations and interactive diagrams for lessons and labs.',
    path: '/viz-builder',
    tags: ['Tools', 'Visualization', 'Creator'],
    cover: { grad: 'from-sky-700 via-blue-800 to-indigo-950', mark: '📊', sub: 'Charts · Diagrams · Interactive' },
  },
  {
    key: 'dsa-arrays-lab',
    label: 'Arrays & Memory Lab',
    emoji: '🧮',
    color: 'cyan',
    desc: 'Full hacker-workstation DSA lab: implement get, insert, delete, linear search, and binary search with live memory visualization and step tracer. JS + Python dual-language.',
    path: '/lab/dsa-arrays-lab',
    tags: ['DSA', 'Memory', 'Python', 'Interactive'],
    cover: { grad: 'from-cyan-700 via-slate-800 to-slate-950', mark: '[0]', sub: 'Memory · Pointers · O(n)' },
  },
  {
    key: 'dsa-linked-lists-lab',
    label: 'Linked Lists Lab',
    emoji: '🔗',
    color: 'cyan',
    desc: 'Full hacker-workstation DSA lab: build nodes, prepend/append, delete, reverse, and cycle detection with animated pointer visualization and step tracer. JS + Python dual-language.',
    path: '/lab/dsa-linked-lists-lab',
    tags: ['DSA', 'Pointers', 'Python', 'Interactive'],
    cover: { grad: 'from-cyan-800 via-slate-800 to-slate-950', mark: '→○→', sub: 'Nodes · Pointers · Cycles' },
  },
  {
    key: 'svg-studio',
    label: 'SVG Studio',
    emoji: '✏️',
    color: 'indigo',
    desc: 'Browser-based vector drawing tool — freehand pencil, drag-to-draw shapes, transform handles, layers panel, import any SVG, export as SVG or PNG. Great for building diagrams from scratch.',
    path: '/svg-studio',
    tags: ['Design', 'SVG', 'Creative', 'Interactive'],
    cover: { grad: 'from-indigo-600 via-purple-700 to-violet-950', mark: '✦', sub: 'Draw · Transform · Export' },
  },
]
