export default {
  id:'b-06',slug:'dot-product-and-similarity',track:'B',order:6,
  title:'Dot Product and Similarity',subtitle:'Measuring Alignment Between Vectors',
  tags:['dot-product', 'cosine-similarity', 'projection', 'perpendicular', 'angle'],prereqs:['b-05'],unlocks:['b-07', 'd-03'],
  hook:{question:'How do you measure how much two vectors point in the same direction?',realWorldContext:'Cosine similarity is the backbone of every recommendation system, every search engine, and every attention mechanism in transformers. It is computed from dot products. Before you can understand any of those systems, you need to understand what a dot product measures geometrically.'},
  intuition:{
    prose:['The dot product a·b = Σaᵢbᵢ = |a||b|cos(θ). When vectors point in the same direction: cos(0°)=1, maximum dot product. When perpendicular: cos(90°)=0, dot product is zero. When opposite: cos(180°)=-1, minimum.', '**Cosine similarity** = a·b / (|a||b|). It is the dot product normalized to [-1, 1]. It measures angle, not magnitude. Two vectors pointing in the same direction have cosine similarity 1 regardless of their lengths.', '**Projection** of a onto b: (a·b/|b|²)·b. The dot product appears in the formula because projection is about measuring how much of a is "in the direction of b."'],
    callouts:[{type:'important',title:'Why This Is Everywhere',body:'Recommendation: user_vector · item_vector = how much this user likes this item\nSearch: query_vector · document_vector = how relevant this document is\nAttention: Q · K^T = how much each query attends to each key\n\nAll three are dot products. Different names, same operation.'}],
    visualizations:[{id:'PythonNotebook',title:'Dot Product and Similarity',
      props:{initialCells:[{id:1,cellTitle:'Stage 1 — Dot Product Computation',prose:'Three equivalent ways to compute the dot product.',instructions:'Run. All three give the same result.',code:'import numpy as np\na = np.array([1.0, 2.0, 3.0])\nb = np.array([4.0, 5.0, 6.0])\nprint("Manual:", sum(ai*bi for ai,bi in zip(a,b)))\nprint("NumPy:", np.dot(a,b))\nprint("@ operator:", a @ b)',output:'',status:'idle'},
        {id:2,cellTitle:'Stage 2 — Dot Product and Angle',prose:'a·b = |a||b|cos(θ). Rearranging: cos(θ) = a·b / (|a||b|).',instructions:'Run. Verify: parallel vectors have dot product = product of magnitudes.',code:'import numpy as np\na = np.array([3.0, 0.0])\nb = np.array([0.0, 4.0])\ndot = np.dot(a, b)\ncos_angle = dot / (np.linalg.norm(a) * np.linalg.norm(b))\nangle_deg = np.degrees(np.arccos(np.clip(cos_angle, -1, 1)))\nprint(f"a·b = {dot}")\nprint(f"cos(θ) = {cos_angle}")\nprint(f"θ = {angle_deg:.1f}°")',output:'',status:'idle'},
        {id:3,cellTitle:'Stage 3 — Perpendicular Vectors',prose:'Perpendicular vectors have dot product = 0.',instructions:'Run. Then modify a and b so they are NOT perpendicular and verify the dot product changes.',code:'import numpy as np\na = np.array([1.0, 2.0])\nb = np.array([-2.0, 1.0])  # perpendicular to a\nprint(f"a·b = {np.dot(a,b)}")  # should be 0',output:'',status:'idle'},
        {id:4,cellTitle:'Stage 4 — Cosine Similarity',prose:'Cosine similarity measures angle between vectors, ignoring magnitude.',instructions:'Run. Notice "data science" and "machine learning" are more similar to each other than to "cooking".',code:'import numpy as np\ndef cos_sim(a, b):\n    return np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\n# Simplified word vectors (not real)\ndata_science = np.array([1,1,0,0,1,1,0])\nml = np.array([1,1,0,0,0,1,1])\ncooking = np.array([0,0,1,1,0,0,0])\nprint(f"data_science vs ml: {cos_sim(data_science,ml):.4f}")\nprint(f"data_science vs cooking: {cos_sim(data_science,cooking):.4f}")',output:'',status:'idle'},
        {id:11,challengeType:'write',challengeNumber:1,challengeTitle:'Challenge 1 — Most Similar',difficulty:'medium',prompt:'Given a query vector and three candidate vectors, find which candidate is most similar (highest cosine similarity). Store the index (0,1,2) in most_similar.',instructions:'1. Compute cosine similarity between query and each candidate.\n2. Find the index of the maximum.\n3. Store in most_similar.',code:'import numpy as np\nquery = np.array([1.0, 0.5, 0.0, 1.0])\ncandidates = [np.array([1.0,0.6,0.1,0.9]), np.array([0.0,0.0,1.0,0.0]), np.array([0.5,0.3,0.0,0.5])]\nmost_similar = ',output:'',status:'idle',testCode:'\nimport numpy as np\ndef cos_sim(a,b): return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))\nquery=np.array([1.0,0.5,0.0,1.0])\ncandidates=[np.array([1.0,0.6,0.1,0.9]),np.array([0.0,0.0,1.0,0.0]),np.array([0.5,0.3,0.0,0.5])]\nsims=[cos_sim(query,c) for c in candidates]\nexpected=sims.index(max(sims))\nif most_similar!=expected: raise ValueError(f"Expected {expected} (sims={[f\'{s:.3f}\' for s in sims]}), got {most_similar}")\nres=f"SUCCESS: Candidate {most_similar} is most similar. Cosine similarities: {[f\'{s:.3f}\' for s in sims]}"\nres\n',hint:'sims=[np.dot(query,c)/(np.linalg.norm(query)*np.linalg.norm(c)) for c in candidates]\nmost_similar=sims.index(max(sims))'}]}
    }],
  },
  mentalModel:['Dot product a·b = Σaᵢbᵢ = |a||b|cos(θ).', 'Same direction: cos(0°)=1. Perpendicular: cos(90°)=0. Opposite: cos(180°)=-1.', 'Cosine similarity = a·b/(|a||b|). Measures angle, not magnitude.', 'np.dot(a,b) or a @ b. Both compute the same thing.', 'Dot product underlies: recommendation systems, search, attention in transformers.'],
}